// ScreenShot.cpp -- hand-owned since frameDumpGetNextFileName was added.
//
// The accessor part (frameDumpGetFPS) was generated by
// tools/gen_accessors.py and is kept as it was written; gen_units.py
// now HOLDS this file rather than regenerating it. The other function
// was read from the image with tools/disasm.py: the null result set
// first (li r3,0), the flag tested (lbz, cmpwi, beqlr), and the file
// name's address as the other return. The two are defined in the
// order retail places them, which the link honours.

class Graphics {
public:
    static float frameDumpFPS;
    static bool frameDumpInProgress;
    static char frameDumpFileName[256];

    float frameDumpGetFPS();
    const char* frameDumpGetNextFileName();
};

const char* Graphics::frameDumpGetNextFileName() {
    if (!frameDumpInProgress) {
        return 0;
    }

    return frameDumpFileName;
}

float Graphics::frameDumpGetFPS() { return Graphics::frameDumpFPS; }
