// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.


class hkpClosestRayHitCollector {
public:
    hkpClosestRayHitCollector();
    virtual void __vtable_anchor();
};



class zCommonPlayerAction {
public:
    zCommonPlayerAction();
    unsigned char _pad[0xC];
};



class zSBPlayerAction : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zSBPlayerAction();

};



class zPlayerLandSB : public zSBPlayerAction {
public:
    virtual void __vtable_anchor();
    zPlayerLandSB();

};



class zSBCastCollector : public hkpClosestRayHitCollector {
public:
    virtual void __vtable_anchor();
    zSBCastCollector();

};


#pragma dont_inline on
zSBPlayerAction::zSBPlayerAction() : zCommonPlayerAction() {}
zPlayerLandSB::zPlayerLandSB() : zSBPlayerAction() {}
zSBCastCollector::zSBCastCollector() : hkpClosestRayHitCollector() {}
#pragma dont_inline off
