// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here is one load or one store and a return. Each
// offset was decoded from the image and re-encoded back to the
// same bytes before being written. GENERATED, not read: real
// matched functions whose offsets are recovered fact, but a count
// of them is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each accessor touches are known, not the fields between.


class hkpRigidBody {
public:
    float getAngularDamping() const;
    float getLinearDamping() const;
    float getRestitution() const;
    void setAngularDamping(float value);
    void setLinearDamping(float value);

    unsigned char _pad0[0x90];
    float f90;
    unsigned char _pad1[0x100];
    float f194;
    float f198;
};


namespace World {

class xOGModel {
public:
    int GetPrototype() const;

    unsigned char _pad0[0xDC];
    int fDC;
};

}  // namespace World

namespace Graphics {

class Node {
public:
    int GetNodeType() const;

    unsigned char _pad0[0x4];
    int f4;
};

}  // namespace Graphics

float hkpRigidBody::getRestitution() const { return f90; }
float hkpRigidBody::getLinearDamping() const { return f194; }
float hkpRigidBody::getAngularDamping() const { return f198; }
void hkpRigidBody::setLinearDamping(float value) { f194 = value; }
void hkpRigidBody::setAngularDamping(float value) { f198 = value; }
int World::xOGModel::GetPrototype() const { return fDC; }
int Graphics::Node::GetNodeType() const { return f4; }
