// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

class zCommonPlayer;


class zInteractionUP {
public:
    void Start(zCommonPlayer* value);
    void Starting();
    void Stop(zCommonPlayer* a0);

    unsigned char _pad0[0x44];
    int f44;
    unsigned char _pad1[0x1];
    unsigned char f49;
};



class zInteractionUPWithIcons {
public:
    void SetupIcons();

    unsigned char _pad0[0x80];
    unsigned char f80;
    unsigned char f81;
};



class zInteractionManager {
public:
    void Reset();

    int f0;
    int f4;
};


void zInteractionUP::Start(zCommonPlayer* value) { f44 = (int)value; }
void zInteractionUP::Stop(zCommonPlayer* a0) { f49 = 0; }
void zInteractionUPWithIcons::SetupIcons() { f80 = 1; f81 = 1; }
void zInteractionUP::Starting() { f49 = 1; }
void zInteractionManager::Reset() { f4 = 0; f0 = 0; }
