// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.


class zPlayerAction {
public:
    zPlayerAction();
    unsigned char _pad[0xC];
};



class zCommonPlayerAction : public zPlayerAction {
public:
    virtual void __vtable_anchor();
    zCommonPlayerAction();

};



class zBoardPlayerAction : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zBoardPlayerAction();

};



class zPlayerSkidStop : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zPlayerSkidStop();

};



class zPlayerSlip : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zPlayerSlip();

};



class zPlayerFallToDeath : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zPlayerFallToDeath();

};



class zPlayerLandBoard : public zBoardPlayerAction {
public:
    virtual void __vtable_anchor();
    zPlayerLandBoard();

};



class zPlayerTriggered : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zPlayerTriggered();

};



class zPlayerHit : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zPlayerHit();

};



class zPlayerHitLaunch : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zPlayerHitLaunch();

};



class zCommonPlayerDash : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zCommonPlayerDash();

};



class zPlayerWalkStart : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zPlayerWalkStart();

};



class zPlayerCustomAnim : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zPlayerCustomAnim();

};



class zPlayerCheat : public zCommonPlayerAction {
public:
    virtual void __vtable_anchor();
    zPlayerCheat();

};



class zBoardPlayer {
public:
    float GetRigidBodyHeight();

    unsigned char _pad0[0xAA4];
    float fAA4;
};



class zPlayer {
public:
    const int* GetFloorNormal() const;

    unsigned char _pad0[0x160];
    int f160;
};



class zPlayerTurn180Board {
public:
    void Begin();

    unsigned char _pad0[0x1C];
    unsigned char f1C;
};



class ProjectileCollisionDetails {
public:
    ProjectileCollisionDetails();

    int f0;
    int f4;
    unsigned char _pad2[0x24];
    int f2C;
};



class hkpCdBodyPairCollector {
public:
    void reset();

    unsigned char _pad0[0x4];
    unsigned char f4;
};


zBoardPlayerAction::zBoardPlayerAction() : zCommonPlayerAction() {}
zCommonPlayerAction::zCommonPlayerAction() : zPlayerAction() {}
zPlayerSkidStop::zPlayerSkidStop() : zCommonPlayerAction() {}
zPlayerSlip::zPlayerSlip() : zCommonPlayerAction() {}
zPlayerFallToDeath::zPlayerFallToDeath() : zCommonPlayerAction() {}
zPlayerLandBoard::zPlayerLandBoard() : zBoardPlayerAction() {}
zPlayerTriggered::zPlayerTriggered() : zCommonPlayerAction() {}
zPlayerHit::zPlayerHit() : zCommonPlayerAction() {}
zPlayerHitLaunch::zPlayerHitLaunch() : zCommonPlayerAction() {}
zCommonPlayerDash::zCommonPlayerDash() : zCommonPlayerAction() {}
zPlayerWalkStart::zPlayerWalkStart() : zCommonPlayerAction() {}
zPlayerCustomAnim::zPlayerCustomAnim() : zCommonPlayerAction() {}
zPlayerCheat::zPlayerCheat() : zCommonPlayerAction() {}
float zBoardPlayer::GetRigidBodyHeight() { return fAA4; }
const int* zPlayer::GetFloorNormal() const { return &f160; }
void zPlayerTurn180Board::Begin() { f1C = 0; }
ProjectileCollisionDetails::ProjectileCollisionDetails() { f0 = 0; f4 = 0; f2C = 0; }
void hkpCdBodyPairCollector::reset() { f4 = 0; }
