// GENERATED by tools/gen_poolprefix.py; regenerate, do not edit.
//
// WAD04_6.cpp is a fragment of the unity translation unit WAD04.cpp.
// That unit's string pool (@stringBase0 at 0x80691E9C, 3068 bytes)
// is filled in order of first appearance across every file it
// included, and a reference bakes the string's pool OFFSET into
// the instruction. The 220 strings below are the ones that come
// before this file's own, in that order, so that compiled alone
// it gets the same offsets. This is data read from the image;
// retail has no such table, it has the files in front.

// The files in front also put .rodata ahead of this unit's
// float literals: in the image the unit's first literal
// (0x80691560) lies 74508 bytes past the lowest .rodata address the
// unit's translation unit forms (0x8067F254). mwcc shares one base
// among a function's literals only when they sit under 32 KB
// into .rodata, so a fragment compiled with nothing ahead is
// one word short per table. The image shows only what the
// linker kept, so the measured distance is a lower bound; the
// array is that distance or 32 KB, whichever is more. It is
// referenced by nothing and holds nothing.
static const unsigned char kUnityRodataAhead[74508] = {1};

static const char* const kUnityPoolPrefix[] = {
    "DebugFont",  // +0
    "~",  // +10
    "reset",  // +12
    "word",  // +18
    "char",  // +23
    "none",  // +28
    "left",  // +33
    "center",  // +38
    "right",  // +45
    "top",  // +51
    "bottom",  // +55
    " ",  // +62
    "rot",  // +64
    "dst",  // +68
    "off",  // +72
    "scale",  // +76
    "screen",  // +82
    "diffuseMap",  // +89
    "0x",  // +100
    "src",  // +103
    "font",  // +107
    "size",  // +112
    "font_width",  // +117
    "font_height",  // +128
    "screen_width",  // +140
    "screen_height",  // +153
    "ProgrammaticUIImmediateModel_reference",  // +167
    "_XOR}",  // +206
    "%d:%02d",  // +212
    "%.*s",  // +220
    "%d",  // +225
    "TXT_WIP",  // +228
    "SL05",  // +236
    "",  // +241
    "stop00",  // +242
    "xEntAutoEventSimple",  // +249
    "loop%02d",  // +269
    "stop%02d",  // +278
    "TRUE",  // +287
    "MissingModel_ModelReference",  // +292
    "LevelProgression",  // +320
    "N/A",  // +337
    "%u%%",  // +341
    "Unknown (TODO)",  // +346
    "Save_Banner_UIDRef",  // +361
    "SFX",  // +380
    "master",  // +384
    "TXT_DEMO",  // +391
    "_root.loadingMovie.ShowAnswer",  // +400
    "_root.loadingMovie.AnimateOut",  // +430
    "_root.loadingMovie.HideLoading",  // +460
    "TtHavokRayCasts",  // +491
    "Et",  // +507
    "ShowMessageBox",  // +510
    "HideMessageBox",  // +525
    "MessageBox_reference",  // +540
    "_root.driver.autosavingStop",  // +561
    "_root.subMenu.SaveLoadDone",  // +589
    "_root.subMenu.SaveLoadFailed",  // +616
    "_root.subMenu.SaveLoadDisabled",  // +645
    "_root.subMenu.SaveLoadRefresh",  // +676
    "EnableMask",  // +706
    "DisableMask",  // +717
    "HideMask",  // +729
    "_level0.SignInChanged",  // +738
    "Stop",  // +760
    "Restart",  // +765
    "UI",  // +773
    "UImusic",  // +776
    "UIdialog",  // +784
    "UIcine",  // +793
    "AnimFinished",  // +800
    "MessageBoxOut",  // +813
    "MessageBoxIn",  // +827
    "SetSubtitlesEnabled",  // +840
    "true",  // +860
    "PlayAttractVideo",  // +865
    "PlayMotionPlusVideo",  // +882
    "/sys/mpls_movie/player.dol",  // +902
    "ASPECT_RATIO_AUTO",  // +929
    "PlayVideo",  // +947
    "Movie%s_Subtitles_reference",  // +957
    "EnableCheatEntry",  // +985
    "ShowSellScreen",  // +1002
    "DEMO_SellScreen_reference",  // +1017
    "ExitDemo",  // +1043
    "EnableCheat",  // +1052
    "DisableCheat",  // +1064
    "UnlockCheat",  // +1077
    "GetPadLock",  // +1089
    "ClearPadLock",  // +1100
    "EnforceTRC",  // +1113
    "WiiTRCBackOut",  // +1124
    "WiiTRCBackOutOver",  // +1138
    "WiiAllOpen",  // +1156
    "WiiNotWaiting",  // +1167
    "MotionReady",  // +1181
    "MotionSelected",  // +1193
    "WiiAllWaiting",  // +1208
    "ClearTRC",  // +1222
    "EnableTRC",  // +1231
    "DisableTRC",  // +1241
    "ConfirmConfirm",  // +1252
    "WaitForConfirm",  // +1267
    "ClearConfirm",  // +1282
    "RevertConfirm",  // +1295
    "SetRumbleState",  // +1309
    "EnablePointers",  // +1324
    "DisablePointers",  // +1339
    "HidePointers",  // +1355
    "AddInput",  // +1368
    "RemoveInput",  // +1377
    "ClearInput",  // +1389
    "ResetInput",  // +1400
    "StartWiiMotionPlusCalibration",  // +1411
    "EnableMotionPlus",  // +1441
    "DisableMotionPlus",  // +1458
    "EnableWiiNunchuck",  // +1476
    "EnableWiiClassicController",  // +1494
    "EnableGamecubeController",  // +1521
    "DPDForceOff",  // +1546
    "DPDOn",  // +1558
    "Unpause",  // +1564
    "ControlOn",  // +1572
    "Quit",  // +1582
    "ActivatePortalWidget",  // +1587
    "Portal",  // +1608
    "PortalToIndex",  // +1615
    "Start",  // +1629
    "SetSubGameType",  // +1635
    "ShowSigninChangedMsgBoxIfNeeded",  // +1650
    "IgnoreSignIn",  // +1682
    "SetReadyForTermination",  // +1695
    "StartGame",  // +1718
    "Yes",  // +1728
    "No",  // +1732
    "SetLanguage",  // +1735
    "ForceGarbageCollect",  // +1747
    "IncreaseMaxHealth",  // +1767
    "ControlOff",  // +1785
    "SaveData",  // +1796
    "LoadData",  // +1805
    "SaveReset",  // +1814
    "SetAutoSaveSlot",  // +1824
    "ClearAutoSaveSlot",  // +1840
    "DeleteData",  // +1858
    "EnableSave",  // +1869
    "EnterLoadScreen",  // +1880
    "ChangeStorageDevice",  // +1896
    "DisableSave",  // +1916
    "PlaySoundFX",  // +1928
    "StopSoundFX",  // +1940
    "SetSoundFXVolume",  // +1952
    "SetMusicVolume",  // +1969
    "SetCinematicVolume",  // +1984
    "SetDialogVolume",  // +2003
    "PlaySoundFXRemote",  // +2019
    "SpendHappyPoints",  // +2037
    "COLLECTIBLE_HAPPY_POINT_COUNTER_reference",  // +2054
    "IsFirstBoot",  // +2096
    "GetString",  // +2108
    "IsSubtitlesEnabled",  // +2118
    "GetNumCheats",  // +2137
    "IsCheatEnabled",  // +2150
    "IsCheatUnlocked",  // +2165
    "GetRumbleState",  // +2181
    "GetPrimaryController",  // +2196
    "GetWiiMotionPlusCalibration",  // +2217
    "IsWaitingOnBackOut",  // +2245
    "WasWiiNunchuckEnabled",  // +2264
    "WasWiiClassicControllerEnabled",  // +2286
    "WasGamecubeControllerEnabled",  // +2317
    "WasGameCubeButtonUsed",  // +2346
    "WasClassicButtonUsed",  // +2368
    "IsWiiNunchuckConnected",  // +2389
    "IsWiiClassicControllerConnected",  // +2412
    "IsWiiClassicControllerEnabled",  // +2444
    "IsWiiMotionPlusConnected",  // +2474
    "IsGamecubeControllerConnected",  // +2499
    "IsGamecubeControllerEnabled",  // +2529
    "IsBiplane",  // +2557
    "GetSubGameType",  // +2567
    "GetMaxLevelUnlocked",  // +2582
    "GetLevelIndex",  // +2602
    "IsWii",  // +2616
    "IsX360",  // +2622
    "IsPS3",  // +2629
    "IsWideScreen",  // +2635
    "IsDemo",  // +2648
    "GetDemoType",  // +2655
    "GetLanguage",  // +2667
    "IsNunchukConnected",  // +2679
    "GetHappyPoints",  // +2698
    "GetCounterCount",  // +2713
    "ResetCounterCount",  // +2729
    "GetSelectedCostume",  // +2747
    "SetSelectedCostume",  // +2766
    "IsCostumeBought",  // +2785
    "SetCostumeBought",  // +2801
    "GetMaxHealth",  // +2818
    "GetNPCsKilled",  // +2831
    "GetSlotStr",  // +2845
    "IsSlotEmpty",  // +2856
    "GetSceneIdx",  // +2868
    "GetHappyObjects",  // +2880
    "GetLives",  // +2896
    "GetSoundFXVolume",  // +2905
    "GetMusicVolume",  // +2922
    "GetCinematicVolume",  // +2937
    "GetDialogVolume",  // +2956
    "RUNNING",  // +2972
    "SUSPEND",  // +2980
    "COMPLETE",  // +2988
    "FAIL",  // +2997
    "ABORT",  // +3002
    "UNKNOWN",  // +3008
    "SearchManager",  // +3016
    "XmonEnableProfiling",  // +3030
    "XmonClientIp",  // +3050
    "PLYR",  // +3063
};
