// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

namespace Sext { class ActionBase; }
namespace Sext { class BTNodeBase; }
namespace World { class EntityHandleBase; }
class zBTClient;

namespace World {

class xOGEntity {
public:
    xOGEntity(World::EntityHandleBase* a0);
    virtual void __vtable_anchor();
};

}  // namespace World


class xEffectAttachIntf : public World::xOGEntity {
public:
    virtual void __vtable_anchor();
    xEffectAttachIntf(World::EntityHandleBase* a0);

};



class zBreakawayPlatform {
public:
    int* DriveGetCurMat(int a0);
    const int* GetSoundPosition() const;

    unsigned char _pad0[0x1B4];
    int f1B4;
    unsigned char _pad1[0x2C];
    int f1E4;
};



class zBTActionHandleEvent {
public:
    int Update(float a0);

    unsigned char _pad0[0x10];
    int f10;
};



class zBTAction {
public:
    void SetAsset(const Sext::ActionBase* value);
    void SetBTClient(zBTClient* value);

    int f0;
    unsigned char _pad1[0x4];
    int f8;
};


namespace zBTNode {

class ChildIterator {
public:
    void Begin();

    unsigned char _pad0[0x8];
    int f8;
};

}  // namespace zBTNode


class zBTNodeAction {
public:
    void Setup(Sext::BTNodeBase* value);

    unsigned char _pad0[0x10];
    int f10;
};


xEffectAttachIntf::xEffectAttachIntf(World::EntityHandleBase* a0) : World::xOGEntity(a0) {}
int* zBreakawayPlatform::DriveGetCurMat(int a0) { return &f1B4; }
const int* zBreakawayPlatform::GetSoundPosition() const { return &f1E4; }
int zBTActionHandleEvent::Update(float a0) { return f10; }
void zBTAction::SetBTClient(zBTClient* value) { f8 = (int)value; }
void zBTAction::SetAsset(const Sext::ActionBase* value) { f0 = (int)value; }
void zBTNode::ChildIterator::Begin() { f8 = 0; }
void zBTNodeAction::Setup(Sext::BTNodeBase* value) { f10 = (int)value; }
