// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

namespace FX { class activity_data; }
namespace World { class EntityHandleBase; }

namespace FX {

class zFXSpawn {
public:
    zFXSpawn(World::EntityHandleBase* a0);
    virtual void __vtable_anchor();
};

}  // namespace FX

namespace FX {

class zFXSpawnWithSoundAssetMultiple : public FX::zFXSpawn {
public:
    virtual void __vtable_anchor();
    zFXSpawnWithSoundAssetMultiple(World::EntityHandleBase* a0);

};

}  // namespace FX

namespace FX {
namespace Particles {
namespace Locator {

class Sphere {
public:
    void release_volume(FX::activity_data& a0);

    unsigned char _pad0[0x4];
    int f4;
};

}  // namespace Locator
}  // namespace Particles
}  // namespace FX

FX::zFXSpawnWithSoundAssetMultiple::zFXSpawnWithSoundAssetMultiple(World::EntityHandleBase* a0) : FX::zFXSpawn(a0) {}
void FX::Particles::Locator::Sphere::release_volume(FX::activity_data& a0) { f4 = 0; }
