// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

class xVec3;

// Each class below stands in for one a member points at.
// Nothing NAMES that class -- these five words carry no
// relocation -- so it is named after where it was found,
// and holds virtuals only up to the slot that is called.
class xCamBlend_m14C {
public:
    virtual void _v0() const;
    virtual void _v1() const;
    virtual void _v2() const;
    virtual void _v3() const;
    virtual void _v4() const;
    virtual void _v5() const;
    virtual void _v6() const;
    virtual void _v7() const;
    virtual void _v8() const;
    virtual void _v9() const;
    virtual void _v10() const;
    virtual void _v11() const;
    virtual void _v12() const;
    virtual void _v13() const;
    virtual void _v14() const;
    virtual void _v15(xVec3* a0, xVec3* a1) const;
};

namespace World {

class ModelPrototypeEntity {
public:
    int* GetModelPrototype();

    unsigned char _pad0[0x20];
    int f20;
};

}  // namespace World


class xCamTimeBias {
public:
    float GetBias();

    unsigned char _pad0[0x8];
    float f8;
};



class xCamBlend {
public:
    void GetTargets(xVec3* a0, xVec3* a1) const;

    unsigned char _pad0[0x14C];
    int f14C;
};


int* World::ModelPrototypeEntity::GetModelPrototype() { return &f20; }
float xCamTimeBias::GetBias() { return f8; }
void xCamBlend::GetTargets(xVec3* a0, xVec3* a1) const { ((xCamBlend_m14C*)f14C)->_v15(a0, a1); }
