// GENERATED by tools/gen_poolprefix.py; regenerate, do not edit.
//
// WAD02_20_1.cpp is a fragment of a unity translation unit and builds no
// string pool of its own, but the files in front of it put .rodata
// ahead of its float literals: in the image the unit's first
// literal (0x8068BA28) lies 50872 bytes past the lowest .rodata address
// the translation unit forms (0x8067F370). mwcc shares one base among
// a function's literals only when they sit under 32 KB into
// .rodata, so a fragment compiled with nothing ahead shares a base
// retail does not. The image shows only what the linker kept, so
// the measured distance is a lower bound; the array is that
// distance or 32 KB, whichever is more. It is referenced by
// nothing and holds nothing.
static const unsigned char kUnityRodataAhead[50872] = {1};
