// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

extern float afterTimer;
extern unsigned char screenLetterBoxActive;
extern unsigned char uiHDREnabled;
namespace UIMgr { extern int activeUIPads; }
namespace UIMgr { extern unsigned char pauseEnabled; }


class zUI {
public:
    unsigned char IsForceHDR();

    unsigned char _pad0[0xE7];
    unsigned char fE7;
};


float zUIGetTimer();
void zUIMgrEnableHDR(bool value);
void zUIMgrEnablePause(bool value);
int zUIMgrGetActivePadMask();
unsigned char zUIMgrGetScreenLetterBox();
void zUIMgrSetActivePadMask(unsigned int value);
void zUIMgrSetScreenLetterBox(bool value);

float zUIGetTimer() { return afterTimer; }
void zUIMgrEnablePause(bool value) { UIMgr::pauseEnabled = value; }
void zUIMgrSetScreenLetterBox(bool value) { screenLetterBoxActive = value; }
unsigned char zUIMgrGetScreenLetterBox() { return screenLetterBoxActive; }
unsigned char zUI::IsForceHDR() { return fE7; }
void zUIMgrEnableHDR(bool value) { uiHDREnabled = value; }
void zUIMgrSetActivePadMask(unsigned int value) { UIMgr::activeUIPads = value; }
int zUIMgrGetActivePadMask() { return UIMgr::activeUIPads; }
