// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

class zNPCBase;


class zDirection {
public:
    float GetYaw();

    unsigned char _pad0[0x4C];
    float f4C;
};



class zCommonPlayer {
public:
    const int* GetFloorPosition() const;
    void ZeroPointGrab(zNPCBase* value);
    void ZeroPointResetState();

    unsigned char _pad0[0x154];
    int f154;
    unsigned char _pad1[0x650];
    int f7A8;
    int f7AC;
    int f7B0;
};



class zPlayerSlip {
public:
    void Reset();

    unsigned char _pad0[0x10];
    int f10;
};



class zPlayerTriggered {
public:
    void Reset();

    unsigned char _pad0[0x24];
    int f24;
};



class zCommonPlayerDash {
public:
    unsigned int GetID();

};


float zDirection::GetYaw() { return f4C; }
const int* zCommonPlayer::GetFloorPosition() const { return &f154; }
void zCommonPlayer::ZeroPointGrab(zNPCBase* value) { f7A8 = (int)value; }
void zCommonPlayer::ZeroPointResetState() { f7A8 = 0; f7AC = 0; f7B0 = 0; }
void zPlayerSlip::Reset() { f10 = 0; }
void zPlayerTriggered::Reset() { f24 = 4; }
unsigned int zCommonPlayerDash::GetID() { return 0x0000000Fu; }
