// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here is one load or one store and a return. Each
// offset was decoded from the image and re-encoded back to the
// same bytes before being written. GENERATED, not read: real
// matched functions whose offsets are recovered fact, but a count
// of them is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each accessor touches are known, not the fields between.

namespace Graphics {

class LightPointSpot {
public:
    void SetLightMask(unsigned short value);
    void SetViewportVisibleMask(unsigned short value);

    unsigned char _pad0[0x12];
    unsigned short f12;
    unsigned short f14;
};

}  // namespace Graphics

void Graphics::LightPointSpot::SetViewportVisibleMask(unsigned short value) { f12 = value; }
void Graphics::LightPointSpot::SetLightMask(unsigned short value) { f14 = value; }
