// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here is one load or one store and a return. Each
// offset was decoded from the image and re-encoded back to the
// same bytes before being written. GENERATED, not read: real
// matched functions whose offsets are recovered fact, but a count
// of them is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each accessor touches are known, not the fields between.


class zUI {
public:
    unsigned char GetBrightness();
    float GetHeight();
    float GetRotation();
    float GetWidth();
    unsigned char IsRestoreFocus();
    void SetBrightness(unsigned char value);
    void SetHeight(float value);
    void SetRotation(float value);
    void SetWidth(float value);

    unsigned char _pad0[0x60];
    float f60;
    float f64;
    unsigned char _pad2[0x10];
    float f78;
    unsigned char _pad3[0x8];
    unsigned char f84;
    unsigned char _pad4[0x63];
    unsigned char fE8;
};



class zPlayerInputHuman {
public:
    int GetPadType();
    unsigned char IsPadDisabled();
    unsigned char NunchukConnected();
    unsigned char WiiClassicControllerConnected();
    unsigned char WiiRemoteConnected();

    unsigned char _pad0[0x2C];
    int f2C;
    unsigned char _pad1[0x8];
    unsigned char f38;
    unsigned char _pad2[0x1D7];
    unsigned char f210;
    unsigned char f211;
    unsigned char f212;
};


unsigned char zUI::GetBrightness() { return f84; }
float zUI::GetRotation() { return f78; }
float zUI::GetHeight() { return f64; }
float zUI::GetWidth() { return f60; }
void zUI::SetBrightness(unsigned char value) { f84 = value; }
void zUI::SetRotation(float value) { f78 = value; }
void zUI::SetHeight(float value) { f64 = value; }
void zUI::SetWidth(float value) { f60 = value; }
unsigned char zUI::IsRestoreFocus() { return fE8; }
unsigned char zPlayerInputHuman::WiiRemoteConnected() { return f210; }
unsigned char zPlayerInputHuman::NunchukConnected() { return f211; }
unsigned char zPlayerInputHuman::WiiClassicControllerConnected() { return f212; }
unsigned char zPlayerInputHuman::IsPadDisabled() { return f38; }
int zPlayerInputHuman::GetPadType() { return f2C; }
