// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here is one load or one store and a return. Each
// offset was decoded from the image and re-encoded back to the
// same bytes before being written. GENERATED, not read: real
// matched functions whose offsets are recovered fact, but a count
// of them is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each accessor touches are known, not the fields between.

namespace Graphics {

class Renderable3D {
public:
    void SetShadowCastDepth(float value);

    unsigned char _pad0[0xB0];
    float fB0;
};

}  // namespace Graphics


class zPlayer {
public:
    int GetCombat();
    int GetSurface() const;
    void SetViewport(int value);
    unsigned char SkipCharacterProxyHavokUpdate();

    unsigned char _pad0[0x6C];
    int f6C;
    unsigned char _pad1[0x8C];
    int fFC;
    unsigned char _pad2[0x108];
    unsigned char f208;
    unsigned char _pad3[0x13];
    int f21C;
};


void Graphics::Renderable3D::SetShadowCastDepth(float value) { fB0 = value; }
int zPlayer::GetCombat() { return f21C; }
void zPlayer::SetViewport(int value) { fFC = value; }
unsigned char zPlayer::SkipCharacterProxyHavokUpdate() { return f208; }
int zPlayer::GetSurface() const { return f6C; }
