// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

namespace Sext { class ConditionBase; }


class zBTAction {
public:
    zBTAction();
    unsigned char _pad[0xC];
};



class zModule {
public:
    zModule();
    unsigned char _pad[0x14];
};



class zCamWorldDrivable {
public:
    int* DriveGetCurMat(int a0);

    unsigned char _pad0[0x228];
    int f228;
};



class zNPCBTCondition {
public:
    unsigned int GetBTFamily() const;

};



class zBTConditionPlayerIsInAction {
public:
    unsigned int GetTypeID() const;
    void Setup(const Sext::ConditionBase* value);

    unsigned char _pad0[0xC];
    int fC;
};



class zBTConditionIsAnyPlayerInCombat {
public:
    unsigned int GetTypeID() const;

};



class zBTConditionDistanceFromPlayer {
public:
    unsigned int GetTypeID() const;

};



class zBTConditionDistanceFromClosestPlayer {
public:
    unsigned int GetTypeID() const;

};



class zBTConditionCheckConditional {
public:
    unsigned int GetTypeID() const;

};



class zBTConditionCheckVariable {
public:
    unsigned int GetTypeID() const;

};



class zBTActionWriteToBlackboard {
public:
    unsigned int GetTypeID() const;

};



class zBTActionWriteVariable {
public:
    unsigned int GetTypeID() const;

};



class zBTActionHandleEvent {
public:
    unsigned int GetTypeID() const;

};



class zBTActionSendEvent {
public:
    unsigned int GetTypeID() const;

};



class zPlayer {
public:
    float GetLastLand();

    unsigned char _pad0[0x400];
    float f400;
};



class zPlayerSlide {
public:
    unsigned int GetID();

};



class zPlayerCelebrationBoard {
public:
    unsigned int GetID();

};



class zPlayerDefeatedBoard {
public:
    unsigned int GetID();

};



class zBoardPlayerKelpTrap {
public:
    unsigned int GetID();

};



class zPlayerCheat {
public:
    unsigned int GetID();

};



class zBoardPlayerBungeeBall {
public:
    unsigned int GetID();

};



class zBoardPlayerQuicksandStuck {
public:
    unsigned int GetID();

};



class zBoardPlayerQuicksandJump {
public:
    unsigned int GetID();

};



class zBoardPlayerCandy {
public:
    unsigned int GetID();

};



class zBoardPlayerLosePowerup {
public:
    unsigned int GetID();

};



class zBoardPlayerPuckPowerupAttack {
public:
    unsigned int GetID();

};



class zBoardPlayerHammerPowerupAttack {
public:
    unsigned int GetID();

};



class zBoardPlayerSpinPowerupAttack {
public:
    unsigned int GetID();

};



class zBoardPlayerGainPowerup {
public:
    unsigned int GetID();

};



class zBoardPlayerDrainGoo {
public:
    unsigned int GetID();

};



class zBoardPlayerFillWithGoo {
public:
    unsigned int GetID();

};



class zPlayerHitLaunchBoard {
public:
    unsigned int GetID();

};



class zPlayerHitBoard {
public:
    unsigned int GetID();

};



class zPlayerLedgeBoard {
public:
    unsigned int GetID();

};



class zBoardPlayerPuckAttack {
public:
    unsigned int GetID();

};



class zBoardPlayerHammerAttack {
public:
    unsigned int GetID();

};



class zBoardPlayerSpinAttack {
public:
    unsigned int GetID();

};



class zPlayerSpringboardBoard {
public:
    unsigned int GetID();

};



class zPlayerDoubleJumpBoard {
public:
    unsigned int GetID();

};



class zPlayerLandHighBoard {
public:
    unsigned int GetID();

};



class zPlayerLandBoard {
public:
    unsigned int GetID();

};



class zPlayerFallBoard {
public:
    unsigned int GetID();

};



class zPlayerFluidBurstBoard {
public:
    unsigned int GetID();

};



class zPlayerSlamLandBoard {
public:
    unsigned int GetID();

};



class zPlayerSlamFallBoard {
public:
    unsigned int GetID();

};



class zPlayerSlamStartBoard {
public:
    unsigned int GetID();

};



class zPlayerFluidSprayBoard {
public:
    unsigned int GetID();

};



class zPlayerJumpBoard {
public:
    unsigned int GetID();

};



class zPlayerTurn180Board {
public:
    unsigned int GetID();

};



class zPlayerCustomAnim {
public:
    unsigned int GetID();

};



class zPlayerFallToDeath {
public:
    unsigned int GetID();

};



class zPlayerTriggered {
public:
    unsigned int GetID();

};



class zPlayerSlip {
public:
    unsigned int GetID();

};



class zPlayerWalkStart {
public:
    unsigned int GetID();

};



class zDirection {
public:
    float GetPitch();
    float GetRoll();
    void SetPitch(float value);
    void SetRoll(float value);
    void SetYaw(float value);

    unsigned char _pad0[0x4C];
    float f4C;
    float f50;
    float f54;
};



class zCamDriver {
public:
    float getCurrentHeight() const;

    unsigned char _pad0[0x1B0];
    float f1B0;
};



class zAchievementsMgr : public zModule {
public:
    virtual void __vtable_anchor();
    zAchievementsMgr();

};



class zBTActionAlwaysComplete : public zBTAction {
public:
    virtual void __vtable_anchor();
    unsigned int GetTypeID() const;
    zBTActionAlwaysComplete();

};



class zBTActionAlwaysFail : public zBTAction {
public:
    virtual void __vtable_anchor();
    unsigned int GetTypeID() const;
    zBTActionAlwaysFail();

};



class zAnimViewerCamera {
public:
    virtual void __vtable_anchor();
    zAnimViewerCamera();

};



class zBTConditionFalse {
public:
    unsigned int GetTypeID() const;

};



class zBTConditionTrue {
public:
    unsigned int GetTypeID() const;

};


#pragma dont_inline on
int* zCamWorldDrivable::DriveGetCurMat(int a0) { return &f228; }
unsigned int zNPCBTCondition::GetBTFamily() const { return 0x00000003u; }
void zBTConditionPlayerIsInAction::Setup(const Sext::ConditionBase* value) { fC = (int)value; }
unsigned int zBTConditionPlayerIsInAction::GetTypeID() const { return 0x4EC7C3F6u; }
unsigned int zBTConditionIsAnyPlayerInCombat::GetTypeID() const { return 0x9D1EA338u; }
unsigned int zBTConditionDistanceFromPlayer::GetTypeID() const { return 0xD91878D8u; }
unsigned int zBTConditionDistanceFromClosestPlayer::GetTypeID() const { return 0xBE5CF04Fu; }
unsigned int zBTConditionCheckConditional::GetTypeID() const { return 0xB80413D6u; }
unsigned int zBTConditionCheckVariable::GetTypeID() const { return 0xD57AD404u; }
unsigned int zBTActionWriteToBlackboard::GetTypeID() const { return 0x307680C0u; }
unsigned int zBTActionWriteVariable::GetTypeID() const { return 0xFC57E1DAu; }
unsigned int zBTActionHandleEvent::GetTypeID() const { return 0xC65A85F5u; }
unsigned int zBTActionSendEvent::GetTypeID() const { return 0xD0762FE1u; }
float zPlayer::GetLastLand() { return f400; }
unsigned int zPlayerSlide::GetID() { return 0x0000002Bu; }
unsigned int zPlayerCelebrationBoard::GetID() { return 0x0000002Au; }
unsigned int zPlayerDefeatedBoard::GetID() { return 0x0000000Du; }
unsigned int zBoardPlayerKelpTrap::GetID() { return 0x00000024u; }
unsigned int zPlayerCheat::GetID() { return 0x00000011u; }
unsigned int zBoardPlayerBungeeBall::GetID() { return 0x00000023u; }
unsigned int zBoardPlayerQuicksandStuck::GetID() { return 0x00000022u; }
unsigned int zBoardPlayerQuicksandJump::GetID() { return 0x00000021u; }
unsigned int zBoardPlayerCandy::GetID() { return 0x00000020u; }
unsigned int zBoardPlayerLosePowerup::GetID() { return 0x0000001Fu; }
unsigned int zBoardPlayerPuckPowerupAttack::GetID() { return 0x0000001Eu; }
unsigned int zBoardPlayerHammerPowerupAttack::GetID() { return 0x0000001Du; }
unsigned int zBoardPlayerSpinPowerupAttack::GetID() { return 0x0000001Cu; }
unsigned int zBoardPlayerGainPowerup::GetID() { return 0x0000001Bu; }
unsigned int zBoardPlayerDrainGoo::GetID() { return 0x0000001Au; }
unsigned int zBoardPlayerFillWithGoo::GetID() { return 0x00000019u; }
unsigned int zPlayerHitLaunchBoard::GetID() { return 0x0000000Cu; }
unsigned int zPlayerHitBoard::GetID() { return 0x0000000Bu; }
unsigned int zPlayerLedgeBoard::GetID() { return 0x00000009u; }
unsigned int zBoardPlayerPuckAttack::GetID() { return 0x00000016u; }
unsigned int zBoardPlayerHammerAttack::GetID() { return 0x00000015u; }
unsigned int zBoardPlayerSpinAttack::GetID() { return 0x00000014u; }
unsigned int zPlayerSpringboardBoard::GetID() { return 0x00000018u; }
unsigned int zPlayerDoubleJumpBoard::GetID() { return 0x00000017u; }
unsigned int zPlayerLandHighBoard::GetID() { return 0x00000012u; }
unsigned int zPlayerLandBoard::GetID() { return 0x00000007u; }
unsigned int zPlayerFallBoard::GetID() { return 0x00000006u; }
unsigned int zPlayerFluidBurstBoard::GetID() { return 0x00000029u; }
unsigned int zPlayerSlamLandBoard::GetID() { return 0x00000027u; }
unsigned int zPlayerSlamFallBoard::GetID() { return 0x00000026u; }
unsigned int zPlayerSlamStartBoard::GetID() { return 0x00000025u; }
unsigned int zPlayerFluidSprayBoard::GetID() { return 0x00000028u; }
unsigned int zPlayerJumpBoard::GetID() { return 0x00000005u; }
unsigned int zPlayerTurn180Board::GetID() { return 0x00000013u; }
unsigned int zPlayerCustomAnim::GetID() { return 0x0000000Au; }
unsigned int zPlayerFallToDeath::GetID() { return 0x0000000Eu; }
unsigned int zPlayerTriggered::GetID() { return 0x00000008u; }
unsigned int zPlayerSlip::GetID() { return 0x00000004u; }
unsigned int zPlayerWalkStart::GetID() { return 0x00000010u; }
float zDirection::GetRoll() { return f54; }
float zDirection::GetPitch() { return f50; }
void zDirection::SetRoll(float value) { f54 = value; }
void zDirection::SetPitch(float value) { f50 = value; }
void zDirection::SetYaw(float value) { f4C = value; }
float zCamDriver::getCurrentHeight() const { return f1B0; }
zAchievementsMgr::zAchievementsMgr() : zModule() {}
zBTActionAlwaysComplete::zBTActionAlwaysComplete() : zBTAction() {}
zBTActionAlwaysFail::zBTActionAlwaysFail() : zBTAction() {}
zAnimViewerCamera::zAnimViewerCamera() {}
unsigned int zBTConditionFalse::GetTypeID() const { return 0x2EF3935Cu; }
unsigned int zBTConditionTrue::GetTypeID() const { return 0x89176D7Du; }
unsigned int zBTActionAlwaysFail::GetTypeID() const { return 0xFD239E46u; }
unsigned int zBTActionAlwaysComplete::GetTypeID() const { return 0xF7756BA5u; }
#pragma dont_inline off
