// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

enum ePlayerActivationState { ePlayerActivationState_ = 0x7FFFFFFF };
namespace World { class EntityHandleBase; }
class hkpPhantom;
class xAnimSingle;
class xAnimTransition;
class xEnt;


class xEnt {
public:
    xEnt(World::EntityHandleBase* a0);
    virtual void __vtable_anchor();
};



class zPlanktonTargetListener {
public:
    virtual void _v0() const;
    virtual void _v1() const;
    virtual void _v2() const;
    virtual void _v3() const;
    virtual void _v4() const;
    virtual void _v5() const;
    virtual void _v6() const;
    virtual void _v7() const;
    virtual void _v8() const;
    virtual void _v9() const;
    virtual void _v10() const;
    virtual void _v11() const;
    virtual void _v12() const;
    virtual void _v13() const;
    virtual void _v14(hkpPhantom* a0) const;
    void phantomDeletedCallback(hkpPhantom* a0);

};



class hkpWorldRayCastInput {
public:
    hkpWorldRayCastInput();

    unsigned char _pad0[0x20];
    unsigned char f20;
    unsigned char _pad1[0x3];
    int f24;
};



class hkpShapeRayCastInput {
public:
    hkpShapeRayCastInput();

    unsigned char _pad0[0x20];
    int f20;
    int f24;
};



class zPlanktonShakeManager {
public:
    static int currentShakeState;
    int* GetShakeState(const xEnt* a0);

};



class zPlantTrap {
public:
    int* GetAttachDPos();
    bool HitCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anDoneChewCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool DoneChewCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anEatCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool EatCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anGoToSpitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool GoToSpitCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anHitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    static bool anIdleCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool IdleCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anProneCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    static bool anProneOutCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool ProneOutCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anReleaseCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool ReleaseCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anSnapCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool SnapCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anSnapEntityCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool SnapEntityCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anSpitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool SpitCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anWarnCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool WarnCheck(xAnimTransition* a0, xAnimSingle* a1);

    unsigned char _pad0[0x5C];
    int f5C;
    unsigned char _pad1[0x30];
    int f90;
};



class zEnt : public xEnt {
public:
    virtual void __vtable_anchor();
    zEnt(World::EntityHandleBase* a0);

};


namespace Graphics {

class Renderable3D {
public:
    void SetShadowCastDepth(float value);

    unsigned char _pad0[0xB0];
    float fB0;
};

}  // namespace Graphics


class zPlayer {
public:
    int* GetAttachDPos();
    int GetCombat();
    int GetSurface() const;
    void SetPlayerActivationState(ePlayerActivationState value);
    void SetViewport(int value);
    unsigned char SkipCharacterProxyHavokUpdate();

    unsigned char _pad0[0x6C];
    int f6C;
    unsigned char _pad1[0x8C];
    int fFC;
    unsigned char _pad2[0x108];
    unsigned char f208;
    unsigned char _pad3[0x13];
    int f21C;
    unsigned char _pad4[0x14];
    int f234;
    unsigned char _pad5[0x1F8];
    int f430;
};


#pragma dont_inline on
void zPlanktonTargetListener::phantomDeletedCallback(hkpPhantom* a0) { _v14(a0); }
hkpWorldRayCastInput::hkpWorldRayCastInput() { f20 = 0; f24 = 0; }
hkpShapeRayCastInput::hkpShapeRayCastInput() { f20 = 0; f24 = 0; }
int* zPlanktonShakeManager::GetShakeState(const xEnt* a0) { return &zPlanktonShakeManager::currentShakeState; }
int* zPlantTrap::GetAttachDPos() { return &f90; }
bool zPlantTrap::anWarnCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->WarnCheck(a0, a1); }
bool zPlantTrap::anProneOutCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->ProneOutCheck(a0, a1); }
bool zPlantTrap::anSnapCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->SnapCheck(a0, a1); }
bool zPlantTrap::anSnapEntityCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->SnapEntityCheck(a0, a1); }
bool zPlantTrap::anReleaseCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->ReleaseCheck(a0, a1); }
bool zPlantTrap::anEatCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->EatCheck(a0, a1); }
bool zPlantTrap::anHitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->HitCheck(a0, a1); }
bool zPlantTrap::anGoToSpitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->GoToSpitCheck(a0, a1); }
bool zPlantTrap::anDoneChewCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->DoneChewCheck(a0, a1); }
bool zPlantTrap::anProneCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->f5C == 9; }
bool zPlantTrap::anSpitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->SpitCheck(a0, a1); }
bool zPlantTrap::anIdleCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->IdleCheck(a0, a1); }
bool zPlantTrap::HitCheck(xAnimTransition* a0, xAnimSingle* a1) { return f5C == 5; }
zEnt::zEnt(World::EntityHandleBase* a0) : xEnt(a0) {}
void Graphics::Renderable3D::SetShadowCastDepth(float value) { fB0 = value; }
int zPlayer::GetCombat() { return f21C; }
void zPlayer::SetViewport(int value) { fFC = value; }
unsigned char zPlayer::SkipCharacterProxyHavokUpdate() { return f208; }
int* zPlayer::GetAttachDPos() { return &f234; }
int zPlayer::GetSurface() const { return f6C; }
void zPlayer::SetPlayerActivationState(ePlayerActivationState value) { f430 = (int)value; }
#pragma dont_inline off
