// GENERATED by tools/gen_accessors.py from the retail image.
// HELD: another generator has added to this file -- tools/gen_assetfix.py
// wrote the Sext assets' Fix(long) into it, and tools/gen_rttid.py
// the RTTID_Fix block, so gen_units.py must NOT regenerate it. The
// accounting still counts every function here as generated, because
// every one of them is.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

namespace World { class EntityHandleBase; }
namespace World { class ShaderCodeBlobAsset; }

namespace Graphics {

class Node {
public:
    int GetNodeType() const;

    unsigned char _pad0[0x4];
    int f4;
};

}  // namespace Graphics

namespace World {

class ShaderCodeBlobAsset {
public:
    unsigned int Create(World::EntityHandleBase* a0, World::ShaderCodeBlobAsset* a1);

};

}  // namespace World

int Graphics::Node::GetNodeType() const { return f4; }
unsigned int World::ShaderCodeBlobAsset::Create(World::EntityHandleBase* a0, World::ShaderCodeBlobAsset* a1) { return 0x00000000u; }

// The event-link fixup every Sext asset's Fix(long) runs. The array
// is stored as a FILE OFFSET and turned into a pointer in place,
// then each link's two typed slots are fixed: the pointer by the
// RTTID the slot's type names, the value by Sext::FixWmlType. The
// link is 40 bytes -- the stride the `mulli r0,r0,40` carries, and
// it is the same 40 in every one of them.

template <class T>
class Pointer32 {
public:
    T Get() const;
};

namespace Sext {

class EventAny;

class EventLinkNew {
public:
    int srcType;
    Pointer32<Sext::EventAny*> src;
    int dstType;
    Pointer32<Sext::EventAny*> dst;
    unsigned char _pad0[40 - 16];
};

// Declared and not defined: every Fix calls it on `this` with r3
// unchanged, so it is a base at offset zero and empty.
class xBaseAsset {
public:
    void CustomFix(long base);
};

void FixWmlType(long base, int type, void* p);

// Sub-objects an asset owns and fixes in place: the call is
// `addi r3,r31,N` on the asset, not a load, so each is a member and
// each has a Fix of its own. Empty, and therefore ONE byte -- which
// is what the offsets of everything after them are measured against.
class PhysicsDataStruct { public: void Fix(long); };
class SoundBankSource { public: void Fix(long); };

}  // namespace Sext

namespace World {
class ModelInstanceAsset { public: void Fix(long); };
class ImmediateInstanceAsset { public: void Fix(long); };
}  // namespace World

// The RTTID_Fix<T> family -- see tools/gen_rttid.py. Each class
// below is a STUB: it carries a Fix(long) because the tail call
// needs one to name, and nothing else about it is known.

namespace Sext {
class AnimList { public: void Fix(long); };
class AnimPackage { public: void Fix(long); };
class AnimationSet { public: void Fix(long); };
class BSP : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x50];
    World::ModelInstanceAsset m50;
    unsigned char _pad1[0x47];
    Sext::PhysicsDataStruct m98;
    unsigned char _pad2[0x6F];
    int linkCount;
    EventLinkNew* links;
};
class BehaviorSet { public: void Fix(long); };
class BehaviorTree { public: void Fix(long); };
class Button_Masher_Widget : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x30];
    int linkCount;
    EventLinkNew* links;
};
class BuyScreen : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x10];
    void* other;
    unsigned char _pad1[0x4];
    int linkCount;
    EventLinkNew* links;
};
class CarlLedgeHoist : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x38];
    int linkCount;
    EventLinkNew* links;
};
class CharacterAssets { public: void Fix(long); };
class Clip { public: void Fix(long); };
class Curve { public: void Fix(long); };
class CurveCamera { public: void Fix(long); };
// Not a stub like the rest: its RTTID_Fix is SIXTEEN bytes and does
// the whole job itself -- lwz, add, stw -- so DTRMovieSettings::Fix
// relocates one pointer and is taken into the wrapper.
class DTRMovieSettings {
public:
    void Fix(long base) { offset += base; }

    long offset;
};
class Decal { public: void Fix(long); };
class DestructibleAsset { public: void Fix(long); };
class ElectricArcAsset { public: void Fix(long); };
class ElectricPointAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x10];
    World::ModelInstanceAsset m10;
    unsigned char _pad1[0x5F];
    int linkCount;
    EventLinkNew* links;
};
class ExplosiveProperties { public: void Fix(long); };
class FXObjectSystem { public: void Fix(long); };
class FXParticleSystem { public: void Fix(long); };
class FXSpawn { public: void Fix(long); };
class Flythrough : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x18];
    Sext::SoundBankSource m18;
    unsigned char _pad1[0xB];
    int linkCount;
    EventLinkNew* links;
};
class Function_Generator : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x34];
    int linkCount;
    EventLinkNew* links;
};
class GradientCurve : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x20];
    void* other;
    int linkCount;
    EventLinkNew* links;
};
class HudUp { public: void Fix(long); };
class InputMappingAsset { public: void Fix(long); };
class LaserAsset { public: void Fix(long); };
class Ledge { public: void Fix(long); };
class LensFlareSpawnPt { public: void Fix(long); };
class LightAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x30];
    World::ModelInstanceAsset m30;
    unsigned char _pad1[0x83];
    int linkCount;
    EventLinkNew* links;
};
class LoadingScreen { public: void Fix(long); };
class NPCAsset { public: void Fix(long); };
class NPCGroupAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x14];
    void* other;
    int linkCount;
    EventLinkNew* links;
};
class NPCPerceptionAsset { public: void Fix(long); };
class NPC_Combat { public: void Fix(long); };
class ParticleSink { public: void Fix(long); };
class PlayerAICommand { public: void Fix(long); };
class PlayerAICommandGroup { public: void Fix(long); };
class PlayerAnimSeq { public: void Fix(long); };
class Player_Location_Ent_Connector : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x14];
    void* other;
    unsigned char _pad1[0x1C];
    int linkCount;
    EventLinkNew* links;
};
class Pointer { public: void Fix(long); };
class ProjectileAsset { public: void Fix(long); };
class Ribbon { public: void Fix(long); };
class RuntimeEntityAsset { public: void Fix(long); };
class Scene { public: void Fix(long); };
class ScreenFade : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x20];
    int linkCount;
    EventLinkNew* links;
};
class Script { public: void Fix(long); };
class ShrapnelAssetDef { public: void Fix(long); };
class Springboard : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x44];
    int linkCount;
    EventLinkNew* links;
};
class SurfaceGamePlay : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0xA0];
    int linkCount;
    EventLinkNew* links;
};
class TargetList { public: void Fix(long); };
class TikiScreen { public: void Fix(long); };
class TriggerEntityAsset { public: void Fix(long); };
class TriggerPhantomAsset { public: void Fix(long); };
class UI_Box : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0xB0];
    World::ImmediateInstanceAsset mB0;
    unsigned char _pad1[0x3F];
    World::ImmediateInstanceAsset mF0;
    unsigned char _pad2[0x3F];
    World::ImmediateInstanceAsset m130;
    unsigned char _pad3[0x3F];
    World::ImmediateInstanceAsset m170;
    unsigned char _pad4[0x3F];
    World::ImmediateInstanceAsset m1B0;
    unsigned char _pad5[0x3F];
    World::ImmediateInstanceAsset m1F0;
    unsigned char _pad6[0x3F];
    World::ImmediateInstanceAsset m230;
    unsigned char _pad7[0x3F];
    World::ImmediateInstanceAsset m270;
    unsigned char _pad8[0x3F];
    World::ImmediateInstanceAsset m2B0;
    unsigned char _pad9[0x5F];
    int linkCount;
    EventLinkNew* links;
};
class UI_Controller : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0xA8];
    int linkCount;
    EventLinkNew* links;
};
class UI_Group { public: void Fix(long); };
class UI_Image : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0xB0];
    World::ImmediateInstanceAsset mB0;
    unsigned char _pad1[0x3F];
    int linkCount;
    EventLinkNew* links;
};
class UI_Model : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0xB0];
    World::ModelInstanceAsset mB0;
    unsigned char _pad1[0x47];
    int linkCount;
    EventLinkNew* links;
};
class UI_Text : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0xD8];
    int linkCount;
    EventLinkNew* links;
};
class UI_User_String : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0xDC];
    int linkCount;
    EventLinkNew* links;
};
class VehicleConfiguration { public: void Fix(long); };
class binary_poi : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x54];
    int linkCount;
    EventLinkNew* links;
};
class text_box : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x10];
    void* other;
    unsigned char _pad1[0x78];
    int linkCount;
    EventLinkNew* links;
};
class xCamAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x84];
    int linkCount;
    EventLinkNew* links;
};
class xCounterAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x14];
    int linkCount;
    EventLinkNew* links;
};
class xEntPlayerAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x50];
    World::ModelInstanceAsset m50;
    unsigned char _pad1[0x47];
    Sext::PhysicsDataStruct m98;
    unsigned char _pad2[0x93];
    int linkCount;
    EventLinkNew* links;
};
class xEnvAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x94];
    int linkCount;
    EventLinkNew* links;
};
class xMovePointAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x44];
    void* other;
    int linkCount;
    EventLinkNew* links;
};
class xPlatformAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x50];
    World::ModelInstanceAsset m50;
    unsigned char _pad1[0x47];
    Sext::PhysicsDataStruct m98;
    unsigned char _pad2[0x5F];
    int linkCount;
    EventLinkNew* links;
};
class xPortalAsset { public: void Fix(long); };
class xSimpleObjAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x50];
    World::ModelInstanceAsset m50;
    unsigned char _pad1[0x47];
    Sext::PhysicsDataStruct m98;
    unsigned char _pad2[0x7F];
    int linkCount;
    EventLinkNew* links;
};
class xSubtitlesAsset { public: void Fix(long); };
class xTimerAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x1C];
    int linkCount;
    EventLinkNew* links;
};
class zBranchSwitchAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x10];
    World::ModelInstanceAsset m10;
    unsigned char _pad1[0x93];
    Sext::SoundBankSource mA4;
    unsigned char _pad2[0xB];
    Sext::SoundBankSource mB0;
    unsigned char _pad3[0xB];
    Sext::SoundBankSource mBC;
    unsigned char _pad4[0xB];
    int linkCount;
    EventLinkNew* links;
};
class zBreakawayPlatformAsset { public: void Fix(long); };
class zBugSpawnerAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x30];
    World::ModelInstanceAsset m30;
    unsigned char _pad1[0x53];
    void* other;
    int linkCount;
    EventLinkNew* links;
};
class zBungeeBallAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x10];
    World::ModelInstanceAsset m10;
    unsigned char _pad1[0x5F];
    Sext::SoundBankSource m70;
    unsigned char _pad2[0x17];
    void* other;
    unsigned char _pad3[0x8];
    int linkCount;
    EventLinkNew* links;
};
class zCaveWormAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x30];
    World::ModelInstanceAsset m30;
    unsigned char _pad1[0x7F];
    int linkCount;
    EventLinkNew* links;
};
class zCheckpointAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x2C];
    void* other;
    unsigned char _pad1[0x24];
    int linkCount;
    EventLinkNew* links;
};
class zCinematicAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x18];
    Sext::SoundBankSource m18;
    unsigned char _pad1[0x13];
    int linkCount;
    EventLinkNew* links;
};
class zCondAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x30];
    void* other;
    int linkCount;
    EventLinkNew* links;
};
class zCrankAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x80];
    Sext::SoundBankSource m80;
    unsigned char _pad1[0x6F];
    World::ModelInstanceAsset mF0;
    unsigned char _pad2[0x5F];
    World::ModelInstanceAsset m150;
    unsigned char _pad3[0x5F];
    World::ModelInstanceAsset m1B0;
    unsigned char _pad4[0x4B];
    int linkCount;
    EventLinkNew* links;
};
class zCurrentAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x24];
    void* other;
    int linkCount;
    EventLinkNew* links;
};
class zDirectionAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x28];
    int linkCount;
    EventLinkNew* links;
};
class zDispatcherAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x10];
    int linkCount;
    EventLinkNew* links;
};
class zDogPackAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x40];
    int linkCount;
    EventLinkNew* links;
};
class zDragRopeAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x68];
    int linkCount;
    EventLinkNew* links;
};
class zDugLeverAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x40];
    World::ModelInstanceAsset m40;
    unsigned char _pad1[0x6F];
    World::ModelInstanceAsset mB0;
    unsigned char _pad2[0x5B];
    int linkCount;
    EventLinkNew* links;
};
class zEventSpyAsset { public: void Fix(long); };
class zFloatingCollectibleAsset { public: void Fix(long); };
class zFloatingCollectibleSpawnerAsset { public: void Fix(long); };
class zFountainAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x30];
    World::ModelInstanceAsset m30;
    unsigned char _pad1[0x5F];
    int linkCount;
    EventLinkNew* links;
};
class zGeyserAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x50];
    World::ModelInstanceAsset m50;
    unsigned char _pad1[0x3F];
    World::ModelInstanceAsset m90;
    unsigned char _pad2[0x63];
    Sext::SoundBankSource mF4;
    unsigned char _pad3[0xB];
    Sext::SoundBankSource m100;
    unsigned char _pad4[0xB];
    int linkCount;
    EventLinkNew* links;
};
class zHammerAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x40];
    World::ModelInstanceAsset m40;
    unsigned char _pad1[0x6B];
    int linkCount;
    EventLinkNew* links;
};
class zHintSphereAsset { public: void Fix(long); };
class zHitButtonAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x30];
    World::ModelInstanceAsset m30;
    unsigned char _pad1[0x3F];
    World::ModelInstanceAsset m70;
    unsigned char _pad2[0x4B];
    int linkCount;
    EventLinkNew* links;
};
class zHouseBalloonBounceAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x40];
    World::ModelInstanceAsset m40;
    unsigned char _pad1[0x5F];
    int linkCount;
    EventLinkNew* links;
};
class zHouseFloatAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0xC8];
    int linkCount;
    EventLinkNew* links;
};
class zInWorldIconWidgetAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x48];
    int linkCount;
    EventLinkNew* links;
};
class zInflatablePlatformAsset { public: void Fix(long); };
class zInteractRopeTieAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x3C];
    int linkCount;
    EventLinkNew* links;
};
class zInteractiveMusicAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x10];
    Sext::SoundBankSource m10;
    unsigned char _pad1[0xF];
    void* other;
    int linkCount;
    EventLinkNew* links;
};
class zKevinSpringboardAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x98];
    int linkCount;
    EventLinkNew* links;
};
class zLedgeShimmyAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x20];
    void* other;
    unsigned char _pad1[0x34];
    int linkCount;
    EventLinkNew* links;
};
class zLeverAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x50];
    World::ModelInstanceAsset m50;
    unsigned char _pad1[0x47];
    Sext::PhysicsDataStruct m98;
    unsigned char _pad2[0x5F];
    Sext::SoundBankSource mF8;
    unsigned char _pad3[0xB];
    Sext::SoundBankSource m104;
    unsigned char _pad4[0xB];
    Sext::SoundBankSource m110;
    unsigned char _pad5[0x2F];
    World::ModelInstanceAsset m140;
    unsigned char _pad6[0x4F];
    void* other;
    unsigned char _pad7[0x20];
    int linkCount;
    EventLinkNew* links;
};
class zMG2PCamAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x24];
    int linkCount;
    EventLinkNew* links;
};
class zManEatingPlantAsset { public: void Fix(long); };
class zPOWGroupAsset { public: void Fix(long); };
class zPOWObjectAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x1C];
    Sext::PhysicsDataStruct m1C;
    unsigned char _pad1[0x53];
    int linkCount;
    EventLinkNew* links;
};
class zPolygonalVolumeAsset { public: void Fix(long); };
class zPryAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x6C];
    int linkCount;
    EventLinkNew* links;
};
class zPuckReflectorAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x30];
    World::ModelInstanceAsset m30;
    unsigned char _pad1[0x67];
    int linkCount;
    EventLinkNew* links;
};
class zPushPullAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x78];
    int linkCount;
    EventLinkNew* links;
};
class zRandomModelListAsset { public: void Fix(long); };
class zRopeCutAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x74];
    int linkCount;
    EventLinkNew* links;
};
class zRubberBandAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x70];
    Sext::SoundBankSource m70;
    unsigned char _pad1[0xB];
    Sext::SoundBankSource m7C;
    unsigned char _pad2[0xB];
    Sext::SoundBankSource m88;
    unsigned char _pad3[0xB];
    int linkCount;
    EventLinkNew* links;
};
class zRussellRopeAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x50];
    Sext::SoundBankSource m50;
    unsigned char _pad1[0xB];
    Sext::SoundBankSource m5C;
    unsigned char _pad2[0xB];
    int linkCount;
    EventLinkNew* links;
};
class zSaveLoadAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x18];
    int linkCount;
    EventLinkNew* links;
};
class zSinkingSurfaceAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x14];
    void* other;
    unsigned char _pad1[0x50];
    int linkCount;
    EventLinkNew* links;
};
class zSlopeAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x14];
    void* other;
    unsigned char _pad1[0x40];
    int linkCount;
    EventLinkNew* links;
};
class zSniffAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x54];
    void* other;
    int linkCount;
    EventLinkNew* links;
};
class zSoundMaskAsset { public: void Fix(long); };
class zSoundWiimoteSpeakerListAsset { public: void Fix(long); };
class zSoundsNamedAsset { public: void Fix(long); };
class zSpinnerAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x30];
    World::ModelInstanceAsset m30;
    unsigned char _pad1[0x63];
    int linkCount;
    EventLinkNew* links;
};
class zSwingVineAsset { public: void Fix(long); };
class zTacticalCommanderAsset { public: void Fix(long); };
class zTikiAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x40];
    World::ModelInstanceAsset m40;
    unsigned char _pad1[0x8F];
    int linkCount;
    EventLinkNew* links;
};
class zTrampolineAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x50];
    World::ModelInstanceAsset m50;
    unsigned char _pad1[0x47];
    Sext::PhysicsDataStruct m98;
    unsigned char _pad2[0x67];
    int linkCount;
    EventLinkNew* links;
};
class zTrapAsset { public: void Fix(long); };
class zUIFlashOnScreenTextAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x10];
    void* other;
    unsigned char _pad1[0xC];
    int linkCount;
    EventLinkNew* links;
};
class zUIHintBoxAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x10];
    void* other;
    int linkCount;
    EventLinkNew* links;
};
class zUpFloatingBridgeAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x50];
    World::ModelInstanceAsset m50;
    unsigned char _pad1[0x63];
    Sext::SoundBankSource mB4;
    unsigned char _pad2[0xB];
    Sext::SoundBankSource mC0;
    unsigned char _pad3[0x17];
    int linkCount;
    EventLinkNew* links;
};
class zUpQuestCardAsset { public: void Fix(long); };
class zWaterAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x18];
    void* other;
    unsigned char _pad1[0x34];
    int linkCount;
    EventLinkNew* links;
};
class zWaterWheelAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x10];
    World::ModelInstanceAsset m10;
    unsigned char _pad1[0x5B];
    int linkCount;
    EventLinkNew* links;
};
class zWhirlpoolAsset : public xBaseAsset {
public:
    void Fix(long base);

    unsigned char _pad0[0x2C];
    int linkCount;
    EventLinkNew* links;
};
}  // namespace Sext

namespace World {
class GeometryAsset { public: void Fix(long); };
class TemplateAsset { public: void Fix(long); };
}  // namespace World

// These branch to another class's Fix -- T inherits it,
// or the linker folded two identical bodies into one.
// Either way the derivation emits the symbol retail has.
namespace Sext {
class AnimViewer : public Sext::NPCAsset { };
class Camera_Tweak : public Sext::zInWorldIconWidgetAsset { };
class Catapult : public Sext::zWhirlpoolAsset { };
class CollectibleSpawnerAsset : public Sext::zCondAsset { };
class FMVReference : public Sext::xCounterAsset { };
class HudSB : public Sext::zSaveLoadAsset { };
class KevinDanglePoint : public Sext::zDragRopeAsset { };
class LedgeGrab : public Sext::xTimerAsset { };
class Light_Effect_Flicker : public Sext::Button_Masher_Widget { };
class Light_Effect_Strobe : public Sext::CarlLedgeHoist { };
class NPCGroupCentipede : public Sext::NPCGroupAsset { };
class NavLink : public Sext::zMG2PCamAsset { };
class PlanktonReticle : public Sext::zSaveLoadAsset { };
class Reference : public Sext::zSaveLoadAsset { };
class Rumble : public Sext::CarlLedgeHoist { };
class Rumble_Box_Emitter : public Sext::Function_Generator { };
class Rumble_Spherical_Emitter : public Sext::zWhirlpoolAsset { };
class RussellDanglePoint : public Sext::zInWorldIconWidgetAsset { };
class ScreenWarp : public Sext::zDogPackAsset { };
class StringReference : public Sext::xCounterAsset { };
class UI_Motion : public Sext::zDispatcherAsset { };
class WallNetGroup : public Sext::zPolygonalVolumeAsset { };
class transition_time : public Sext::zDispatcherAsset { };
class xCamAssetD : public Sext::xCamAsset { };
class xGroupAsset : public Sext::zSaveLoadAsset { };
class zBiplaneCurveAsset : public Sext::zPolygonalVolumeAsset { };
class zCamTweakCurveAsset : public Sext::zCurrentAsset { };
class zCrawlAsset : public Sext::zPushPullAsset { };
class zCustomRobotAsset : public Sext::zDirectionAsset { };
class zFloatingCollectibleGroupAsset : public Sext::zPolygonalVolumeAsset { };
class zFogAsset : public Sext::zWhirlpoolAsset { };
class zLaserTurretAsset : public Sext::xPlatformAsset { };
class zNPCGenericPoolAsset : public Sext::zPolygonalVolumeAsset { };
class zScaleformAsset : public Sext::UI_User_String { };
class zStepUpAsset : public Sext::zDragRopeAsset { };
class zTriggerAsset : public Sext::xCounterAsset { };
class zTripAsset : public Sext::CarlLedgeHoist { };
}  // namespace Sext

namespace World {
class StaticGeometryAsset : public World::GeometryAsset { };
}  // namespace World

namespace Util {

// Recovered from the branch target and the two symbols: the call is
// T::Fix(long) on the pointer, tail-called, so the body is one word.
template <class T>
void RTTID_Fix(void* p, long l) {
    ((T*)p)->Fix(l);
}

}  // namespace Util

template void Util::RTTID_Fix<World::StaticGeometryAsset>(void*, long);
template void Util::RTTID_Fix<Sext::Curve>(void*, long);
template void Util::RTTID_Fix<Sext::Clip>(void*, long);
template void Util::RTTID_Fix<Sext::zSoundsNamedAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zSoundWiimoteSpeakerListAsset>(void*, long);
template void Util::RTTID_Fix<Sext::DestructibleAsset>(void*, long);
template void Util::RTTID_Fix<Sext::Decal>(void*, long);
template void Util::RTTID_Fix<Sext::AnimList>(void*, long);
template void Util::RTTID_Fix<Sext::AnimationSet>(void*, long);
template void Util::RTTID_Fix<Sext::BSP>(void*, long);
template void Util::RTTID_Fix<Sext::xCamAsset>(void*, long);
template void Util::RTTID_Fix<Sext::xCamAssetD>(void*, long);
template void Util::RTTID_Fix<Sext::zMG2PCamAsset>(void*, long);
template void Util::RTTID_Fix<Sext::CurveCamera>(void*, long);
template void Util::RTTID_Fix<Sext::CharacterAssets>(void*, long);
template void Util::RTTID_Fix<Sext::zCondAsset>(void*, long);
template void Util::RTTID_Fix<Sext::xCounterAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zSaveLoadAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zDispatcherAsset>(void*, long);
template void Util::RTTID_Fix<Sext::xEnvAsset>(void*, long);
template void Util::RTTID_Fix<Sext::xGroupAsset>(void*, long);
template void Util::RTTID_Fix<Sext::xMovePointAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zTacticalCommanderAsset>(void*, long);
template void Util::RTTID_Fix<Sext::NPC_Combat>(void*, long);
template void Util::RTTID_Fix<Sext::xEntPlayerAsset>(void*, long);
template void Util::RTTID_Fix<Sext::xPlatformAsset>(void*, long);
template void Util::RTTID_Fix<Sext::ProjectileAsset>(void*, long);
template void Util::RTTID_Fix<Sext::RuntimeEntityAsset>(void*, long);
template void Util::RTTID_Fix<Sext::Script>(void*, long);
template void Util::RTTID_Fix<Sext::xSimpleObjAsset>(void*, long);
template void Util::RTTID_Fix<Sext::xTimerAsset>(void*, long);
template void Util::RTTID_Fix<Sext::TriggerPhantomAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zTriggerAsset>(void*, long);
template void Util::RTTID_Fix<Sext::TriggerEntityAsset>(void*, long);
template void Util::RTTID_Fix<Sext::SurfaceGamePlay>(void*, long);
template void Util::RTTID_Fix<Sext::zDirectionAsset>(void*, long);
template void Util::RTTID_Fix<Sext::xPortalAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zEventSpyAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zPolygonalVolumeAsset>(void*, long);
template void Util::RTTID_Fix<Sext::ElectricPointAsset>(void*, long);
template void Util::RTTID_Fix<Sext::ElectricArcAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zFloatingCollectibleSpawnerAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zFloatingCollectibleGroupAsset>(void*, long);
template void Util::RTTID_Fix<Sext::CollectibleSpawnerAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zFloatingCollectibleAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zBreakawayPlatformAsset>(void*, long);
template void Util::RTTID_Fix<Sext::ParticleSink>(void*, long);
template void Util::RTTID_Fix<Sext::zCinematicAsset>(void*, long);
template void Util::RTTID_Fix<Sext::GradientCurve>(void*, long);
template void Util::RTTID_Fix<Sext::zPOWObjectAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zPOWGroupAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zInWorldIconWidgetAsset>(void*, long);
template void Util::RTTID_Fix<Sext::LensFlareSpawnPt>(void*, long);
template void Util::RTTID_Fix<Sext::zRandomModelListAsset>(void*, long);
template void Util::RTTID_Fix<Sext::AnimPackage>(void*, long);
template void Util::RTTID_Fix<Sext::zUpFloatingBridgeAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zSwingVineAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zRussellRopeAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zDragRopeAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zInteractRopeTieAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zLeverAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zDogPackAsset>(void*, long);
template void Util::RTTID_Fix<Sext::Ledge>(void*, long);
template void Util::RTTID_Fix<Sext::LedgeGrab>(void*, long);
template void Util::RTTID_Fix<Sext::RussellDanglePoint>(void*, long);
template void Util::RTTID_Fix<Sext::KevinDanglePoint>(void*, long);
template void Util::RTTID_Fix<Sext::CarlLedgeHoist>(void*, long);
template void Util::RTTID_Fix<Sext::zPushPullAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zTrapAsset>(void*, long);
template void Util::RTTID_Fix<Sext::xSubtitlesAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zTripAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zManEatingPlantAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zCaveWormAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zCrawlAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zHouseFloatAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zStepUpAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zSniffAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zHouseBalloonBounceAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zKevinSpringboardAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zPryAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zDugLeverAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zCrankAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zRopeCutAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zHitButtonAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zTrampolineAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zPuckReflectorAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zSpinnerAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zHammerAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zRubberBandAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zFountainAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zTikiAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zBungeeBallAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zInflatablePlatformAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zWaterWheelAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zWaterAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zCurrentAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zWhirlpoolAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zSinkingSurfaceAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zLedgeShimmyAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zHintSphereAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zSlopeAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zBugSpawnerAsset>(void*, long);
template void Util::RTTID_Fix<Sext::PlayerAnimSeq>(void*, long);
template void Util::RTTID_Fix<Sext::InputMappingAsset>(void*, long);
template void Util::RTTID_Fix<Sext::NavLink>(void*, long);
template void Util::RTTID_Fix<Sext::WallNetGroup>(void*, long);
template void Util::RTTID_Fix<Sext::zBranchSwitchAsset>(void*, long);
template void Util::RTTID_Fix<Sext::BehaviorTree>(void*, long);
template void Util::RTTID_Fix<Sext::BehaviorSet>(void*, long);
template void Util::RTTID_Fix<Sext::PlayerAICommand>(void*, long);
template void Util::RTTID_Fix<Sext::PlayerAICommandGroup>(void*, long);
template void Util::RTTID_Fix<Sext::zSoundMaskAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zFogAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zBiplaneCurveAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zLaserTurretAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zInteractiveMusicAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zNPCGenericPoolAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zGeyserAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zUpQuestCardAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zCustomRobotAsset>(void*, long);
template void Util::RTTID_Fix<Sext::LaserAsset>(void*, long);
template void Util::RTTID_Fix<Sext::ScreenWarp>(void*, long);
template void Util::RTTID_Fix<World::TemplateAsset>(void*, long);
template void Util::RTTID_Fix<Sext::VehicleConfiguration>(void*, long);
template void Util::RTTID_Fix<Sext::TargetList>(void*, long);
template void Util::RTTID_Fix<Sext::Pointer>(void*, long);
template void Util::RTTID_Fix<Sext::Button_Masher_Widget>(void*, long);
template void Util::RTTID_Fix<Sext::Flythrough>(void*, long);
template void Util::RTTID_Fix<Sext::Camera_Tweak>(void*, long);
template void Util::RTTID_Fix<Sext::zCamTweakCurveAsset>(void*, long);
template void Util::RTTID_Fix<Sext::text_box>(void*, long);
template void Util::RTTID_Fix<Sext::Player_Location_Ent_Connector>(void*, long);
template void Util::RTTID_Fix<Sext::Reference>(void*, long);
template void Util::RTTID_Fix<Sext::StringReference>(void*, long);
template void Util::RTTID_Fix<Sext::Function_Generator>(void*, long);
template void Util::RTTID_Fix<Sext::UI_Text>(void*, long);
template void Util::RTTID_Fix<Sext::UI_User_String>(void*, long);
template void Util::RTTID_Fix<Sext::UI_Image>(void*, long);
template void Util::RTTID_Fix<Sext::UI_Model>(void*, long);
template void Util::RTTID_Fix<Sext::UI_Box>(void*, long);
template void Util::RTTID_Fix<Sext::UI_Controller>(void*, long);
template void Util::RTTID_Fix<Sext::zScaleformAsset>(void*, long);
template void Util::RTTID_Fix<Sext::UI_Motion>(void*, long);
template void Util::RTTID_Fix<Sext::UI_Group>(void*, long);
template void Util::RTTID_Fix<Sext::HudUp>(void*, long);
template void Util::RTTID_Fix<Sext::HudSB>(void*, long);
template void Util::RTTID_Fix<Sext::PlanktonReticle>(void*, long);
template void Util::RTTID_Fix<Sext::TikiScreen>(void*, long);
template void Util::RTTID_Fix<Sext::BuyScreen>(void*, long);
template void Util::RTTID_Fix<Sext::LoadingScreen>(void*, long);
template void Util::RTTID_Fix<Sext::Rumble>(void*, long);
template void Util::RTTID_Fix<Sext::Rumble_Box_Emitter>(void*, long);
template void Util::RTTID_Fix<Sext::Rumble_Spherical_Emitter>(void*, long);
template void Util::RTTID_Fix<Sext::ScreenFade>(void*, long);
template void Util::RTTID_Fix<Sext::ShrapnelAssetDef>(void*, long);
template void Util::RTTID_Fix<Sext::LightAsset>(void*, long);
template void Util::RTTID_Fix<Sext::Light_Effect_Flicker>(void*, long);
template void Util::RTTID_Fix<Sext::Light_Effect_Strobe>(void*, long);
template void Util::RTTID_Fix<Sext::NPCPerceptionAsset>(void*, long);
template void Util::RTTID_Fix<Sext::NPCGroupCentipede>(void*, long);
template void Util::RTTID_Fix<Sext::AnimViewer>(void*, long);
template void Util::RTTID_Fix<Sext::Scene>(void*, long);
template void Util::RTTID_Fix<Sext::transition_time>(void*, long);
template void Util::RTTID_Fix<Sext::binary_poi>(void*, long);
template void Util::RTTID_Fix<Sext::zCheckpointAsset>(void*, long);
template void Util::RTTID_Fix<Sext::Springboard>(void*, long);
template void Util::RTTID_Fix<Sext::Ribbon>(void*, long);
template void Util::RTTID_Fix<Sext::FMVReference>(void*, long);
template void Util::RTTID_Fix<Sext::ExplosiveProperties>(void*, long);
template void Util::RTTID_Fix<Sext::Catapult>(void*, long);
template void Util::RTTID_Fix<Sext::zUIFlashOnScreenTextAsset>(void*, long);
template void Util::RTTID_Fix<Sext::zUIHintBoxAsset>(void*, long);
template void Util::RTTID_Fix<Sext::FXParticleSystem>(void*, long);
template void Util::RTTID_Fix<Sext::FXObjectSystem>(void*, long);
template void Util::RTTID_Fix<Sext::FXSpawn>(void*, long);

template void Util::RTTID_Fix<Sext::DTRMovieSettings>(void*, long);

#pragma dont_inline on
void Sext::BSP::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m50.Fix(base);
    m98.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::Button_Masher_Widget::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::CarlLedgeHoist::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::ElectricPointAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m10.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::Flythrough::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m18.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::Function_Generator::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::LightAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m30.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::ScreenFade::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::Springboard::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::SurfaceGamePlay::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::UI_Box::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    mB0.Fix(base);
    mF0.Fix(base);
    m130.Fix(base);
    m170.Fix(base);
    m1B0.Fix(base);
    m1F0.Fix(base);
    m230.Fix(base);
    m270.Fix(base);
    m2B0.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::UI_Controller::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::UI_Image::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    mB0.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::UI_Model::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    mB0.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::UI_Text::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::UI_User_String::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::binary_poi::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::xCamAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::xCounterAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::xEntPlayerAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m50.Fix(base);
    m98.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::xEnvAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::xPlatformAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m50.Fix(base);
    m98.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::xSimpleObjAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m50.Fix(base);
    m98.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::xTimerAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zBranchSwitchAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m10.Fix(base);
    mA4.Fix(base);
    mB0.Fix(base);
    mBC.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zCaveWormAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m30.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zCinematicAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m18.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zCondAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zCrankAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m80.Fix(base);
    mF0.Fix(base);
    m150.Fix(base);
    m1B0.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zDirectionAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zDispatcherAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zDogPackAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zDragRopeAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zDugLeverAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m40.Fix(base);
    mB0.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zFountainAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m30.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zGeyserAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m50.Fix(base);
    m90.Fix(base);
    mF4.Fix(base);
    m100.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zHammerAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m40.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zHitButtonAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m30.Fix(base);
    m70.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zHouseBalloonBounceAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m40.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zHouseFloatAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zInWorldIconWidgetAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zInteractRopeTieAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zKevinSpringboardAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zMG2PCamAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zPOWObjectAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m1C.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zPryAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zPuckReflectorAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m30.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zPushPullAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zRopeCutAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zRubberBandAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m70.Fix(base);
    m7C.Fix(base);
    m88.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zRussellRopeAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m50.Fix(base);
    m5C.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zSaveLoadAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zSpinnerAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m30.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zTikiAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m40.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zTrampolineAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m50.Fix(base);
    m98.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zUpFloatingBridgeAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m50.Fix(base);
    mB4.Fix(base);
    mC0.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zWaterWheelAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m10.Fix(base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zWhirlpoolAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}
#pragma dont_inline off


#pragma dont_inline on
void Sext::BuyScreen::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::GradientCurve::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::NPCGroupAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::Player_Location_Ent_Connector::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::text_box::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::xMovePointAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zBugSpawnerAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m30.Fix(base);
    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zBungeeBallAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m10.Fix(base);
    m70.Fix(base);
    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zCheckpointAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zCurrentAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zInteractiveMusicAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m10.Fix(base);
    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zLedgeShimmyAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zLeverAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    m50.Fix(base);
    m98.Fix(base);
    mF8.Fix(base);
    m104.Fix(base);
    m110.Fix(base);
    m140.Fix(base);
    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zSinkingSurfaceAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zSlopeAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zSniffAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zUIFlashOnScreenTextAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zUIHintBoxAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}

void Sext::zWaterAsset::Fix(long base) {
    EventLinkNew* end;
    EventLinkNew* p;

    CustomFix(base);

    other = (void*)((long)other + base);
    p = (EventLinkNew*)((long)links + base);
    links = p;
    end = p + linkCount;

    while (p != end) {
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->src, base);
        Sext::FixWmlType(base, p->srcType, p->src.Get());
        Util::RTTID_Fix<Sext::DTRMovieSettings>(&p->dst, base);
        Sext::FixWmlType(base, p->dstType, p->dst.Get());
        p++;
    }
}
#pragma dont_inline off
