// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.


class zBoardPlayer {
public:
    float GetRigidBodyHeight();

    unsigned char _pad0[0xAA4];
    float fAA4;
};



class zPlayer {
public:
    const int* GetFloorNormal() const;

    unsigned char _pad0[0x160];
    int f160;
};



class zPlayerTurn180Board {
public:
    void Begin();

    unsigned char _pad0[0x1C];
    unsigned char f1C;
};



class ProjectileCollisionDetails {
public:
    ProjectileCollisionDetails();

    int f0;
    int f4;
    unsigned char _pad2[0x24];
    int f2C;
};



class hkpCdBodyPairCollector {
public:
    void reset();

    unsigned char _pad0[0x4];
    unsigned char f4;
};


float zBoardPlayer::GetRigidBodyHeight() { return fAA4; }
const int* zPlayer::GetFloorNormal() const { return &f160; }
void zPlayerTurn180Board::Begin() { f1C = 0; }
ProjectileCollisionDetails::ProjectileCollisionDetails() { f0 = 0; f4 = 0; f2C = 0; }
void hkpCdBodyPairCollector::reset() { f4 = 0; }
