// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.


class zNPCBTClientBase {
public:
    int GetOwner() const;

    unsigned char _pad0[0x1A0];
    int f1A0;
};


namespace Graphics {

class LightKitData {
public:
    LightKitData();

    unsigned char _pad0[0x70];
    int f70;
    int f74;
    int f78;
};

}  // namespace Graphics

int zNPCBTClientBase::GetOwner() const { return f1A0; }
Graphics::LightKitData::LightKitData() { f70 = 0; f74 = 0; f78 = 0; }
