// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here is one load or one store and a return. Each
// offset was decoded from the image and re-encoded back to the
// same bytes before being written. GENERATED, not read: real
// matched functions whose offsets are recovered fact, but a count
// of them is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each accessor touches are known, not the fields between.

namespace Graphics {

class Geometry {
public:
    int GetVertexCount() const;

    unsigned char _pad0[0x60];
    int f60;
};

}  // namespace Graphics

namespace Graphics {

class StaticBuilder {
public:
    int GetFixedVertexBuffers() const;

    unsigned char _pad0[0xCC];
    int fCC;
};

}  // namespace Graphics

namespace Graphics {

class FixedVertexBuffer {
public:
    int GetReadBuffer() const;

    unsigned char _pad0[0xC];
    int fC;
};

}  // namespace Graphics


class xEnt {
public:
    int DriveGetDriver();
    int GetAttachMat();

    unsigned char _pad0[0x34];
    int f34;
    unsigned char _pad1[0x30];
    int f68;
};


int Graphics::Geometry::GetVertexCount() const { return f60; }
int Graphics::StaticBuilder::GetFixedVertexBuffers() const { return fCC; }
int Graphics::FixedVertexBuffer::GetReadBuffer() const { return fC; }
int xEnt::GetAttachMat() { return f34; }
int xEnt::DriveGetDriver() { return f68; }
