// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

namespace System {

// A base only in the sense that r3 reaches it unchanged:
// the branch is four bytes and names nothing else.
class CriticalSection {
public:
    void Enter();
    void Exit();
};

}  // namespace System


class Graphics {
public:
    static int renderThreadCriticalSection;
    void RenderLoopEnterCS();
    void RenderLoopExitCS();

};


void Graphics::RenderLoopEnterCS() { ((System::CriticalSection*)&Graphics::renderThreadCriticalSection)->Enter(); }
void Graphics::RenderLoopExitCS() { ((System::CriticalSection*)&Graphics::renderThreadCriticalSection)->Exit(); }
