// GENERATED by tools/gen_poolprefix.py; regenerate, do not edit.
//
// zBouncer.cpp is a fragment of a unity translation unit and builds no
// string pool of its own, but the files in front of it put .rodata
// ahead of its float literals: in the image the unit's first
// literal (0x806893B8) lies 41320 bytes past the lowest .rodata address
// the translation unit forms (0x8067F250). mwcc shares one base among
// a function's literals only when they sit under 32 KB into
// .rodata, so a fragment compiled with nothing ahead shares a base
// retail does not. This array is that distance, measured; it is
// referenced by nothing and holds nothing.
static const unsigned char kUnityRodataAhead[41320] = {1};
