// GENERATED by tools/gen_poolprefix.py; regenerate, do not edit.
//
// zBuyScreen.cpp is a fragment of the unity translation unit WAD02.cpp.
// That unit's string pool (@stringBase0 at 0x8068BE28, 5231 bytes)
// is filled in order of first appearance across every file it
// included, and a reference bakes the string's pool OFFSET into
// the instruction. The 88 strings below are the ones that come
// before this file's own, in that order, so that compiled alone
// it gets the same offsets. This is data read from the image;
// retail has no such table, it has the files in front.

static const char* const kUnityPoolPrefix[] = {
    "BalloonB",  // +0
    "BalloonB1",  // +9
    "BalloonB2",  // +19
    "BalloonB3",  // +29
    "BalloonB4",  // +39
    "BalloonB5",  // +49
    "BalloonS",  // +59
    "BalloonS1",  // +68
    "BalloonS2",  // +78
    "BalloonS3",  // +88
    "BalloonG",  // +98
    "BalloonG1",  // +107
    "MissingModel_ModelReference",  // +117
    "SBNuggetBecomeUnhappyScriptRef",  // +145
    "UID_A_BOOT_collect_unhap_nug",  // +176
    "FLOATING_COLLECTIBLE_TURN_UNHAPPY",  // +205
    "FloatingCollectible",  // +239
    "zFountain",  // +259
    "GlobalPuckAttackCounterReference",  // +269
    "CollectibleSpawner",  // +302
    "WMLTYPE_SpawnCollectible_Event",  // +321
    "WMLTYPE_SpawnCollectibleAtPosition_Event",  // +352
    "%d",  // +393
    "FMV%c%s_%s",  // +396
    "FMV%c%s",  // +407
    "master",  // +415
    "SB_Hammer_Widget_Rumble_FX_Ref",  // +422
    "Hammer",  // +453
    "HammerUp",  // +460
    "HammerStriking",  // +469
    "HammerImpact",  // +484
    "HammerRecoil",  // +497
    "CHAR",  // +510
    "ButtonHammerStrength",  // +515
    "ButtonIdle",  // +536
    "ButtonStrengthOne",  // +547
    "ButtonStrengthTwo",  // +565
    "ButtonStrengthThree",  // +583
    "ButtonActivated",  // +603
    "ShowPuckAmmo",  // +619
    "HidePuckAmmo",  // +632
    "SetFluidMeter",  // +645
    "ShowFluidMeter",  // +659
    "HideFluidMeter",  // +674
    "ShowPlanktonHud",  // +689
    "HidePlanktonHud",  // +705
    "SetPlanktonStunMode",  // +721
    "SetPlanktonHurtMode",  // +741
    "HideTimer",  // +761
    "HideCounter",  // +771
    "HideBossMeter",  // +783
    "COLLECTIBLE_HAPPY_POINT_COUNTER_reference",  // +797
    "COLLECTIBLE_LIFE_reference",  // +839
    "InitHud",  // +866
    "UID_A_BOOT_Music_timetrial",  // +874
    "ShowHud",  // +901
    "HideHud",  // +909
    "HudVisible",  // +917
    "HudInvisible",  // +928
    "SetHealth",  // +941
    "SetMaxHealth",  // +951
    "SetPuckAmmo",  // +964
    "HidePowerupSpongebuff",  // +976
    "HidePowerupSpin",  // +998
    "HidePowerupHammer",  // +1014
    "HidePowerupPuck",  // +1032
    "HidePowerupInvicibility",  // +1048
    "ShowPowerupSpongebuff",  // +1072
    "ShowPowerupSpin",  // +1094
    "ShowPowerupHammer",  // +1110
    "ShowPowerupPuck",  // +1128
    "ShowPowerupInvicibility",  // +1144
    "SetPowerupTimer",  // +1168
    "SetHappinessPoints",  // +1184
    "H",  // +1203
    "T",  // +1205
    "SetPlanktonAmmo",  // +1207
    "ShowCounter",  // +1223
    "SetCounter",  // +1235
    "ShowTimer",  // +1246
    "SetTimer",  // +1256
    "SetBossMeter",  // +1265
    "ShowBossMeter",  // +1278
    "SetLives",  // +1292
    "TikiScreenPlayer_reference",  // +1301
    "strings",  // +1328
    "ShowTiki",  // +1336
    "HideTiki",  // +1345
};
