// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.


class zDirection {
public:
    int* GetLocation();
    int* GetRotation();

    unsigned char _pad0[0x40];
    int f40;
    unsigned char _pad1[0x8];
    int f4C;
};


int* zDirection::GetLocation() { return &f40; }
int* zDirection::GetRotation() { return &f4C; }

enum eMemMgrTag { eMemMgrTag_ = 0x7FFFFFFF };

namespace Memory {
enum GlobalHeapEnum { GlobalHeapEnum_ = 0x7FFFFFFF };

void* AllocGlobalHeap(unsigned long size, GlobalHeapEnum heap, eMemMgrTag tag,
                      bool clear);
}  // namespace Memory

extern "C" {
void* memset(void* dst, int c, unsigned long n);
}

inline void* operator new(unsigned long, void* p) { return p; }

namespace World {
class EntityHandleBase;
}

class zCheckpoint;


// 0x38, and polymorphic: the vtable pointer the constructor stores
// sits at +0, so nothing precedes it.
class xBase {
public:
    virtual void _v0();

    unsigned char _pad0[0x34 - 0x4];
};

namespace World {

class xOGEntity : public xBase {
public:
    xOGEntity(EntityHandleBase* handle);

    unsigned char _pad0[0x40 - 0x34];
};

}  // namespace World

namespace Sext {

class zCheckpointAsset {
public:
    static ::zCheckpoint* Create(World::EntityHandleBase* handle,
                                 zCheckpointAsset* asset);
};

}  // namespace Sext

class zCheckpoint : public World::xOGEntity {
public:
    zCheckpoint(World::EntityHandleBase* handle) : World::xOGEntity(handle) {}

    virtual void _v0();


    void Init(Sext::zCheckpointAsset* asset);

    unsigned char _pad0[0xA8 - 0x40];
};

zCheckpoint* Sext::zCheckpointAsset::Create(World::EntityHandleBase* handle,
                                            zCheckpointAsset* asset) {
    ::zCheckpoint* entity = new (memset(
        Memory::AllocGlobalHeap(sizeof(::zCheckpoint), (Memory::GlobalHeapEnum)0,
                                (eMemMgrTag)16, false),
        0, sizeof(::zCheckpoint))) ::zCheckpoint(handle);

    entity->Init((Sext::zCheckpointAsset*)asset);

    return entity;
}
