// zCommonPlayerActions.cpp -- hand-owned since the animation tables were added.
//
// The accessor part below was generated by
// tools/gen_accessors.py and is kept as it was written;
// gen_units.py now HOLDS this file rather than regenerating
// it, so a new accessor candidate is merged in by hand. The
// tables were merged by tools/gen_animtables.py.
//
// This file is a fragment of a unity build: the generated
// header puts the whole string pool in front, so the string
// offsets baked into the code come out as retail has them.
#include "SB/GM/Engine/Game/zCommonPlayerActions.pool.h"

class xAnimTable;
class xAnimState;
class xAnimPlay;
class xQuat;
class xVec3;
class xAnimSingle;
class xAnimTransition;
unsigned int xAnimTableNewState(xAnimTable* table, const char* name, unsigned int a, unsigned int b, float c, float* d, float* e, float f, unsigned short* g, void* h, void (*i)(xAnimPlay*, xAnimState*, void*), void (*j)(xAnimPlay*, xAnimState*, void*), void (*k)(xAnimState*, xAnimSingle*, void*), void (*l)(xAnimPlay*, xQuat*, xVec3*, xVec3*, int), unsigned long long m, unsigned int n);
unsigned int xAnimTableNewTransition(xAnimTable* table, const char* from, const char* to, unsigned int (*a)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*b)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int d, unsigned int e, float f, float g, unsigned short h, unsigned short i, float j, unsigned short* k);
void zSBAnimPackageBE(xAnimPlay*, xAnimState*, void*);
void xAnimDefaultBeforeEnter(xAnimPlay*, xAnimState*, void*);
void zHitBE(xAnimPlay*, xAnimState*, void*);

// -- generated accessor part (gen_accessors.py) ------------
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

class xAnimSingle;
class xAnimTransition;
class xEntFrame;
class xScene;


// A base only in the sense that r3 reaches it unchanged:
// the branch is four bytes and names nothing else.
class zPlayer;

// Only the field the 108-byte animation callbacks read, at the
// offset they read it from and the type their compare says --
// cmpwi is signed, cmplwi is not. Nothing else about zPlayer is
// known here.
class xVec3 { public: float x; float y; float z; };

// Only the y two Begins read, at +0x34 of the model the handle
// at the player's +0x34 holds. Nothing else about either is known
// here; both are spelled as the offsets that were measured.
class xOGModel { public: unsigned char _pad0[0x30]; xVec3 pos; };
class xOGModelHandle { public: xOGModel* model; int f4; };

// The two fields ApplyBasicPhysics touches: a flag word it ORs 2
// into, and the vector it adds through. `ori`, so unsigned.
class xEntFrame {
public:
    unsigned char _pad0[0x88];
    // zPlayerHitLaunch::End zeroes all three; LandCheck reads the y.
    xVec3 f88;
    unsigned int flags;
    xVec3 pos;
};

// The one field SetBlend writes. Everything else about the
// transition is reached only as a pointer.
class xAnimTransition {
public:
    unsigned char _pad0[0x28];
    float f28;
};
void v3add(xVec3* d, xVec3* a, xVec3* b);

// Q24Sext10eHitSource -- two components, so Sext qualifies it.
// Only the value zPlayerFallToDeath::Begin passes is known.
namespace Sext { enum eHitSource { eHitSource_ = 0x7FFFFFFF }; }

// Nothing NAMES it -- `addi r3,r4,1244` carries no relocation, so
// it is the player's own storage at +0x4DC, reached as an offset
// rather than declared as a member of unknown size.
class zInteractionManager {
public:
    void StopCurrentInteraction();
};

// The virtuals come FIRST so the vptr lands at 0, which is where
// zPlayerHit::End reads it: `lwz r12,0(r3)` then `lwz r12,524(r12)`,
// and (524 - 8) / 4 is 129. They cost four bytes, and the padding
// in front of f4A0 gives up exactly those four.
class zPlayer {
public:
    virtual void _v0();
    virtual void _v1();
    virtual void _v2();
    virtual void _v3();
    virtual void _v4();
    virtual void _v5();
    virtual void _v6();
    virtual void _v7();
    virtual void _v8();
    virtual void _v9();
    virtual void _v10();
    virtual void _v11();
    virtual void _v12();
    virtual void _v13();
    virtual void _v14();
    virtual void _v15();
    virtual void _v16();
    virtual void _v17();
    virtual void _v18();
    virtual void _v19();
    virtual void _v20();
    virtual void _v21();
    virtual void _v22();
    virtual void _v23();
    virtual void _v24();
    virtual void _v25();
    virtual void _v26();
    virtual void _v27();
    virtual void _v28();
    virtual void _v29();
    virtual void _v30();
    virtual void _v31();
    virtual void _v32();
    virtual void _v33();
    virtual void _v34();
    virtual void _v35();
    virtual void _v36();
    virtual void _v37();
    virtual void _v38();
    virtual void _v39();
    virtual void _v40();
    virtual void _v41();
    virtual void _v42();
    virtual void _v43();
    virtual void _v44();
    virtual void _v45();
    virtual void _v46();
    virtual void _v47();
    virtual void _v48();
    virtual void _v49();
    virtual void _v50();
    virtual void _v51();
    virtual void _v52();
    virtual void _v53();
    virtual void _v54();
    virtual void _v55();
    virtual void _v56();
    virtual void _v57();
    virtual void _v58();
    virtual void _v59();
    virtual void _v60();
    virtual void _v61();
    virtual void _v62();
    virtual void _v63();
    virtual void _v64();
    virtual void _v65();
    virtual void _v66();
    virtual void _v67();
    virtual void _v68();
    virtual void _v69();
    virtual void _v70();
    virtual void _v71();
    virtual void _v72();
    virtual void _v73();
    virtual void _v74();
    virtual void _v75();
    virtual void _v76();
    virtual void _v77();
    virtual void _v78();
    virtual void _v79();
    virtual void _v80();
    virtual void _v81();
    virtual void _v82();
    virtual void _v83();
    virtual void _v84();
    virtual void _v85();
    virtual void _v86();
    virtual void _v87();
    virtual void _v88();
    virtual void _v89();
    virtual void _v90();
    virtual void _v91();
    virtual void _v92();
    virtual void _v93();
    virtual void _v94();
    virtual void _v95();
    virtual void _v96();
    virtual void _v97();
    virtual void _v98();
    virtual void _v99();
    virtual void _v100();
    virtual void _v101();
    virtual void _v102();
    virtual void _v103();
    virtual void _v104();
    virtual void _v105();
    virtual void _v106();
    virtual void _v107();
    virtual void _v108();
    virtual void _v109();
    virtual void _v110();
    virtual void _v111();
    virtual void _v112();
    virtual void _v113();
    virtual void _v114();
    virtual void _v115();
    virtual void _v116();
    virtual void _v117();
    virtual void _v118();
    virtual void _v119();
    virtual void _v120();
    virtual void _v121();
    virtual void _v122();
    virtual void _v123();
    virtual void _v124();
    virtual void _v125();
    virtual void _v126();
    virtual void _v127();
    virtual void _v128();
    virtual void _v129();

    unsigned char _pad0[0x34 - 0x4];
    xOGModelHandle ogModel;
    unsigned char _pad1[0x58 - 0x3C];
    xEntFrame* frame;
    unsigned char _pad2[0x1C4 - 0x5C];
    int zPlayerFlags;
    unsigned char _pad3[0x2F4 - 0x1C8];
    float fallingTime;
    unsigned char _pad4[0x4A0 - 0x2F8];
    int f4A0;
    unsigned char _pad5[0x4A8 - 0x4A4];
    float f4A8;
    unsigned char _pad6[0x554 - 0x4AC];
    int currentHitType;
    unsigned char _pad7[0x5C4 - 0x558];
    float f5C4;
    unsigned char _pad8[0x5EC - 0x5C8];
    // `extsb`, so signed.
    signed char f5EC;
    signed char f5ED;

    static void KillAllPlayers(Sext::eHitSource a0);
};
class zPlayerActionManager;

// The stub zSBPlayerActions.cpp carries, with ONE difference, and
// the difference is what the bytes say: there retail's unity build
// inlined NewState, AddActionTransition and the manager's
// AddTransitionsTo family into the tables, and that file defines
// them `inline` so the fragment inlines them the same way. Here they
// are real calls -- the tables `bl` straight to
// NewState__13zPlayerAction..., AddTransitionsTo__20zPlayerAction
// Manager... and the rest -- so they are declared and left
// undefined, and each relocation reaches retail's own symbol.
//
// Three members, then the virtuals, so the vptr lands at +12 and the
// derived classes' leading padding shrinks by the sixteen bytes the
// base takes.
class zPlayerAction {
public:
    zPlayerActionManager* manager;
    zPlayer* player;
    void (*doneCB)(zPlayerAction*);

    enum SpecialActions { SpecialActions_ = 0x7FFFFFFF };

    virtual void _v0();
    virtual void AddStandardTransitions(xAnimTable* table, const char* name);
    virtual void AddDefaultTransitions(xAnimTable* table, const char* name);
    virtual void AddTransitions(xAnimTable* table, const char* name,
                                unsigned int (*a)(xAnimTransition*, xAnimSingle*, void*),
                                unsigned int (*b)(xAnimTransition*, xAnimSingle*, void*),
                                unsigned short e, float f, unsigned int g,
                                unsigned int h, SpecialActions i);

    // Slot 5 is what every one of the image's 116-byte animation
    // callbacks tests before it forwards: `lwz r12,28(r12)` on a
    // vptr that sits at +12, and (28 - 8) / 4 is 5. Appended, so the
    // three slots the tables call keep the indices they have.
    virtual bool _v4();
    virtual bool _v5();

    void Move(xScene* a0, float a1, xEntFrame* a2);
    static void AddActionTransition(xAnimTable*, const char*, const char*, unsigned int (*)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*)(xAnimTransition*, xAnimSingle*, void*), unsigned short, float, unsigned int, unsigned int);
    // Returns the state it made: four AddStates keep it in a
    // member. The mangled name carries no return type, so this
    // and `void` name the same symbol.
    unsigned int NewState(xAnimTable*, const char*, unsigned int, unsigned int, float, float*, float*, float, unsigned short*, void (*)(xAnimPlay*, xAnimState*, void*), void (*)(xAnimPlay*, xAnimState*, void*), void (*)(xAnimState*, xAnimSingle*, void*), void (*)(xAnimPlay*, xQuat*, xVec3*, xVec3*, int), unsigned int);
    void NewStateMany(xAnimTable*, const char*, int, unsigned int, unsigned int, float, float*, float*, float, unsigned short*, void (*)(xAnimPlay*, xAnimState*, void*), void (*)(xAnimPlay*, xAnimState*, void*), void (*)(xAnimState*, xAnimSingle*, void*), void (*)(xAnimPlay*, xQuat*, xVec3*, xVec3*, int), unsigned int);
    void AddStandardTransitionsFrom(xAnimTable* table, const char* name);
};

class zPlayerActionManager {
public:
    zPlayerAction** actions;
    unsigned char _pad0[0xC - 0x4];
    // `cmplwi`, so unsigned.
    unsigned int f0C;
    unsigned int f10;
    void AddStandardTransitionsTo(unsigned int, xAnimTable*, const char*);
    void AddTransitionsTo(unsigned int, xAnimTable*, const char*, unsigned int (*)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*)(xAnimTransition*, xAnimSingle*, void*), unsigned short, float, unsigned int, unsigned int, zPlayerAction::SpecialActions);
};


// Each class below stands in for one a member points at.
// Nothing NAMES that class -- these five words carry no
// relocation -- so it is named after where it was found,
// and holds virtuals only up to the slot that is called.
class zPlayerWalk_m4 {
public:
    virtual void _v0() const;
    virtual void _v1() const;
    virtual void _v2() const;
    virtual void _v3() const;
    virtual void _v4() const;
    virtual void _v5() const;
    virtual void _v6() const;
    virtual void _v7() const;
    virtual void _v8() const;
    virtual void _v9() const;
    virtual void _v10() const;
    virtual void _v11() const;
    virtual void _v12() const;
    virtual void _v13() const;
    virtual void _v14() const;
    virtual void _v15() const;
    virtual void _v16() const;
    virtual void _v17() const;
    virtual void _v18() const;
    virtual void _v19() const;
    virtual void _v20() const;
    virtual void _v21() const;
    virtual void _v22() const;
    virtual void _v23() const;
    virtual void _v24() const;
    virtual void _v25() const;
    virtual void _v26() const;
    virtual void _v27() const;
    virtual void _v28() const;
    virtual void _v29() const;
    virtual void _v30() const;
    virtual void _v31() const;
    virtual void _v32() const;
    virtual void _v33() const;
    virtual void _v34() const;
    virtual void _v35() const;
    virtual void _v36() const;
    virtual void _v37() const;
    virtual void _v38() const;
    virtual void _v39() const;
    virtual void _v40(float a0) const;
};

// The two dereferences every animation callback makes.
// Nothing in the image NAMES either type, so both are
// spelled as the offsets that were measured. Neither
// struct emits a symbol.
struct AnimCBSlot { unsigned char _pad[0x90]; void* owner; };
struct AnimCBHolder { unsigned char _pad[0x4]; AnimCBSlot* slot; };

// The one word IsLastEntry reads off whatever the custom-anim
// action holds at +0x10. Named after where it was found.
struct zPlayerCustomAnim_m10 {
    unsigned char _pad0[0x4];
    unsigned int f4;
};


class zPlayerIdle : public zPlayerAction {
public:
    void Move(xScene* a0, float a1, xEntFrame* a2);
    static unsigned int anIdleCB(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool IdleCB(xAnimTransition* a0, xAnimSingle* a1);
    static unsigned int anInactiveIdleCB(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool InactiveIdleCB(xAnimTransition* a0, xAnimSingle* a1);

    static unsigned int anInactive2Check(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anInactive3Check(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anInactive4Check(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anInactive5Check(xAnimTransition*, xAnimSingle*, void*);
    void AddInternalTransitions(xAnimTable* table);
    static unsigned int anIdleNormalCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    void AddStates(xAnimTable* table);

    void Begin();

    static const char* GetTransitionString() { return "Idle*"; }
    static void AddTransitionsTo(zPlayerActionManager* a0, xAnimTable* a1, const char* a2);
    void AddActionTransitions(xAnimTable* table);
};



class zPlayerWalk {
public:
    void Update(float a0);

    unsigned char _pad0[0x4];
    int f4;
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
};



class zPlayerSlip : public zPlayerAction {
public:
    void Reset();

    int f10;
    static unsigned int anSlipCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    static const char* GetTransitionString() { return "Slip#"; }
    void AddActionTransitions(xAnimTable* table);
    void AddStates(xAnimTable* table);
    bool SlipCheck(xAnimTransition* a0, xAnimSingle* a1);
};



class zPlayerJump : public zPlayerAction {
public:
    void End();

    unsigned char f10;
    static const char* GetTransitionString() { return "Jump*"; }
    void AddActionTransitions(xAnimTable* table);
    void AddStates(xAnimTable* table);
    static unsigned int anJumpCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool JumpCheck(xAnimTransition* a0, xAnimSingle* a1);

    void Begin();

    float f14;
    float f18;

    void Timestep(float dt);

    float f1C;
};



class zPlayerFall : public zPlayerAction {
public:
    static bool anFallHighCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool FallHighCheck(xAnimTransition* a0, xAnimSingle* a1);

    static const char* GetTransitionString() { return "Fall*"; }
    void AddActionTransitions(xAnimTable* table);
    void AddStates(xAnimTable* table);
    void AddStandardTransitionsFrom(xAnimTable* table, const char* name);

    void Begin();

    float f10;
};



// The four states AddStates keeps: `stw r3,K(this)` after each
// NewState, at +0x10, +0x14, +0x18 and +0x1C, which is where the
// action base ends.
class zPlayerTriggered : public zPlayerAction {
public:
    void Reset();

    unsigned int states[4];
    unsigned char _pad0[0x24 - 0x20];
    int f24;
    void AddActionTransitions(xAnimTable* table);
    static unsigned int anTriggeredAnimCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    void AddStates(xAnimTable* table);
    bool TriggeredAnimCheck(xAnimTransition* a0, xAnimSingle* a1);
    void AddStandardTransitionsFrom(xAnimTable* table, const char* name);
};



class zPlayerLedge : public zPlayerAction {
public:
    static unsigned int anLedgeGrabUpCB(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool LedgeGrabUpCB(xAnimTransition* a0, xAnimSingle* a1);

    void AddInternalTransitions(xAnimTable* table);
    static unsigned int anLedgeGrabCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    static const char* GetTransitionString() { return "LedgeLand01"; }
    void AddActionTransitions(xAnimTable* table);
    void AddStates(xAnimTable* table);

    void End();
};



class zCommonPlayerDash : public zPlayerAction {
public:
    unsigned int GetID();
    static unsigned int anEndCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool EndCheck(xAnimTransition* a0, xAnimSingle* a1);

    void AddInternalTransitions(xAnimTable* table);
    static unsigned int anStartCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    static const char* GetTransitionString() { return "Dash*"; }
    void AddActionTransitions(xAnimTable* table);
    void AddStates(xAnimTable* table);

    void Reset();

    float f10;
};



class zPlayerCustomAnim : public zPlayerAction {
public:
    static unsigned int anLoopToLoopCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool LoopToLoopCheck(xAnimTransition* a0, xAnimSingle* a1);
    static unsigned int anLoopToTran1Check(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool LoopToTran1Check(xAnimTransition* a0, xAnimSingle* a1);
    static unsigned int anLoopToTran2Check(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool LoopToTran2Check(xAnimTransition* a0, xAnimSingle* a1);
    static unsigned int anTranToLoop1Check(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool TranToLoop1Check(xAnimTransition* a0, xAnimSingle* a1);
    static unsigned int anTranToLoop1DefCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool TranToLoop1DefCheck(xAnimTransition* a0, xAnimSingle* a1);
    static unsigned int anTranToLoop2Check(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool TranToLoop2Check(xAnimTransition* a0, xAnimSingle* a1);
    static unsigned int anTranToLoop2DefCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool TranToLoop2DefCheck(xAnimTransition* a0, xAnimSingle* a1);
    static unsigned int anTranToTranCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool TranToTranCheck(xAnimTransition* a0, xAnimSingle* a1);
    static unsigned int anTranToTranDefCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool TranToTranDefCheck(xAnimTransition* a0, xAnimSingle* a1);

    static unsigned int anNewStateCB(xAnimTransition*, xAnimSingle*, void*);
    void AddInternalTransitions(xAnimTable* table);
    static unsigned int anStopCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anStopDefCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddActionTransitions(xAnimTable* table);
    static unsigned int anStartLoopCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anStartTranCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    void AddStates(xAnimTable* table);
    bool StartLoopCheck(xAnimTransition* a0, xAnimSingle* a1);
    bool StartTranCheck(xAnimTransition* a0, xAnimSingle* a1);

    bool IsLastEntry();
    void Reset();

    zPlayerCustomAnim_m10* f10;
    unsigned int f14;
    unsigned char f18;
    unsigned char f19;
    unsigned char f1A;
    unsigned char _pad0[0x1C - 0x1B];
    float f1C;
    float f20;
    unsigned char _pad1[0x34 - 0x24];
    int f34;
    int f38;

    void SetNextState();

    void SetBlend(xAnimTransition* a0);
};


void zPlayerIdle::Move(xScene* a0, float a1, xEntFrame* a2) { zPlayerAction::Move(a0, a1, a2); }
unsigned int zPlayerIdle::anInactiveIdleCB(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerIdle*)((AnimCBHolder*)a1)->slot->owner)->InactiveIdleCB(a0, a1); }
unsigned int zPlayerIdle::anIdleCB(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerIdle*)((AnimCBHolder*)a1)->slot->owner)->IdleCB(a0, a1); }
void zPlayerWalk::Update(float a0) { ((zPlayerWalk_m4*)f4)->_v40(a0); }
void zPlayerSlip::Reset() { f10 = 0; }
void zPlayerJump::End() { f10 = 0; }
bool zPlayerFall::anFallHighCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerFall*)((AnimCBHolder*)a1)->slot->owner)->FallHighCheck(a0, a1); }
void zPlayerTriggered::Reset() { f24 = 4; }
unsigned int zPlayerLedge::anLedgeGrabUpCB(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerLedge*)((AnimCBHolder*)a1)->slot->owner)->LedgeGrabUpCB(a0, a1); }
unsigned int zCommonPlayerDash::GetID() { return 0x0000000Fu; }
unsigned int zCommonPlayerDash::anEndCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zCommonPlayerDash*)((AnimCBHolder*)a1)->slot->owner)->EndCheck(a0, a1); }
unsigned int zPlayerCustomAnim::anTranToTranDefCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerCustomAnim*)((AnimCBHolder*)a1)->slot->owner)->TranToTranDefCheck(a0, a1); }
unsigned int zPlayerCustomAnim::anTranToLoop1DefCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerCustomAnim*)((AnimCBHolder*)a1)->slot->owner)->TranToLoop1DefCheck(a0, a1); }
unsigned int zPlayerCustomAnim::anTranToLoop2DefCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerCustomAnim*)((AnimCBHolder*)a1)->slot->owner)->TranToLoop2DefCheck(a0, a1); }
unsigned int zPlayerCustomAnim::anTranToTranCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerCustomAnim*)((AnimCBHolder*)a1)->slot->owner)->TranToTranCheck(a0, a1); }
unsigned int zPlayerCustomAnim::anTranToLoop1Check(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerCustomAnim*)((AnimCBHolder*)a1)->slot->owner)->TranToLoop1Check(a0, a1); }
unsigned int zPlayerCustomAnim::anTranToLoop2Check(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerCustomAnim*)((AnimCBHolder*)a1)->slot->owner)->TranToLoop2Check(a0, a1); }
unsigned int zPlayerCustomAnim::anLoopToLoopCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerCustomAnim*)((AnimCBHolder*)a1)->slot->owner)->LoopToLoopCheck(a0, a1); }
unsigned int zPlayerCustomAnim::anLoopToTran1Check(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerCustomAnim*)((AnimCBHolder*)a1)->slot->owner)->LoopToTran1Check(a0, a1); }
unsigned int zPlayerCustomAnim::anLoopToTran2Check(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlayerCustomAnim*)((AnimCBHolder*)a1)->slot->owner)->LoopToTran2Check(a0, a1); }

class zCommonPlayerAction : public zPlayerAction {
public:
    static unsigned int anLandCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anRunCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anWalkCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anFallCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool FallCheck(xAnimTransition* a0, xAnimSingle* a1);

    void ApplyBasicPhysics(const xVec3& v);

    bool LandCheck(xAnimTransition* a0, xAnimSingle* a1);
    bool JumpLandCheck(xAnimTransition* a0, xAnimSingle* a1);
};

class zPlayerFallToDeath : public zPlayerAction {
public:
    void AddInternalTransitions(xAnimTable* table);
    static unsigned int anStartCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    void AddStates(xAnimTable* table);
    bool StartCheck(xAnimTransition* a0, xAnimSingle* a1);

    void Begin();

    float f10;
};

class zPlayerLand : public zPlayerAction {
public:
    void AddInternalTransitions(xAnimTable* table);
    static const char* GetTransitionString() { return "Land*"; }
    void AddActionTransitions(xAnimTable* table);
    static void anLandBeforeEnter(xAnimPlay*, xAnimState*, void*);
    void AddStates(xAnimTable* table);
    static unsigned int anLandRunCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool LandRunCheck(xAnimTransition* a0, xAnimSingle* a1);
    static unsigned int anLandWalkCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool LandWalkCheck(xAnimTransition* a0, xAnimSingle* a1);

    void LandBeforeEnter(xAnimPlay* a0, xAnimState* a1);
};

// -- the animation tables, read from the image ------------------

// zPlayerCustomAnim::AddInternalTransitions: 12 call(s)
void zPlayerCustomAnim::AddInternalTransitions(xAnimTable* table) {
    xAnimTableNewTransition(table, "CustomTran01", "CustomTran02", 0, zPlayerCustomAnim::anTranToTranDefCheck, zPlayerCustomAnim::anNewStateCB, 16, 0, 0.0f, 0.0f, 1010, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "CustomTran02", "CustomTran01", 0, zPlayerCustomAnim::anTranToTranDefCheck, zPlayerCustomAnim::anNewStateCB, 16, 0, 0.0f, 0.0f, 1010, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "CustomTran#", "CustomLoop01", 0, zPlayerCustomAnim::anTranToLoop1DefCheck, zPlayerCustomAnim::anNewStateCB, 16, 0, 0.0f, 0.0f, 1010, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "CustomTran#", "CustomLoop02", 0, zPlayerCustomAnim::anTranToLoop2DefCheck, zPlayerCustomAnim::anNewStateCB, 16, 0, 0.0f, 0.0f, 1010, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "CustomTran01", "CustomTran02", 0, zPlayerCustomAnim::anTranToTranCheck, zPlayerCustomAnim::anNewStateCB, 0, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "CustomTran02", "CustomTran01", 0, zPlayerCustomAnim::anTranToTranCheck, zPlayerCustomAnim::anNewStateCB, 0, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "CustomTran#", "CustomLoop01", 0, zPlayerCustomAnim::anTranToLoop1Check, zPlayerCustomAnim::anNewStateCB, 0, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "CustomTran#", "CustomLoop02", 0, zPlayerCustomAnim::anTranToLoop2Check, zPlayerCustomAnim::anNewStateCB, 0, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "CustomLoop01", "CustomLoop02", 0, zPlayerCustomAnim::anLoopToLoopCheck, zPlayerCustomAnim::anNewStateCB, 0, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "CustomLoop02", "CustomLoop01", 0, zPlayerCustomAnim::anLoopToLoopCheck, zPlayerCustomAnim::anNewStateCB, 0, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "CustomLoop#", "CustomTran01", 0, zPlayerCustomAnim::anLoopToTran1Check, zPlayerCustomAnim::anNewStateCB, 0, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "CustomLoop#", "CustomTran02", 0, zPlayerCustomAnim::anLoopToTran2Check, zPlayerCustomAnim::anNewStateCB, 0, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
}

// zPlayerIdle::AddInternalTransitions: 9 call(s)
void zPlayerIdle::AddInternalTransitions(xAnimTable* table) {
    xAnimTableNewTransition(table, "Idle01", "Idle01", 0, 0, 0, 16, 0, 0.0f, 0.0f, 1000, 0, 0.0f, 0);
    xAnimTableNewTransition(table, "Idle01", "Idle02", 0, zPlayerIdle::anInactive2Check, zPlayerIdle::anInactiveIdleCB, 16, 0, 0.0f, 0.0f, 1000, 0, 0.0f, 0);
    xAnimTableNewTransition(table, "Idle01", "Idle03", 0, zPlayerIdle::anInactive3Check, zPlayerIdle::anInactiveIdleCB, 16, 0, 0.0f, 0.0f, 1000, 0, 0.0f, 0);
    xAnimTableNewTransition(table, "Idle01", "Idle04", 0, zPlayerIdle::anInactive4Check, zPlayerIdle::anInactiveIdleCB, 16, 0, 0.0f, 0.0f, 1000, 0, 0.0f, 0);
    xAnimTableNewTransition(table, "Idle01", "Idle05", 0, zPlayerIdle::anInactive5Check, zPlayerIdle::anInactiveIdleCB, 16, 0, 0.0f, 0.0f, 1000, 0, 0.0f, 0);
    xAnimTableNewTransition(table, "Idle02", "Idle01", 0, 0, zPlayerIdle::anIdleCB, 16, 0, 0.0f, 0.0f, 1000, 0, 0.0f, 0);
    xAnimTableNewTransition(table, "Idle03", "Idle01", 0, 0, zPlayerIdle::anIdleCB, 16, 0, 0.0f, 0.0f, 1000, 0, 0.0f, 0);
    xAnimTableNewTransition(table, "Idle04", "Idle01", 0, 0, zPlayerIdle::anIdleCB, 16, 0, 0.0f, 0.0f, 1000, 0, 0.0f, 0);
    xAnimTableNewTransition(table, "Idle05", "Idle01", 0, 0, zPlayerIdle::anIdleCB, 16, 0, 0.0f, 0.0f, 1000, 0, 0.0f, 0);
}

// zPlayerLedge::AddInternalTransitions: 2 call(s)
void zPlayerLedge::AddInternalTransitions(xAnimTable* table) {
    xAnimTableNewTransition(table, "LedgeGrab01", "LedgeUp01", 0, 0, zPlayerLedge::anLedgeGrabUpCB, 16, 0, 0.0f, 0.0f, 1001, 0, 0.1f, 0);
    xAnimTableNewTransition(table, "LedgeUp01", "LedgeLand01", 0, 0, 0, 16, 0, 0.0f, 0.0f, 1001, 0, 0.15f, 0);
}

// zPlayerFallToDeath::AddInternalTransitions: 2 call(s)
void zPlayerFallToDeath::AddInternalTransitions(xAnimTable* table) {
    xAnimTableNewTransition(table, "DeathFallFalling01", "DeathFallImpact01", 0, zCommonPlayerAction::anLandCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "DeathFallImpact01", "DeathFallImpactCycle01", 0, 0, 0, 16, 0, 0.0f, 0.0f, 1000, 0, 0.0f, 0);
}

// zCommonPlayerDash::AddInternalTransitions: 2 call(s)
void zCommonPlayerDash::AddInternalTransitions(xAnimTable* table) {
    xAnimTableNewTransition(table, "DashStart01", "DashCycle01", 0, 0, 0, 16, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
    xAnimTableNewTransition(table, "DashCycle01", "DashEnd01", 0, zCommonPlayerDash::anEndCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
}

// zPlayerLand::AddInternalTransitions: 1 call(s)
void zPlayerLand::AddInternalTransitions(xAnimTable* table) {
    xAnimTableNewTransition(table, "LandHighIdle01", "LandHighOut01", 0, 0, 0, 16, 0, 0.0f, 0.0f, 1000, 0, 0.15f, 0);
}

class zPlayerDoubleJump : public zPlayerAction {
public:
    static const char* GetTransitionString() { return "DoubleJump*"; }
    void AddActionTransitions(xAnimTable* table);
};

// zPlayerDoubleJump::AddActionTransitions: 2 call(s)
void zPlayerDoubleJump::AddActionTransitions(xAnimTable* table) {
    manager->AddStandardTransitionsTo(7, table, zPlayerDoubleJump::GetTransitionString());
    manager->AddStandardTransitionsTo(12, table, zPlayerDoubleJump::GetTransitionString());
}

// zPlayerTriggered::AddActionTransitions: 1 call(s)
void zPlayerTriggered::AddActionTransitions(xAnimTable* table) {
    manager->AddTransitionsTo(0, table, "Triggered#", 0, 0, 2000, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
}

class zPlayerHit : public zPlayerAction {
public:
    static unsigned int anHitCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    void AddActionTransitions(xAnimTable* table);
    void AddStates(xAnimTable* table);
    bool HitCheck(xAnimTransition* a0, xAnimSingle* a1);

    void End();
};

// zPlayerHit::AddTransitionsFrom: 1 call(s)
void zPlayerHit::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "Hit01", zPlayerHit::anHitCheck, c, d, e, f, g, h);
}

class zPlayerRun : public zPlayerAction {
public:
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    void AddStates(xAnimTable* table);

    static unsigned int anSlowRunCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);

    float f10;
};

// zPlayerRun::AddTransitionsFrom: 1 call(s)
void zPlayerRun::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "Run01", zCommonPlayerAction::anRunCheck, c, d, e, f, g, h);
}

// zPlayerIdle::AddTransitionsFrom: 1 call(s)
void zPlayerIdle::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "Idle01", zPlayerIdle::anIdleNormalCheck, c, d, e, f, g, h);
}

// zPlayerSlip::AddTransitionsFrom: 1 call(s)
void zPlayerSlip::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "Slip01", zPlayerSlip::anSlipCheck, c, d, e, f, g, h);
}

// zPlayerWalk::AddTransitionsFrom: 1 call(s)
void zPlayerWalk::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "Walk01", zCommonPlayerAction::anWalkCheck, c, d, e, f, g, h);
}

// zPlayerLedge::AddTransitionsFrom: 1 call(s)
void zPlayerLedge::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "LedgeGrab01", zPlayerLedge::anLedgeGrabCheck, c, d, e, f, g, h);
}

class zPlayerHitLaunch : public zPlayerAction {
public:
    static unsigned int anLaunchCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    static const char* GetTransitionString() { return "Launch*"; }
    void AddActionTransitions(xAnimTable* table);
    void AddStates(xAnimTable* table);
    bool LaunchCheck(xAnimTransition* a0, xAnimSingle* a1);

    void End();
};

// zPlayerHitLaunch::AddTransitionsFrom: 1 call(s)
void zPlayerHitLaunch::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "Launch01", zPlayerHitLaunch::anLaunchCheck, c, d, e, f, g, h);
}

// zCommonPlayerDash::AddTransitionsFrom: 1 call(s)
void zCommonPlayerDash::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "DashStart01", zCommonPlayerDash::anStartCheck, c, d, e, f, g, h);
}

// zPlayerFallToDeath::AddTransitionsFrom: 1 call(s)
void zPlayerFallToDeath::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "DeathFallFalling01", zPlayerFallToDeath::anStartCheck, c, d, e, f, g, h);
}

class zPlayerWalkStart : public zPlayerAction {
public:
    static unsigned int anStartWalkCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    void AddStates(xAnimTable* table);
    bool StartWalkCheck(xAnimTransition* a0, xAnimSingle* a1);
    static const char* GetTransitionString() { return "StartWalk#"; }
    void AddActionTransitions(xAnimTable* table);
};

// zPlayerWalkStart::AddTransitionsFrom: 1 call(s)
void zPlayerWalkStart::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "StartWalk01", zPlayerWalkStart::anStartWalkCheck, c, d, e, 0.05f, g, h);
}

// zPlayerJump::AddActionTransitions: 4 call(s)
void zPlayerJump::AddActionTransitions(xAnimTable* table) {
    manager->AddStandardTransitionsTo(7, table, zPlayerJump::GetTransitionString());
    manager->AddStandardTransitionsTo(12, table, zPlayerJump::GetTransitionString());
    manager->AddStandardTransitionsTo(13, table, zPlayerJump::GetTransitionString());
    manager->AddStandardTransitionsTo(15, table, zPlayerJump::GetTransitionString());
}

// zPlayerCustomAnim::AddActionTransitions: 2 call(s)
void zPlayerCustomAnim::AddActionTransitions(xAnimTable* table) {
    zPlayerAction::AddActionTransition(table, "CustomTran#", "Idle01", zPlayerCustomAnim::anStopDefCheck, 0, 0, 1000, 0.0f, 16, 0);
    zPlayerAction::AddActionTransition(table, "Custom*", "Idle01", zPlayerCustomAnim::anStopCheck, 0, 0, 1000, 0.0f, 0, 0);
}

// zPlayerSlip::AddActionTransitions: 6 call(s)
void zPlayerSlip::AddActionTransitions(xAnimTable* table) {
    manager->AddStandardTransitionsTo(0, table, zPlayerSlip::GetTransitionString());
    manager->AddStandardTransitionsTo(2, table, zPlayerSlip::GetTransitionString());
    manager->AddStandardTransitionsTo(3, table, zPlayerSlip::GetTransitionString());
    manager->AddStandardTransitionsTo(6, table, zPlayerSlip::GetTransitionString());
    manager->AddStandardTransitionsTo(8, table, zPlayerSlip::GetTransitionString());
    manager->AddStandardTransitionsTo(12, table, zPlayerSlip::GetTransitionString());
}

class zPlayerDefeated : public zPlayerAction {
public:
    static unsigned int anDeathCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anDrownCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i);
    void AddStates(xAnimTable* table);
    bool DeathCheck(xAnimTransition* a0, xAnimSingle* a1);
    bool DrownCheck(xAnimTransition* a0, xAnimSingle* a1);
};

// zPlayerDefeated::AddTransitionsFrom: 2 call(s)
void zPlayerDefeated::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "DefeatedBeginStand01", zPlayerDefeated::anDeathCheck, c, d, e, f, g, h);
    zPlayerAction::AddActionTransition(table, name, "DefeatedBeginLiquid01", zPlayerDefeated::anDrownCheck, c, d, e, f, g, h);
}

// zPlayerCustomAnim::AddTransitionsFrom: 2 call(s)
void zPlayerCustomAnim::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "CustomTran01", zPlayerCustomAnim::anStartTranCheck, c, d, e, f, g, h);
    zPlayerAction::AddActionTransition(table, name, "CustomLoop01", zPlayerCustomAnim::anStartLoopCheck, c, d, e, f, g, h);
}

// zPlayerHitLaunch::AddActionTransitions: 3 call(s)
void zPlayerHitLaunch::AddActionTransitions(xAnimTable* table) {
    zPlayerActionManager* mgr = manager;

    mgr->AddTransitionsTo(0, table, zPlayerHitLaunch::GetTransitionString(), 0, 0, 1000, 0.0f, 16, 0, (zPlayerAction::SpecialActions)0);
    mgr->AddTransitionsTo(2, table, zPlayerHitLaunch::GetTransitionString(), 0, 0, 1000, 0.0f, 16, 0, (zPlayerAction::SpecialActions)0);
    mgr->AddTransitionsTo(3, table, zPlayerHitLaunch::GetTransitionString(), 0, 0, 1000, 0.0f, 16, 0, (zPlayerAction::SpecialActions)0);
}

// zPlayerHit::AddActionTransitions: 3 call(s)
void zPlayerHit::AddActionTransitions(xAnimTable* table) {
    zPlayerActionManager* mgr = manager;
    const char* s = "Hit*";

    mgr->AddTransitionsTo(0, table, s, 0, 0, 1000, 0.0f, 16, 0, (zPlayerAction::SpecialActions)0);
    mgr->AddTransitionsTo(2, table, s, 0, 0, 1000, 0.0f, 16, 0, (zPlayerAction::SpecialActions)0);
    mgr->AddTransitionsTo(3, table, s, 0, 0, 1000, 0.0f, 16, 0, (zPlayerAction::SpecialActions)0);
}

// zPlayerFall::AddActionTransitions: 5 call(s)
void zPlayerFall::AddActionTransitions(xAnimTable* table) {
    manager->AddStandardTransitionsTo(12, table, zPlayerFall::GetTransitionString());
    manager->AddStandardTransitionsTo(15, table, zPlayerFall::GetTransitionString());
    manager->AddStandardTransitionsTo(13, table, zPlayerFall::GetTransitionString());
    manager->AddTransitionsTo(7, table, "FallIdle01 FallMoving01", 0, 0, 1000, 0.15f, 0, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(7, table, "FallHigh*", 0, 0, 1000, 0.15f, 0, 0, (zPlayerAction::SpecialActions)1);
}

// zCommonPlayerDash::AddActionTransitions: 4 call(s)
void zCommonPlayerDash::AddActionTransitions(xAnimTable* table) {
    manager->AddStandardTransitionsTo(8, table, zCommonPlayerDash::GetTransitionString());
    manager->AddTransitionsTo(0, table, "DashEnd01", 0, 0, 1000, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(2, table, "DashEnd01", 0, 0, 1000, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(3, table, "DashEnd01", 0, 0, 1000, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
}

class zPlayerSkidStop : public zPlayerAction {
public:
    static const char* GetTransitionString() { return "SkidStop#"; }
    void AddActionTransitions(xAnimTable* table);
    void AddStates(xAnimTable* table);
};

// zPlayerSkidStop::AddActionTransitions: 8 call(s)
void zPlayerSkidStop::AddActionTransitions(xAnimTable* table) {
    manager->AddTransitionsTo(0, table, zPlayerSkidStop::GetTransitionString(), 0, 0, 1000, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddStandardTransitionsTo(2, table, zPlayerSkidStop::GetTransitionString());
    manager->AddStandardTransitionsTo(3, table, zPlayerSkidStop::GetTransitionString());
    manager->AddStandardTransitionsTo(4, table, zPlayerSkidStop::GetTransitionString());
    manager->AddStandardTransitionsTo(8, table, zPlayerSkidStop::GetTransitionString());
    manager->AddStandardTransitionsTo(12, table, zPlayerSkidStop::GetTransitionString());
    manager->AddStandardTransitionsTo(13, table, zPlayerSkidStop::GetTransitionString());
    manager->AddStandardTransitionsTo(15, table, zPlayerSkidStop::GetTransitionString());
}

// zPlayerTriggered::AddTransitionsFrom: 4 call(s)
void zPlayerTriggered::AddTransitionsFrom(xAnimTable* table, const char* name, unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*d)(xAnimTransition*, xAnimSingle*, void*), unsigned short e, float f, unsigned int g, unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "Triggered01", zPlayerTriggered::anTriggeredAnimCheck, c, d, e, f, g, h);
    zPlayerAction::AddActionTransition(table, name, "Triggered02", zPlayerTriggered::anTriggeredAnimCheck, c, d, e, f, g, h);
    zPlayerAction::AddActionTransition(table, name, "Triggered03", zPlayerTriggered::anTriggeredAnimCheck, c, d, e, f, g, h);
    zPlayerAction::AddActionTransition(table, name, "Triggered04", zPlayerTriggered::anTriggeredAnimCheck, c, d, e, f, g, h);
}

class zPlayerCheat : public zPlayerAction {
public:
    static unsigned int anCheatBeginCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anCheatEndCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddActionTransitions(xAnimTable* table);
    void AddStates(xAnimTable* table);
};

// zPlayerCheat::AddActionTransitions: 4 call(s)
void zPlayerCheat::AddActionTransitions(xAnimTable* table) {
    zPlayerAction::AddActionTransition(table, "*", "Cheat01", zPlayerCheat::anCheatBeginCheck, 0, 0, 64000, 0.0f, 0, 0);
    manager->AddTransitionsTo(0, table, "Cheat01", zPlayerCheat::anCheatEndCheck, 0, 1000, 0.15f, 0, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(2, table, "Cheat01", zPlayerCheat::anCheatEndCheck, 0, 1000, 0.15f, 0, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(3, table, "Cheat01", zPlayerCheat::anCheatEndCheck, 0, 1000, 0.15f, 0, 0, (zPlayerAction::SpecialActions)0);
}

// zPlayerLedge::AddActionTransitions: 6 call(s)
void zPlayerLedge::AddActionTransitions(xAnimTable* table) {
    manager->AddStandardTransitionsTo(12, table, "Ledge*");
    manager->AddStandardTransitionsTo(2, table, zPlayerLedge::GetTransitionString());
    manager->AddStandardTransitionsTo(3, table, zPlayerLedge::GetTransitionString());
    manager->AddTransitionsTo(0, table, zPlayerLedge::GetTransitionString(), 0, 0, 1000, 0.1f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(2, table, zPlayerLedge::GetTransitionString(), 0, 0, 1000, 0.1f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(3, table, zPlayerLedge::GetTransitionString(), 0, 0, 1000, 0.1f, 16, 0, (zPlayerAction::SpecialActions)0);
}

// zPlayerLand::AddActionTransitions: 10 call(s)
void zPlayerLand::AddActionTransitions(xAnimTable* table) {
    manager->AddTransitionsTo(0, table, "LandIdle01 LandMoving01 LandHighOut01", 0, 0, 1000, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(2, table, "LandIdle01 LandMoving01 LandHighOut01", 0, 0, 1000, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(3, table, "LandIdle01 LandMoving01 LandHighOut01", 0, 0, 1000, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(3, table, "LandHighIdle01", 0, 0, 1001, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(2, table, "LandHighIdle01", 0, 0, 1001, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(3, table, "LandHighOut01", 0, 0, 1001, 0.15f, 0, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(2, table, "LandHighOut01", 0, 0, 1001, 0.15f, 0, 0, (zPlayerAction::SpecialActions)0);
    manager->AddStandardTransitionsTo(12, table, zPlayerLand::GetTransitionString());
    manager->AddStandardTransitionsTo(13, table, zPlayerLand::GetTransitionString());
    manager->AddStandardTransitionsTo(15, table, zPlayerLand::GetTransitionString());
}

// zPlayerHitLaunch::AddStates: 1 call(s)
void zPlayerHitLaunch::AddStates(xAnimTable* table) {
    NewState(table, "Launch01", 32, 0x2000020, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
}

// zPlayerHit::AddStates: 1 call(s)
void zPlayerHit::AddStates(xAnimTable* table) {
    NewState(table, "Hit01", 32, 32, 1.0f, 0, 0, 0.0f, 0, zHitBE, 0, 0, 0, 0);
}

// zPlayerIdle::AddStates: 1 call(s)
void zPlayerIdle::AddStates(xAnimTable* table) {
    NewStateMany(table, "Idle01", 5, 64, 0x2000400, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
}

// zPlayerSlip::AddStates: 1 call(s)
void zPlayerSlip::AddStates(xAnimTable* table) {
    NewState(table, "Slip01", 16, 1042, 1.0f, 0, 0, 0.0f, 0, xAnimDefaultBeforeEnter, 0, 0, 0, 0);
}

// zPlayerCheat::AddStates: 1 call(s)
void zPlayerCheat::AddStates(xAnimTable* table) {
    NewState(table, "Cheat01", 16, 2, 1.0f, 0, 0, 0.0f, 0, xAnimDefaultBeforeEnter, 0, 0, 0, 0);
}

// zPlayerWalkStart::AddStates: 1 call(s)
void zPlayerWalkStart::AddStates(xAnimTable* table) {
    NewState(table, "StartWalk01", 32, 1026, 1.0f, 0, 0, 0.0f, 0, xAnimDefaultBeforeEnter, 0, 0, 0, 0);
}

// zPlayerSkidStop::AddStates: 1 call(s)
void zPlayerSkidStop::AddStates(xAnimTable* table) {
    NewStateMany(table, "SkidStop01", 2, 32, 1033, 1.0f, 0, 0, 0.0f, 0, xAnimDefaultBeforeEnter, 0, 0, 0, 0);
}

// zPlayerJump::AddStates: 3 call(s)
void zPlayerJump::AddStates(xAnimTable* table) {
    NewState(table, "JumpStart01", 32, 1044, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "JumpStart02", 32, 1044, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "JumpStart03", 32, 1044, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
}

// zPlayerLedge::AddStates: 3 call(s)
void zPlayerLedge::AddStates(xAnimTable* table) {
    NewState(table, "LedgeGrab01", 32, 128, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "LedgeUp01", 32, 16544, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "LedgeLand01", 32, 32, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
}

// zPlayerFallToDeath::AddStates: 3 call(s)
void zPlayerFallToDeath::AddStates(xAnimTable* table) {
    NewState(table, "DeathFallFalling01", 16, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "DeathFallImpact01", 32, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "DeathFallImpactCycle01", 0, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
}

// zCommonPlayerDash::AddStates: 3 call(s)
void zCommonPlayerDash::AddStates(xAnimTable* table) {
    NewState(table, "DashStart01", 32, 1029, 1.0f, 0, 0, 0.0f, 0, xAnimDefaultBeforeEnter, 0, 0, 0, 0);
    NewState(table, "DashCycle01", 16, 1045, 1.0f, 0, 0, 0.0f, 0, xAnimDefaultBeforeEnter, 0, 0, 0, 0);
    NewState(table, "DashEnd01", 32, 1029, 1.0f, 0, 0, 0.0f, 0, xAnimDefaultBeforeEnter, 0, 0, 0, 0);
}

// zPlayerFall::AddStates: 4 call(s)
void zPlayerFall::AddStates(xAnimTable* table) {
    NewState(table, "FallIdle01", 16, 1040, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "FallMoving01", 16, 1044, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "FallHighIdle01", 16, 1028, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "FallHighMoving01", 16, 1028, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
}

// zPlayerCustomAnim::AddStates: 4 call(s)
void zPlayerCustomAnim::AddStates(xAnimTable* table) {
    NewState(table, "CustomTran01", 32, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "CustomTran02", 32, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "CustomLoop01", 16, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "CustomLoop02", 16, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
}

// zPlayerRun::AddStates: 4 call(s)
void zPlayerRun::AddStates(xAnimTable* table) {
    NewState(table, "Run01", 16, 1043, 1.0f, 0, 0, 0.0f, 0, xAnimDefaultBeforeEnter, 0, 0, 0, 0);
    NewState(table, "RunFastStart01", 32, 1043, 1.0f, 0, 0, 0.0f, 0, xAnimDefaultBeforeEnter, 0, 0, 0, 0);
    NewState(table, "RunFastCycle01", 16, 1045, 1.0f, 0, 0, 0.0f, 0, xAnimDefaultBeforeEnter, 0, 0, 0, 0);
    NewState(table, "RunFastEnd01", 32, 1045, 1.0f, 0, 0, 0.0f, 0, xAnimDefaultBeforeEnter, 0, 0, 0, 0);
}

// zPlayerLand::AddStates: 4 call(s)
void zPlayerLand::AddStates(xAnimTable* table) {
    NewState(table, "LandIdle01", 32, 0x2000000, 1.0f, 0, 0, 0.0f, 0, zPlayerLand::anLandBeforeEnter, 0, 0, 0, 0);
    NewState(table, "LandMoving01", 32, 3, 1.0f, 0, 0, 0.0f, 0, zPlayerLand::anLandBeforeEnter, 0, 0, 0, 0);
    NewState(table, "LandHighIdle01", 32, 0x2000000, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "LandHighOut01", 32, 0x2000000, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
}

// zPlayerTriggered::AddStates: 4 call(s)
void zPlayerTriggered::AddStates(xAnimTable* table) {
    states[0] = NewState(table, "Triggered01", 32, 32, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    states[1] = NewState(table, "Triggered02", 32, 32, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    states[2] = NewState(table, "Triggered03", 32, 32, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    states[3] = NewState(table, "Triggered04", 32, 32, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
}

// zPlayerDefeated::AddStates: 5 call(s)
void zPlayerDefeated::AddStates(xAnimTable* table) {
    NewState(table, "DefeatedBeginStand01", 0, 32, 1.0f, 0, 0, 0.0f, 0, zSBAnimPackageBE, 0, 0, 0, 0);
    NewState(table, "DefeatedBeginMove01", 0, 32, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "DefeatedBeginLandBack01", 0, 32, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "DefeatedBeginLandFront01", 0, 32, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "DefeatedBeginLiquid01", 0, 32, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
}

unsigned int zPlayerDefeated::anDeathCheck(xAnimTransition* a0, xAnimSingle* a1,
                                           void* a2) {
    unsigned int result = 0;

    if (((zPlayerDefeated*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerDefeated*)((AnimCBHolder*)a0)->slot->owner)->DeathCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerDefeated::anDrownCheck(xAnimTransition* a0, xAnimSingle* a1,
                                           void* a2) {
    unsigned int result = 0;

    if (((zPlayerDefeated*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerDefeated*)((AnimCBHolder*)a0)->slot->owner)->DrownCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zCommonPlayerAction::anFallCheck(xAnimTransition* a0, xAnimSingle* a1,
                                              void* a2) {
    unsigned int result = 0;

    if (((zCommonPlayerAction*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zCommonPlayerAction*)((AnimCBHolder*)a0)->slot->owner)->FallCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerHit::anHitCheck(xAnimTransition* a0, xAnimSingle* a1,
                                    void* a2) {
    unsigned int result = 0;

    if (((zPlayerHit*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerHit*)((AnimCBHolder*)a0)->slot->owner)->HitCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerJump::anJumpCheck(xAnimTransition* a0, xAnimSingle* a1,
                                      void* a2) {
    unsigned int result = 0;

    if (((zPlayerJump*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerJump*)((AnimCBHolder*)a0)->slot->owner)->JumpCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerLand::anLandRunCheck(xAnimTransition* a0, xAnimSingle* a1,
                                         void* a2) {
    unsigned int result = 0;

    if (((zPlayerLand*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerLand*)((AnimCBHolder*)a0)->slot->owner)->LandRunCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerLand::anLandWalkCheck(xAnimTransition* a0, xAnimSingle* a1,
                                          void* a2) {
    unsigned int result = 0;

    if (((zPlayerLand*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerLand*)((AnimCBHolder*)a0)->slot->owner)->LandWalkCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerHitLaunch::anLaunchCheck(xAnimTransition* a0, xAnimSingle* a1,
                                             void* a2) {
    unsigned int result = 0;

    if (((zPlayerHitLaunch*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerHitLaunch*)((AnimCBHolder*)a0)->slot->owner)->LaunchCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerSlip::anSlipCheck(xAnimTransition* a0, xAnimSingle* a1,
                                      void* a2) {
    unsigned int result = 0;

    if (((zPlayerSlip*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerSlip*)((AnimCBHolder*)a0)->slot->owner)->SlipCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerFallToDeath::anStartCheck(xAnimTransition* a0, xAnimSingle* a1,
                                              void* a2) {
    unsigned int result = 0;

    if (((zPlayerFallToDeath*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerFallToDeath*)((AnimCBHolder*)a0)->slot->owner)->StartCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerCustomAnim::anStartLoopCheck(xAnimTransition* a0, xAnimSingle* a1,
                                                 void* a2) {
    unsigned int result = 0;

    if (((zPlayerCustomAnim*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerCustomAnim*)((AnimCBHolder*)a0)->slot->owner)->StartLoopCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerCustomAnim::anStartTranCheck(xAnimTransition* a0, xAnimSingle* a1,
                                                 void* a2) {
    unsigned int result = 0;

    if (((zPlayerCustomAnim*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerCustomAnim*)((AnimCBHolder*)a0)->slot->owner)->StartTranCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerWalkStart::anStartWalkCheck(xAnimTransition* a0, xAnimSingle* a1,
                                                void* a2) {
    unsigned int result = 0;

    if (((zPlayerWalkStart*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerWalkStart*)((AnimCBHolder*)a0)->slot->owner)->StartWalkCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerTriggered::anTriggeredAnimCheck(xAnimTransition* a0, xAnimSingle* a1,
                                                    void* a2) {
    unsigned int result = 0;

    if (((zPlayerTriggered*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerTriggered*)((AnimCBHolder*)a0)->slot->owner)->TriggeredAnimCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

// zPlayerFall::AddStandardTransitionsFrom: 1 call(s)
void zPlayerFall::AddStandardTransitionsFrom(xAnimTable* table, const char* name) {
    AddTransitions(table, name, 0, 0, 1000, 0.1f, 0, 0, (zPlayerAction::SpecialActions)0);
}

// zPlayerTriggered::AddStandardTransitionsFrom: 1 call(s)
void zPlayerTriggered::AddStandardTransitionsFrom(xAnimTable* table, const char* name) {
    AddTransitions(table, name, 0, 0, 200, 0.15f, 0, 0, (zPlayerAction::SpecialActions)0);
}

// zPlayerWalkStart::AddActionTransitions: 10 call(s)
void zPlayerWalkStart::AddActionTransitions(xAnimTable* table) {
    manager->AddStandardTransitionsTo(1, table, zPlayerWalkStart::GetTransitionString());
    manager->AddTransitionsTo(0, table, zPlayerWalkStart::GetTransitionString(), 0, 0, 1000, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(2, table, zPlayerWalkStart::GetTransitionString(), 0, 0, 1000, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddTransitionsTo(3, table, zPlayerWalkStart::GetTransitionString(), 0, 0, 1000, 0.15f, 16, 0, (zPlayerAction::SpecialActions)0);
    manager->AddStandardTransitionsTo(4, table, zPlayerWalkStart::GetTransitionString());
    manager->AddStandardTransitionsTo(6, table, zPlayerWalkStart::GetTransitionString());
    manager->AddStandardTransitionsTo(8, table, zPlayerWalkStart::GetTransitionString());
    manager->AddStandardTransitionsTo(12, table, zPlayerWalkStart::GetTransitionString());
    manager->AddStandardTransitionsTo(15, table, zPlayerWalkStart::GetTransitionString());
    AddStandardTransitions(table, zPlayerWalkStart::GetTransitionString());
}

unsigned int zPlayerLedge::anLedgeGrabCheck(xAnimTransition* a0, xAnimSingle* a1,
                                            void* a2) {
    unsigned int result = 0;

    if (((zPlayerLedge*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerLedge*)((AnimCBHolder*)a0)->slot->owner)->player->f4A0 == 2) {
            result = 1;
        }
    }

    return result;
}

// The interaction action is declared here rather than above: it is
// the only thing in the unit that names zInteractionManager.
class zCommonPlayerInterAction : public zPlayerAction {
public:
    void End();

    int f10;
};

void zPlayerIdle::Begin() {
    IdleCB(0, 0);
}

void zCommonPlayerDash::Reset() {
    f10 = 1.0f;
}

void zCommonPlayerInterAction::End() {
    f10 = 0;

    ((zInteractionManager*)((char*)player + 0x4DC))->StopCurrentInteraction();
}

// The holder is a1 ITSELF here, not a1->slot: `lwz r3,144(r4)` is
// the owner at +0x90 read straight off the state.
void zPlayerLand::anLandBeforeEnter(xAnimPlay* a0, xAnimState* a1,
                                    void* a2) {
    ((zPlayerLand*)((AnimCBSlot*)a1)->owner)->LandBeforeEnter(a0, a1);
}

bool zPlayerCustomAnim::IsLastEntry() {
    return f14 >= f10->f4;
}

void zPlayerHit::End() {
    player->currentHitType = -1;

    player->_v129();
}

void zPlayerFall::Begin() {
    if (manager->f0C == 15) {
        return;
    }

    f10 = player->ogModel.model->pos.y;
}

bool zCommonPlayerDash::EndCheck(xAnimTransition* a0,
                                 xAnimSingle* a1) {
    bool result = false;

    if (f10 <= 0.0f) {
        result = true;
    }

    return result;
}

bool zPlayerHitLaunch::LaunchCheck(xAnimTransition* a0,
                                   xAnimSingle* a1) {
    return player->currentHitType == 2 || player->currentHitType == 1;
}

bool zPlayerLedge::LedgeGrabUpCB(xAnimTransition* a0,
                                 xAnimSingle* a1) {
    player->f4A0 = 0;
    player->f4A8 = 1.0f;

    return false;
}

unsigned int zPlayerRun::anSlowRunCheck(xAnimTransition* a0,
                                        xAnimSingle* a1, void* a2) {
    return ((zPlayerRun*)((AnimCBHolder*)a1)->slot->owner)->f10 < 5.0f;
}

void zPlayerJump::Begin() {
    f10 = 1;
    f14 = 0.0f;
    f18 = player->ogModel.model->pos.y;
}

void zPlayerCustomAnim::Reset() {
    f10 = 0;
    f18 = 0;
    f19 = 0;
    f34 = 0;
    f38 = 0;
    f1C = 0.0f;
}

void zPlayerIdle::AddActionTransitions(xAnimTable* table) {
    zPlayerIdle::AddTransitionsTo(manager, table,
                                  zPlayerIdle::GetTransitionString());
}

void zCommonPlayerAction::ApplyBasicPhysics(const xVec3& v) {
    player->frame->flags |= 2;

    v3add(&player->frame->pos, &player->frame->pos, (xVec3*)&v);
}

bool zPlayerWalkStart::StartWalkCheck(xAnimTransition* a0,
                                      xAnimSingle* a1) {
    bool result = false;

    if (!player->f5ED && player->f5EC >= 1) {
        result = true;
    }

    return result;
}

bool zPlayerSlip::SlipCheck(xAnimTransition* a0, xAnimSingle* a1) {
    bool result = false;

    if (player->f5EC > 0 && f10 == 1) {
        result = true;
    }

    return result;
}

void zPlayerJump::Timestep(float dt) {
    if (f1C > 0.0f) {
        f1C -= dt;

        if (f1C < 0.0f) {
            f1C = 0.0f;
        }
    }
}

bool zPlayerFall::FallHighCheck(xAnimTransition* a0, xAnimSingle* a1) {
    return f10 - player->ogModel.model->pos.y > 12.0f;
}

unsigned int zPlayerCustomAnim::anNewStateCB(xAnimTransition* a0,
                                             xAnimSingle* a1,
                                             void* a2) {
    ((zPlayerCustomAnim*)((AnimCBHolder*)a1)->slot->owner)->SetNextState();

    return 0;
}

bool zCommonPlayerAction::FallCheck(xAnimTransition* a0,
                                    xAnimSingle* a1) {
    bool result = false;

    if (!(player->zPlayerFlags & 2) && player->fallingTime > 0.15f) {
        result = true;
    }

    return result;
}

bool zPlayerIdle::IdleCB(xAnimTransition* a0, xAnimSingle* a1) {
    if (player->currentHitType == 1 || player->currentHitType == 2) {
        player->currentHitType = -1;
    }

    player->f5C4 = 0.0f;

    return false;
}

bool zPlayerTriggered::TriggeredAnimCheck(xAnimTransition* a0,
                                          xAnimSingle* a1) {
    bool result = false;

    if (f24 < 4 &&
        (unsigned int)((AnimCBHolder*)a0)->slot == states[f24]) {
        result = true;
    }

    return result;
}

unsigned int zCommonPlayerDash::anStartCheck(xAnimTransition* a0,
                                             xAnimSingle* a1,
                                             void* a2) {
    ((zCommonPlayerDash*)((AnimCBHolder*)a0)->slot->owner)->_v5();

    return 0;
}

void zPlayerFallToDeath::Begin() {
    zPlayer::KillAllPlayers((Sext::eHitSource)1);

    f10 = 0.0f;
}

void zPlayerLedge::End() {
    player->f5C4 = 0.0f;
    player->f4A0 = 0;
    player->zPlayerFlags |= 8;
    player->zPlayerFlags &= ~0x10;
}

// Three conjuncts and no register spent on them.
bool zCommonPlayerAction::LandCheck(xAnimTransition* a0,
                                    xAnimSingle* a1) {
    if ((player->zPlayerFlags & 2) && !(player->zPlayerFlags & 0x2000) &&
        player->frame->f88.y <= 0.01f) {
        return true;
    }

    return false;
}

bool zPlayerCustomAnim::StartTranCheck(xAnimTransition* a0,
                                       xAnimSingle* a1) {
    if (f18 && !f1A) {
        SetBlend(a0);

        return true;
    }

    return false;
}

bool zPlayerCustomAnim::StartLoopCheck(xAnimTransition* a0,
                                       xAnimSingle* a1) {
    if (f18 && f1A) {
        SetBlend(a0);

        return true;
    }

    return false;
}

void zPlayerHitLaunch::End() {
    if (manager->f10 != 6) {
        xEntFrame* frame = player->frame;

        frame->f88.x = 0.0f;
        frame->f88.y = 0.0f;
        frame->f88.z = 0.0f;
    }

    player->currentHitType = -1;

    player->_v129();
}

bool zPlayerLand::LandWalkCheck(xAnimTransition* a0, xAnimSingle* a1) {
    bool result = false;

    if (((zCommonPlayerAction*)this)->JumpLandCheck(a0, a1) &&
        player->f5EC < 2) {
        result = true;
    }

    return result;
}

bool zPlayerLand::LandRunCheck(xAnimTransition* a0, xAnimSingle* a1) {
    bool result = false;

    if (((zCommonPlayerAction*)this)->JumpLandCheck(a0, a1) &&
        player->f5EC >= 2) {
        result = true;
    }

    return result;
}

// The same predicate as LandCheck, with the first two conjuncts
// ASSIGNED to a bool -- which is why this one materialises a flag
// and LandCheck does not.
bool zCommonPlayerAction::JumpLandCheck(xAnimTransition* a0,
                                        xAnimSingle* a1) {
    bool result = false;
    bool onGround = (player->zPlayerFlags & 2) &&
                    !(player->zPlayerFlags & 0x2000);

    if (onGround && player->frame->f88.y <= 0.01f) {
        result = true;
    }

    return result;
}

void zPlayerAction::AddStandardTransitionsFrom(xAnimTable* table,
                                               const char* name) {
    AddTransitions(table, name, 0, 0, 1000, 0.15f, 0, 0,
                   (zPlayerAction::SpecialActions)0);
}

void zPlayerCustomAnim::SetBlend(xAnimTransition* a0) {
    if (f20 < 0.0f) {
        a0->f28 = 6.6666665f;
    } else if (f20 == 0.0f) {
        a0->f28 = 0.0f;
    } else {
        a0->f28 = 1.0f / f20;
    }
}
