// GENERATED by tools/transplant.py from a matched twin.
// Do not hand-edit: re-emit, or take the file over and remove this
// banner -- written_vs_generated.py splits on it.
//
// zFog, transplanted from Sext::zEventSpyAsset::Create, which
// is matched. 27 of 34 instructions are byte-identical and two more
// reach the same symbol from a different address; the holes are the
// allocation size, the base constructor, the vtable and the VIRTUAL
// SLOT the init is called through -- (K - 8) / 4 of the
// `lwz r12,K(r12)`, because a CodeWarrior vtable pointer points
// eight bytes past its start. All four were read from the image.
//
// A call through a vtable names no symbol, so the init's parameter
// type is the one thing here the image cannot say; it is spelled as
// the asset, which is what it is called with.
//
// The base carries nothing but its constructor and all the padding
// rides on the derived class: the vptr sits at +0 either way, and
// how sizeof splits between the two changes no code. None of the
// virtuals is defined, which is what leaves __vt__zFog
// referenced instead of emitted.

enum eMemMgrTag { eMemMgrTag_ = 0x7FFFFFFF };

namespace Memory {
enum GlobalHeapEnum { GlobalHeapEnum_ = 0x7FFFFFFF };

void* AllocGlobalHeap(unsigned long size, GlobalHeapEnum heap, eMemMgrTag tag,
                      bool clear);
}  // namespace Memory

extern "C" {
void* memset(void* dst, int c, unsigned long n);
}

inline void* operator new(unsigned long, void* p) { return p; }

namespace World { class EntityHandleBase; }
namespace Sext { class zFogAsset; }

namespace World {

class xOGEntity {
public:
    xOGEntity(EntityHandleBase* handle);
};

}  // namespace World

class zFog : public World::xOGEntity {
public:
    zFog(World::EntityHandleBase* handle) : World::xOGEntity(handle) {}

    virtual void _v0();  virtual void _v1();  virtual void _v2();
    virtual void _v3();  virtual void _v4();  virtual void _v5();
    virtual void _v6();  virtual void _v7();  virtual void _v8();
    virtual void _v9();  virtual void _v10();  virtual void _v11();
    virtual void _v12();  virtual void _v13();  virtual void _v14();
    virtual void _v15();  virtual void _v16();  virtual void _v17();
    virtual void _v18();  virtual void _v19();
    virtual void Init(Sext::zFogAsset* asset);

    unsigned char _pad0[0x40 - 0x4];
};

namespace Sext {

class zFogAsset {
public:
    static ::zFog* Create(World::EntityHandleBase* handle,
                          zFogAsset* asset);
};

}  // namespace Sext

zFog* Sext::zFogAsset::Create(World::EntityHandleBase* handle,
                              zFogAsset* asset) {
    ::zFog* entity = new (memset(
        Memory::AllocGlobalHeap(sizeof(::zFog), (Memory::GlobalHeapEnum)0,
                                (eMemMgrTag)16, false),
        0, sizeof(::zFog))) ::zFog(handle);

    entity->Init(asset);

    return entity;
}
