// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

enum _GameOstrich { _GameOstrich_ = 0x7FFFFFFF };

extern int gGameMode;
extern int gGameOstrich;
extern int gGameState;

int zGameGetOstrich();
int zGameModeGet();
void zGameSetOstrich(_GameOstrich value);
int zGameStateGet();

int zGameStateGet() { return gGameState; }
int zGameModeGet() { return gGameMode; }
int zGameGetOstrich() { return gGameOstrich; }
void zGameSetOstrich(_GameOstrich value) { gGameOstrich = (int)value; }
