// GENERATED by tools/gen_poolprefix.py; regenerate, do not edit.
//
// zGameState.cpp is a fragment of the unity translation unit WAD02.cpp.
// That unit's string pool (@stringBase0 at 0x8068BE28, 5231 bytes)
// is filled in order of first appearance across every file it
// included, and a reference bakes the string's pool OFFSET into
// the instruction. The 25 strings below are the ones that come
// before this file's own, in that order, so that compiled alone
// it gets the same offsets. This is data read from the image;
// retail has no such table, it has the files in front.

// The files in front also put .rodata ahead of this unit's
// float literals: in the image the unit's first literal
// (0x8068BA48) lies 50904 bytes past the lowest .rodata address the
// unit's translation unit forms (0x8067F370). mwcc shares one base
// among a function's literals only when they sit under 32 KB
// into .rodata, so a fragment compiled with nothing ahead is
// one word short per table. The image shows only what the
// linker kept, so the measured distance is a lower bound; the
// array is that distance or 32 KB, whichever is more. It is
// referenced by nothing and holds nothing.
static const unsigned char kUnityRodataAhead[50904] = {1};

static const char* const kUnityPoolPrefix[] = {
    "BalloonB",  // +0
    "BalloonB1",  // +9
    "BalloonB2",  // +19
    "BalloonB3",  // +29
    "BalloonB4",  // +39
    "BalloonB5",  // +49
    "BalloonS",  // +59
    "BalloonS1",  // +68
    "BalloonS2",  // +78
    "BalloonS3",  // +88
    "BalloonG",  // +98
    "BalloonG1",  // +107
    "MissingModel_ModelReference",  // +117
    "SBNuggetBecomeUnhappyScriptRef",  // +145
    "UID_A_BOOT_collect_unhap_nug",  // +176
    "FLOATING_COLLECTIBLE_TURN_UNHAPPY",  // +205
    "FloatingCollectible",  // +239
    "zFountain",  // +259
    "GlobalPuckAttackCounterReference",  // +269
    "CollectibleSpawner",  // +302
    "WMLTYPE_SpawnCollectible_Event",  // +321
    "WMLTYPE_SpawnCollectibleAtPosition_Event",  // +352
    "%d",  // +393
    "FMV%c%s_%s",  // +396
    "FMV%c%s",  // +407
};
