// GENERATED by tools/transplant.py from a matched twin.
// Do not hand-edit: re-emit, or take the file over and remove this
// banner -- written_vs_generated.py splits on it.
//
// zLensFlareSpawnPt, transplanted from
// Create__Q24Sext11xGroupAssetFPQ25World16EntityHandleBasePQ24Sext11xGroupAsset,
// which is matched. The shapes are identical instruction for
// instruction; the holes were 3, and every one of them is
// read from the retail image rather than guessed:
//
//   +0x020  li      r3,104
//   +0x030  li      r5,104
//   +0x050  addi    r3,r3,1616  = 806C0650  __vt__17zLensFlareSpawnPt
//
// The DWARF places this function in zLensFlare.cpp.

enum eMemMgrTag { eMemMgrTag_ = 0x7FFFFFFF };

namespace Memory {
enum GlobalHeapEnum { GlobalHeapEnum_ = 0x7FFFFFFF };

void* AllocGlobalHeap(unsigned long size, GlobalHeapEnum heap, eMemMgrTag tag,
                      bool clear);
}  // namespace Memory

extern "C" {
void* memset(void* dst, int c, unsigned long n);
}

inline void* operator new(unsigned long, void* p) { return p; }

namespace World {
class EntityHandleBase;
}

class zLensFlareSpawnPt;


// 0x38, and polymorphic: the vtable pointer the constructor stores
// sits at +0, so nothing precedes it.
class xBase {
public:
    virtual void _v0();

    unsigned char _pad0[0x34 - 0x4];
};

namespace World {

class xOGEntity : public xBase {
public:
    xOGEntity(EntityHandleBase* handle);

    unsigned char _pad0[0x40 - 0x34];
};

}  // namespace World

namespace Sext {

class LensFlareSpawnPt {
public:
    static zLensFlareSpawnPt* Create(World::EntityHandleBase* handle,
                                     LensFlareSpawnPt* asset);
};

}  // namespace Sext

class zLensFlareSpawnPt : public World::xOGEntity {
public:
    zLensFlareSpawnPt(World::EntityHandleBase* handle) : World::xOGEntity(handle) {}

    virtual void _v0();


    void Init(Sext::LensFlareSpawnPt* asset);

    unsigned char _pad0[0x68 - 0x40];
};

zLensFlareSpawnPt* Sext::LensFlareSpawnPt::Create(World::EntityHandleBase* handle,
                                                  LensFlareSpawnPt* asset) {
    zLensFlareSpawnPt* entity = new (memset(
        Memory::AllocGlobalHeap(sizeof(zLensFlareSpawnPt), (Memory::GlobalHeapEnum)0,
                                (eMemMgrTag)16, false),
        0, sizeof(zLensFlareSpawnPt))) zLensFlareSpawnPt(handle);

    entity->Init((Sext::LensFlareSpawnPt*)asset);

    return entity;
}
