// GENERATED by tools/gen_poolprefix.py; regenerate, do not edit.
//
// zNPCBTAction.cpp is a fragment of the unity translation unit WAD02.cpp.
// That unit's string pool (@stringBase0 at 0x8068BE28, 5231 bytes)
// is filled in order of first appearance across every file it
// included, and a reference bakes the string's pool OFFSET into
// the instruction. The 204 strings below are the ones that come
// before this file's own, in that order, so that compiled alone
// it gets the same offsets. This is data read from the image;
// retail has no such table, it has the files in front.

// The files in front also put .rodata ahead of this unit's
// float literals: in the image the unit's first literal
// (0x8068BA28) lies 50872 bytes past the lowest .rodata address the
// unit's translation unit forms (0x8067F370). mwcc shares one base
// among a function's literals only when they sit under 32 KB
// into .rodata, so a fragment compiled with nothing ahead is
// one word short per table. The image shows only what the
// linker kept, so the measured distance is a lower bound; the
// array is that distance or 32 KB, whichever is more. It is
// referenced by nothing and holds nothing.
static const unsigned char kUnityRodataAhead[50872] = {1};

static const char* const kUnityPoolPrefix[] = {
    "BalloonB",  // +0
    "BalloonB1",  // +9
    "BalloonB2",  // +19
    "BalloonB3",  // +29
    "BalloonB4",  // +39
    "BalloonB5",  // +49
    "BalloonS",  // +59
    "BalloonS1",  // +68
    "BalloonS2",  // +78
    "BalloonS3",  // +88
    "BalloonG",  // +98
    "BalloonG1",  // +107
    "MissingModel_ModelReference",  // +117
    "SBNuggetBecomeUnhappyScriptRef",  // +145
    "UID_A_BOOT_collect_unhap_nug",  // +176
    "FLOATING_COLLECTIBLE_TURN_UNHAPPY",  // +205
    "FloatingCollectible",  // +239
    "zFountain",  // +259
    "GlobalPuckAttackCounterReference",  // +269
    "CollectibleSpawner",  // +302
    "WMLTYPE_SpawnCollectible_Event",  // +321
    "WMLTYPE_SpawnCollectibleAtPosition_Event",  // +352
    "%d",  // +393
    "FMV%c%s_%s",  // +396
    "FMV%c%s",  // +407
    "master",  // +415
    "SB_Hammer_Widget_Rumble_FX_Ref",  // +422
    "Hammer",  // +453
    "HammerUp",  // +460
    "HammerStriking",  // +469
    "HammerImpact",  // +484
    "HammerRecoil",  // +497
    "CHAR",  // +510
    "ButtonHammerStrength",  // +515
    "ButtonIdle",  // +536
    "ButtonStrengthOne",  // +547
    "ButtonStrengthTwo",  // +565
    "ButtonStrengthThree",  // +583
    "ButtonActivated",  // +603
    "ShowPuckAmmo",  // +619
    "HidePuckAmmo",  // +632
    "SetFluidMeter",  // +645
    "ShowFluidMeter",  // +659
    "HideFluidMeter",  // +674
    "ShowPlanktonHud",  // +689
    "HidePlanktonHud",  // +705
    "SetPlanktonStunMode",  // +721
    "SetPlanktonHurtMode",  // +741
    "HideTimer",  // +761
    "HideCounter",  // +771
    "HideBossMeter",  // +783
    "COLLECTIBLE_HAPPY_POINT_COUNTER_reference",  // +797
    "COLLECTIBLE_LIFE_reference",  // +839
    "InitHud",  // +866
    "UID_A_BOOT_Music_timetrial",  // +874
    "ShowHud",  // +901
    "HideHud",  // +909
    "HudVisible",  // +917
    "HudInvisible",  // +928
    "SetHealth",  // +941
    "SetMaxHealth",  // +951
    "SetPuckAmmo",  // +964
    "HidePowerupSpongebuff",  // +976
    "HidePowerupSpin",  // +998
    "HidePowerupHammer",  // +1014
    "HidePowerupPuck",  // +1032
    "HidePowerupInvicibility",  // +1048
    "ShowPowerupSpongebuff",  // +1072
    "ShowPowerupSpin",  // +1094
    "ShowPowerupHammer",  // +1110
    "ShowPowerupPuck",  // +1128
    "ShowPowerupInvicibility",  // +1144
    "SetPowerupTimer",  // +1168
    "SetHappinessPoints",  // +1184
    "H",  // +1203
    "T",  // +1205
    "SetPlanktonAmmo",  // +1207
    "ShowCounter",  // +1223
    "SetCounter",  // +1235
    "ShowTimer",  // +1246
    "SetTimer",  // +1256
    "SetBossMeter",  // +1265
    "ShowBossMeter",  // +1278
    "SetLives",  // +1292
    "TikiScreenPlayer_reference",  // +1301
    "strings",  // +1328
    "ShowTiki",  // +1336
    "HideTiki",  // +1345
    "BuyScreenPlayer_reference",  // +1354
    "Hide",  // +1380
    "Show",  // +1385
    "Init",  // +1390
    "SetEyeStunnable",  // +1395
    "SetEyeHurtable",  // +1411
    "SetEyeNeutral",  // +1426
    "SetRimGrabbable",  // +1440
    "SetRimNeutral",  // +1456
    "TtzLaser_CheckLOS",  // +1470
    "Et",  // +1488
    "TtxHavok_TestRaysInSimWorld",  // +1491
    "TtblockedLOS",  // +1519
    "LetterBox_reference",  // +1532
    "_root.AnimateInPop",  // +1552
    "_root.AnimateOut",  // +1571
    "_root.ShowEventSkippable",  // +1588
    "UID_",  // +1613
    "zLocatorEntity",  // +1618
    "HBM_Disallowed_reference",  // +1633
    "%s%c%s",  // +1658
    "sb09.ini",  // +1665
    "BOOT",  // +1674
    "audiomasher",  // +1679
    "soak",  // +1691
    "SoakLevels",  // +1696
    " ,",  // +1707
    " .",  // +1710
    "dumpCinematics",  // +1713
    "dumpCinematicsFilePrefix",  // +1728
    "cinematic_dump",  // +1753
    "dumpCinematicsFrameRate",  // +1768
    "ProfFuncTriangle",  // +1792
    "",  // +1809
    "ProfFuncSquare",  // +1810
    "ProfFuncLeft",  // +1825
    "ProfFuncRight",  // +1838
    "ProfFuncUp",  // +1852
    "ProfFuncDown",  // +1863
    "NoMusic",  // +1876
    "NoSoundFX",  // +1884
    "enableWireFrameDebugger",  // +1894
    "enableWireFrameDebuggerConvexShapes",  // +1918
    "wireFrameDebuggerDrawDistance",  // +1954
    "NoCutscenes",  // +1984
    "NoPadCheck",  // +1996
    "SkippableCutscenes",  // +2007
    "WiiPerformanceWarnings",  // +2026
    "SuperSoaker",  // +2049
    "SoakStatisticsMode",  // +2061
    "AudioMasher",  // +2080
    "MenuMasher",  // +2092
    "Watermark",  // +2103
    "WatermarkAlpha",  // +2113
    "WatermarkSize",  // +2128
    "NoDamage",  // +2142
    "g.DamageInvincibility",  // +2151
    "g.Gravity",  // +2173
    "g.CameraFOV",  // +2183
    "DisableScaleformRenderingInMasterDuringCinematics",  // +2195
    "ShowTimecodeDuringCinematics",  // +2245
    "NoMovies",  // +2274
    "option_vibration_p1",  // +2283
    "OptionSubtitles",  // +2303
    "OXMDemo",  // +2319
    "MNUI",  // +2327
    "MNUS",  // +2332
    "VideoSystem",  // +2337
    "PAL",  // +2349
    "NTSC",  // +2353
    "ShowMenuOnBoot",  // +2358
    "SkipAsserts",  // +2373
    "DemoType",  // +2385
    "AllowMasterCheats",  // +2394
    "FlashWIP",  // +2412
    "ShortbreadCookieJar",  // +2421
    "AttractModeDuringGameplay",  // +2441
    "RealVine",  // +2467
    "EnableFriendlyFly",  // +2476
    "EnableHUD",  // +2494
    "EnableLetterboxDuringCinematic",  // +2504
    "WristStrap_reference",  // +2535
    "DebugFont",  // +2556
    "ProgrammaticUIImmediateModel_reference",  // +2566
    "????",  // +2605
    "%c%c%c%c",  // +2610
    "MASTER",  // +2619
    "%d %d\t%s\t%c%c%c%c\t%.4f %.4f %.4f\t%s",  // +2626
    "BUILD\tCONFIG\tSCENE\tPOS\tPLAYER",  // +2662
    "EN_US",  // +2692
    "EN_CA",  // +2698
    "FR_CA",  // +2704
    "ES_MX",  // +2710
    "DefaultRegion",  // +2716
    "EN_UK",  // +2730
    "DE_DE",  // +2736
    "FR_FR",  // +2742
    "ES_ES",  // +2748
    "IT_IT",  // +2754
    "PT_PT",  // +2760
    "NL_NL",  // +2766
    "RU_RU",  // +2772
    "FI_FI",  // +2778
    "SV_SE",  // +2784
    "DA_DK",  // +2790
    "NO_NO",  // +2796
    "GR_GR",  // +2802
    "EN_AU",  // +2808
    "LanguageSetting",  // +2814
    "mnls_reference",  // +2830
    "Menu01",  // +2845
    "UI CREATESAVE TEXT",  // +2852
    "Debug Metrics Module",  // +2871
    "Example Module",  // +2892
    "NPC Manager",  // +2907
    "NPC Ninja Manager",  // +2919
};
