// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

class xAnimSingle;
class xAnimTransition;


class zPlantTrap {
public:
    int* GetAttachDPos();
    bool HitCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anDoneChewCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool DoneChewCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anEatCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool EatCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anGoToSpitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool GoToSpitCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anHitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    static bool anIdleCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool IdleCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anProneCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    static bool anProneOutCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool ProneOutCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anReleaseCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool ReleaseCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anSnapCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool SnapCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anSnapEntityCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool SnapEntityCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anSpitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool SpitCheck(xAnimTransition* a0, xAnimSingle* a1);
    static bool anWarnCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    bool WarnCheck(xAnimTransition* a0, xAnimSingle* a1);

    unsigned char _pad0[0x5C];
    int f5C;
    unsigned char _pad1[0x30];
    int f90;
};


int* zPlantTrap::GetAttachDPos() { return &f90; }
bool zPlantTrap::anWarnCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->WarnCheck(a0, a1); }
bool zPlantTrap::anProneOutCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->ProneOutCheck(a0, a1); }
bool zPlantTrap::anSnapCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->SnapCheck(a0, a1); }
bool zPlantTrap::anSnapEntityCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->SnapEntityCheck(a0, a1); }
bool zPlantTrap::anReleaseCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->ReleaseCheck(a0, a1); }
bool zPlantTrap::anEatCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->EatCheck(a0, a1); }
bool zPlantTrap::anHitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->HitCheck(a0, a1); }
bool zPlantTrap::anGoToSpitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->GoToSpitCheck(a0, a1); }
bool zPlantTrap::anDoneChewCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->DoneChewCheck(a0, a1); }
bool zPlantTrap::anProneCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->f5C == 9; }
bool zPlantTrap::anSpitCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->SpitCheck(a0, a1); }
bool zPlantTrap::anIdleCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zPlantTrap*)a2)->IdleCheck(a0, a1); }
bool zPlantTrap::HitCheck(xAnimTransition* a0, xAnimSingle* a1) { return f5C == 5; }
