// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

class hkpPhantom;
class xEnt;


class zPlanktonTargetListener {
public:
    virtual void _v0() const;
    virtual void _v1() const;
    virtual void _v2() const;
    virtual void _v3() const;
    virtual void _v4() const;
    virtual void _v5() const;
    virtual void _v6() const;
    virtual void _v7() const;
    virtual void _v8() const;
    virtual void _v9() const;
    virtual void _v10() const;
    virtual void _v11() const;
    virtual void _v12() const;
    virtual void _v13() const;
    virtual void _v14(hkpPhantom* a0) const;
    void phantomDeletedCallback(hkpPhantom* a0);

};



class hkpWorldRayCastInput {
public:
    hkpWorldRayCastInput();

    unsigned char _pad0[0x20];
    unsigned char f20;
    unsigned char _pad1[0x3];
    int f24;
};



class hkpShapeRayCastInput {
public:
    hkpShapeRayCastInput();

    unsigned char _pad0[0x20];
    int f20;
    int f24;
};



class zPlanktonShakeManager {
public:
    static int currentShakeState;
    int* GetShakeState(const xEnt* a0);

};


void zPlanktonTargetListener::phantomDeletedCallback(hkpPhantom* a0) { _v14(a0); }
hkpWorldRayCastInput::hkpWorldRayCastInput() { f20 = 0; f24 = 0; }
hkpShapeRayCastInput::hkpShapeRayCastInput() { f20 = 0; f24 = 0; }
int* zPlanktonShakeManager::GetShakeState(const xEnt* a0) { return &zPlanktonShakeManager::currentShakeState; }
