// zPlanktonPlayer.cpp -- hand-owned since the animation tables were added.
//
// The accessor part below was generated by
// tools/gen_accessors.py and is kept as it was written;
// gen_units.py now HOLDS this file rather than regenerating
// it, so a new accessor candidate is merged in by hand. The
// tables were merged by tools/gen_animtables.py.
//
// This file is a fragment of a unity build: the generated
// header puts the whole string pool in front, so the string
// offsets baked into the code come out as retail has them.
#include "SB/GM/Engine/Game/zPlanktonPlayer.pool.h"

class xAnimTable;
class xAnimState;
class xAnimPlay;
class xQuat;
class xVec3;
class xAnimSingle;
class xAnimTransition;
unsigned int xAnimTableNewState(xAnimTable* table, const char* name, unsigned int a, unsigned int b, float c, float* d, float* e, float f, unsigned short* g, void* h, void (*i)(xAnimPlay*, xAnimState*, void*), void (*j)(xAnimPlay*, xAnimState*, void*), void (*k)(xAnimState*, xAnimSingle*, void*), void (*l)(xAnimPlay*, xQuat*, xVec3*, xVec3*, int), unsigned long long m, unsigned int n);
unsigned int xAnimTableNewTransition(xAnimTable* table, const char* from, const char* to, unsigned int (*a)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*b)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*), unsigned int d, unsigned int e, float f, float g, unsigned short h, unsigned short i, float j, unsigned short* k);

// -- generated accessor part (gen_accessors.py) ------------
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

// The action base, as zPlayerAction.cpp declares it: three members and
// then the virtuals, so the vptr sits at +12 and slots 1, 2, 3 are the
// three transition-adding virtuals the tables below dispatch through
// (`lwz r12,12(r3); lwz r12,8|12|20(r12); bctrl`). A table class that
// makes such a call derives from this stub, and reaches the manager's
// action array through `manager`, its first word.
class zPlayer;
class zPlayerActionManager;
// The two dereferences every animation callback makes. Nothing in
// the image NAMES either type, so both are spelled as the offsets
// that were measured. Neither struct emits a symbol.
struct AnimCBSlot { unsigned char _pad[0x90]; void* owner; };
struct AnimCBHolder { unsigned char _pad[0x4]; AnimCBSlot* slot; };

class zPlayerAction {
public:
    zPlayerActionManager* manager;
    zPlayer* player;
    void (*doneCB)(zPlayerAction*);

    enum SpecialActions { SpecialActions_ = 0x7FFFFFFF };

    virtual void _v0();
    virtual void AddStandardTransitions(xAnimTable* table, const char* name);
    virtual void AddDefaultTransitions(xAnimTable* table, const char* name);
    virtual void AddTransitions(xAnimTable* table, const char* name,
                                unsigned int (*a)(xAnimTransition*, xAnimSingle*, void*),
                                unsigned int (*b)(xAnimTransition*, xAnimSingle*, void*),
                                unsigned short e, float f, unsigned int g,
                                unsigned int h, SpecialActions i);

    // Slot 5 is what every one of the image's 116-byte animation
    // callbacks tests before it forwards: `lwz r12,28(r12)` on a
    // vptr that sits at +12, and (28 - 8) / 4 is 5. Appended, so the
    // three slots the tables call keep the indices they have.
    virtual bool _v4();
    virtual bool _v5();

    unsigned int NewState(xAnimTable* table, const char* name,
                          unsigned int a, unsigned int b, float c,
                          float* d, float* e, float f, unsigned short* g,
                          void (*h)(xAnimPlay*, xAnimState*, void*),
                          void (*i)(xAnimPlay*, xAnimState*, void*),
                          void (*j)(xAnimState*, xAnimSingle*, void*),
                          void (*k)(xAnimPlay*, xQuat*, xVec3*, xVec3*, int),
                          unsigned int l);
    static unsigned int ActionChange(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int AddActionTransition(
        xAnimTable* table, const char* from, const char* to,
        unsigned int (*a)(xAnimTransition*, xAnimSingle*, void*),
        unsigned int (*b)(xAnimTransition*, xAnimSingle*, void*),
        unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*),
        unsigned short g, float h, unsigned int i, unsigned int j);
};

// The manager, and the three helpers zPlayerAction.cpp defines as
// `actions[id]->...(...)`. Retail's unity build held that file in
// the same translation unit as the tables (WAD03) and -O4 inlined
// them, and the inlined form is what the bytes say: a table written
// as the direct `manager->actions[k]->AddTransitions(...)` creates
// the pool-string temp before the load chain, retail after it --
// zPlayerRunSB 5 of 299 words, zSBPlayerPuckAttack 9 of 164, both
// exact once spelled through the helper. Inline here so the
// fragment inlines them the same way and emits no copy.
class zPlayerActionManager {
public:
    zPlayerAction** actions;

    void AddStandardTransitionsTo(unsigned int id, xAnimTable* table, const char* name);
    void AddDefaultTransitionsTo(unsigned int id, xAnimTable* table, const char* name);
    void AddTransitionsTo(unsigned int id, xAnimTable* table, const char* name,
                          unsigned int (*a)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*b)(xAnimTransition*, xAnimSingle*, void*),
                          unsigned short e, float f, unsigned int g,
                          unsigned int h, zPlayerAction::SpecialActions i);
};

inline void zPlayerActionManager::AddStandardTransitionsTo(unsigned int id, xAnimTable* table, const char* name) {
    actions[id]->AddStandardTransitions(table, name);
}
inline void zPlayerActionManager::AddDefaultTransitionsTo(unsigned int id, xAnimTable* table, const char* name) {
    actions[id]->AddDefaultTransitions(table, name);
}
inline void zPlayerActionManager::AddTransitionsTo(unsigned int id, xAnimTable* table, const char* name,
                                                   unsigned int (*a)(xAnimTransition*, xAnimSingle*, void*), unsigned int (*b)(xAnimTransition*, xAnimSingle*, void*),
                                                   unsigned short e, float f, unsigned int g,
                                                   unsigned int h, zPlayerAction::SpecialActions i) {
    actions[id]->AddTransitions(table, name, a, b, e, f, g, h, i);
}

// zPlayerAction.cpp defines this, and retail's unity build had it in the
// same translation unit as the tables (WAD03: 80105550..801894A0 holds
// both), where -O4's auto-inliner took it: an action table's direct
// xAnimTableNewTransition with ActionChange as its third callback and
// the fixed zeros is this call, its `c == 0` test folded away. Inline
// here so the fragment inlines it the same way and emits no copy.
// NewState is the same story as AddActionTransition below: defined in
// zPlayerAction.cpp, inlined by retail's unity build. A state table
// spelled as the direct xAnimTableNewState with `this` as the owner
// hoists its constants in another order (zPlayerHitSB::AddStates 250
// of 385 words); through the helper, 0.
inline unsigned int zPlayerAction::NewState(
    xAnimTable* table, const char* name, unsigned int a, unsigned int b,
    float c, float* d, float* e, float f, unsigned short* g,
    void (*h)(xAnimPlay*, xAnimState*, void*),
    void (*i)(xAnimPlay*, xAnimState*, void*),
    void (*j)(xAnimState*, xAnimSingle*, void*),
    void (*k)(xAnimPlay*, xQuat*, xVec3*, xVec3*, int), unsigned int l) {
    return xAnimTableNewState(table, name, a, b, c, d, e, f, g, this,
                              h, i, j, k, 0, l);
}
inline unsigned int zPlayerAction::AddActionTransition(
    xAnimTable* table, const char* from, const char* to,
    unsigned int (*a)(xAnimTransition*, xAnimSingle*, void*),
    unsigned int (*b)(xAnimTransition*, xAnimSingle*, void*),
    unsigned int (*c)(xAnimTransition*, xAnimSingle*, void*),
    unsigned short g, float h, unsigned int i, unsigned int j) {
    if (c == 0) {
        c = ActionChange;
    }

    return xAnimTableNewTransition(table, from, to, a, b, c, i, j, 0.0f,
                                   0.0f, g, 0, h, 0);
}

class hkpPhantom;
class xEnt;


class zPlanktonTargetListener {
public:
    virtual void _v0() const;
    virtual void _v1() const;
    virtual void _v2() const;
    virtual void _v3() const;
    virtual void _v4() const;
    virtual void _v5() const;
    virtual void _v6() const;
    virtual void _v7() const;
    virtual void _v8() const;
    virtual void _v9() const;
    virtual void _v10() const;
    virtual void _v11() const;
    virtual void _v12() const;
    virtual void _v13() const;
    virtual void _v14(hkpPhantom* a0) const;
    void phantomDeletedCallback(hkpPhantom* a0);

};



class hkpWorldRayCastInput {
public:
    hkpWorldRayCastInput();

    unsigned char _pad0[0x20];
    unsigned char f20;
    unsigned char _pad1[0x3];
    int f24;
};



class hkpShapeRayCastInput {
public:
    hkpShapeRayCastInput();

    unsigned char _pad0[0x20];
    int f20;
    int f24;
};



class zPlanktonShakeManager {
public:
    static int currentShakeState;
    int* GetShakeState(const xEnt* a0);

};


void zPlanktonTargetListener::phantomDeletedCallback(hkpPhantom* a0) { _v14(a0); }
hkpWorldRayCastInput::hkpWorldRayCastInput() { f20 = 0; f24 = 0; }
hkpShapeRayCastInput::hkpShapeRayCastInput() { f20 = 0; f24 = 0; }
int* zPlanktonShakeManager::GetShakeState(const xEnt* a0) { return &zPlanktonShakeManager::currentShakeState; }

class zPlayerIdlePlankton : public zPlayerAction {
public:
    void AddTransitionsFrom(xAnimTable* table, const char* name,
                            unsigned int (*a)(xAnimTransition*, xAnimSingle*, void*),
                            unsigned int (*b)(xAnimTransition*, xAnimSingle*, void*),
                            unsigned short e, float f, unsigned int g,
                            unsigned int h, zPlayerAction::SpecialActions i);
    // Members from the DWARF (zPlayerIdlePlankton is 0x1C bytes).
    xAnimState* talkState[2];
    unsigned char nextTalkState;

    static unsigned int anEnterCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anExitCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anIdleCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anShakeCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anShakeMissCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anStopTalkAnimCB(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anTalkCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anZapHurtCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anZapMissCheck(xAnimTransition*, xAnimSingle*, void*);
    static unsigned int anZapStunCheck(xAnimTransition*, xAnimSingle*, void*);
    void AddInternalTransitions(xAnimTable* table);
    void AddStates(xAnimTable* table);
    bool ShakeMissCheck(xAnimTransition* a0, xAnimSingle* a1);
    bool TalkCheck(xAnimTransition* a0, xAnimSingle* a1);
    bool ZapMissCheck(xAnimTransition* a0, xAnimSingle* a1);
};

// -- the animation tables, read from the image ------------------

// zPlayerIdlePlankton::AddStates: 11 call(s)
void zPlayerIdlePlankton::AddStates(xAnimTable* table) {
    NewState(table, "Hidden01", 16, 16384, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "Idle01", 16, 0x2004000, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "Enter01", 32, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "Exit01", 32, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "AttackShake01", 16, 0x2000000, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "AttackShakeMiss01", 32, 0x2000000, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "AttackStun01", 32, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "AttackShoot01", 32, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    NewState(table, "AttackEmpty01", 32, 0x2000000, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    talkState[0] = (xAnimState*)NewState(table, "Talk01", 32, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
    talkState[1] = (xAnimState*)NewState(table, "Talk02", 32, 0, 1.0f, 0, 0, 0.0f, 0, 0, 0, 0, 0, 0);
}

// zPlayerIdlePlankton::AddInternalTransitions: 24 call(s)
void zPlayerIdlePlankton::AddInternalTransitions(xAnimTable* table) {
    float FAST_BLEND_TIME = 0.06666667f;
    xAnimTableNewTransition(table, "Hidden01", "Enter01", 0, zPlayerIdlePlankton::anEnterCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "Exit01", "Enter01", 0, zPlayerIdlePlankton::anEnterCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "Exit01", "Enter01", 0, zPlayerIdlePlankton::anEnterCheck, 0, 16, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "Exit01", 0, zPlayerIdlePlankton::anExitCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "Exit01", 0, zPlayerIdlePlankton::anExitCheck, 0, 16, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "Exit01", "Hidden01", 0, 0, 0, 16, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "Enter01", "Idle01", 0, 0, 0, 16, 0, 0.0f, 0.0f, 999, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "Attack*", "Idle01", 0, 0, 0, 16, 0, 0.0f, 0.0f, 999, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "AttackShake01", "Idle01", 0, zPlayerIdlePlankton::anIdleCheck, 0, 0, 0, 0.0f, 0.0f, 999, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "AttackShake01", 0, zPlayerIdlePlankton::anShakeCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "AttackShakeMiss01", 0, zPlayerIdlePlankton::anShakeMissCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "AttackStun01", 0, zPlayerIdlePlankton::anZapStunCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "AttackShoot01", 0, zPlayerIdlePlankton::anZapHurtCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "AttackEmpty01", 0, zPlayerIdlePlankton::anZapMissCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "AttackShake01", 0, zPlayerIdlePlankton::anShakeCheck, 0, 16, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "AttackShakeMiss01", 0, zPlayerIdlePlankton::anShakeMissCheck, 0, 16, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "AttackStun01", 0, zPlayerIdlePlankton::anZapStunCheck, 0, 16, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "AttackShoot01", 0, zPlayerIdlePlankton::anZapHurtCheck, 0, 16, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "AttackEmpty01", 0, zPlayerIdlePlankton::anZapMissCheck, 0, 16, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "*", "Talk01", 0, zPlayerIdlePlankton::anTalkCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "Talk01", "Talk02", 0, zPlayerIdlePlankton::anTalkCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "Talk02", "Talk01", 0, zPlayerIdlePlankton::anTalkCheck, 0, 0, 0, 0.0f, 0.0f, 1000, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "Talk01", "Idle01", 0, zPlayerIdlePlankton::anIdleCheck, zPlayerIdlePlankton::anStopTalkAnimCB, 16, 0, 0.0f, 0.0f, 999, 0, FAST_BLEND_TIME, 0);
    xAnimTableNewTransition(table, "Talk02", "Idle01", 0, zPlayerIdlePlankton::anIdleCheck, zPlayerIdlePlankton::anStopTalkAnimCB, 16, 0, 0.0f, 0.0f, 999, 0, FAST_BLEND_TIME, 0);
}

// zPlayerIdlePlankton::AddTransitionsFrom: every transition INTO the idle, from the
// state `name`: the action helper with the idle's own check as the
// first callback and the caller's as the second and third.
void zPlayerIdlePlankton::AddTransitionsFrom(xAnimTable* table, const char* name,
                            unsigned int (*a)(xAnimTransition*, xAnimSingle*, void*),
                            unsigned int (*b)(xAnimTransition*, xAnimSingle*, void*),
                            unsigned short e, float f, unsigned int g,
                            unsigned int h, zPlayerAction::SpecialActions i) {
    zPlayerAction::AddActionTransition(table, name, "Idle01", zPlayerIdlePlankton::anIdleCheck, a, b, e, f, g, h);
}

unsigned int zPlayerIdlePlankton::anShakeMissCheck(xAnimTransition* a0, xAnimSingle* a1,
                                                   void* a2) {
    unsigned int result = 0;

    if (((zPlayerIdlePlankton*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerIdlePlankton*)((AnimCBHolder*)a0)->slot->owner)->ShakeMissCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerIdlePlankton::anTalkCheck(xAnimTransition* a0, xAnimSingle* a1,
                                              void* a2) {
    unsigned int result = 0;

    if (((zPlayerIdlePlankton*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerIdlePlankton*)((AnimCBHolder*)a0)->slot->owner)->TalkCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}

unsigned int zPlayerIdlePlankton::anZapMissCheck(xAnimTransition* a0, xAnimSingle* a1,
                                                 void* a2) {
    unsigned int result = 0;

    if (((zPlayerIdlePlankton*)((AnimCBHolder*)a0)->slot->owner)->_v5()) {
        if (((zPlayerIdlePlankton*)((AnimCBHolder*)a0)->slot->owner)->ZapMissCheck(a0, a1)) {
            result = 1;
        }
    }

    return result;
}
