// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

namespace Sext { class EventAny; }
class xBase;


class zProjectileSpawner {
public:
    static void StaticHandleEvent(xBase* a0, xBase* a1, unsigned int a2, Sext::EventAny* a3);
    void HandleEvent(xBase* a0, unsigned int a1, Sext::EventAny* a2);

};


void zProjectileSpawner::StaticHandleEvent(xBase* a0, xBase* a1, unsigned int a2, Sext::EventAny* a3) { ((zProjectileSpawner*)a1)->HandleEvent(a1, a2, a3); }
