// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.


class zProjectileHavok {
public:
    int GetOwnerProjectile();

    unsigned char _pad0[0x80];
    int f80;
};


int zProjectileHavok::GetOwnerProjectile() { return f80; }

// The 80-byte base-only destructor, the compiler's own: the
// null-this test, the BASE's destructor on `this` with the flag
// CLEAR -- r4 = 0 is a base subobject where r4 = -1 is a complete
// one -- then operator delete when the CALLER's flag is positive,
// and `return this`. No member is destroyed, so the class needs
// nothing but its base.
//
// Non-virtual throughout: the call is a direct `bl` either way, and
// a virtual destructor would make this unit the home of a vtable
// retail keeps elsewhere. Where the base's destructor folded onto
// __dt__12hkBaseObjectFv -- 64 bytes of null test, conditional
// operator delete and `return this` -- the base is spelled as the
// symbol that survived, which is what makes the relocation reach
// retail's own.
void operator delete(void* mem);

class hkBaseObject {
public:
    ~hkBaseObject();
};

class ProjectileCollisionListener : public hkBaseObject {
public:
    ~ProjectileCollisionListener();
};

ProjectileCollisionListener::~ProjectileCollisionListener() {}
