// GENERATED by tools/transplant.py from a matched twin.
// Do not hand-edit: re-emit, or take the file over and remove this
// banner -- written_vs_generated.py splits on it.
//
// zPuckReflector, transplanted from
// Create__Q24Sext13zSpinnerAssetFPQ25World16EntityHandleBasePQ24Sext13zSpinnerAsset,
// which is matched. The shapes are identical instruction for
// instruction; the holes were 2, and every one of them is
// read from the retail image rather than guessed:
//
//   +0x020  li      r3,168
//   +0x030  li      r5,168
//
// The entity constructor is a CALL, so it is declared and never
// defined and no vtable is stored here. The class is padded to
// the size the allocation asks for, which is the only thing
// about its layout this file knows.
//
// The DWARF places this function in zPuckReflector.cpp.

enum eMemMgrTag { eMemMgrTag_ = 0x7FFFFFFF };

namespace Memory {
enum GlobalHeapEnum { GlobalHeapEnum_ = 0x7FFFFFFF };

void* AllocGlobalHeap(unsigned long size, GlobalHeapEnum heap, eMemMgrTag tag,
                      bool clear);
}  // namespace Memory

extern "C" {
void* memset(void* dst, int c, unsigned long n);
}

inline void* operator new(unsigned long, void* p) { return p; }

namespace World { class EntityHandleBase; }



namespace Sext { class zPuckReflectorAsset; }

class zPuckReflector {
public:
    zPuckReflector(World::EntityHandleBase* handle,
                       Sext::zPuckReflectorAsset* asset);

    unsigned char _pad0[0xA8];
};

namespace Sext {

class zPuckReflectorAsset {
public:
    static zPuckReflector* Create(World::EntityHandleBase* handle,
                                  zPuckReflectorAsset* asset);
};

}  // namespace Sext

zPuckReflector* Sext::zPuckReflectorAsset::Create(World::EntityHandleBase* handle,
                                                  zPuckReflectorAsset* asset) {
    return new (memset(Memory::AllocGlobalHeap(
                           sizeof(zPuckReflector), (Memory::GlobalHeapEnum)0,
                           (eMemMgrTag)16, false),
                       0, sizeof(zPuckReflector))) zPuckReflector(handle, asset);
}
