// GENERATED by tools/transplant.py from a matched twin.
// Do not hand-edit: re-emit, or take the file over and remove this
// banner -- written_vs_generated.py splits on it.
//
// zRubberBand, transplanted from
// Create__Q24Sext13zSpinnerAssetFPQ25World16EntityHandleBasePQ24Sext13zSpinnerAsset,
// which is matched. The shapes are identical instruction for
// instruction; the holes were 3, and every one of them is
// read from the retail image rather than guessed:
//
//   +0x020  li      r3,656
//   +0x030  li      r5,656
//   +0x048  bl        -> __ct__11zRubberBandFPQ25World16EntityHandleBasePQ24Sext16zRubberBandAsset
//
// The entity constructor is a CALL, so it is declared and never
// defined and no vtable is stored here. The class is padded to
// the size the allocation asks for, which is the only thing
// about its layout this file knows.
//
// The DWARF places this function in zRubberBand.cpp.

enum eMemMgrTag { eMemMgrTag_ = 0x7FFFFFFF };

namespace Memory {
enum GlobalHeapEnum { GlobalHeapEnum_ = 0x7FFFFFFF };

void* AllocGlobalHeap(unsigned long size, GlobalHeapEnum heap, eMemMgrTag tag,
                      bool clear);
}  // namespace Memory

extern "C" {
void* memset(void* dst, int c, unsigned long n);
}

inline void* operator new(unsigned long, void* p) { return p; }

namespace World { class EntityHandleBase; }



namespace Sext { class zRubberBandAsset; }

class zRubberBand {
public:
    zRubberBand(World::EntityHandleBase* handle,
                    Sext::zRubberBandAsset* asset);

    unsigned char _pad0[0x290];
};

namespace Sext {

class zRubberBandAsset {
public:
    static zRubberBand* Create(World::EntityHandleBase* handle,
                               zRubberBandAsset* asset);
};

}  // namespace Sext

zRubberBand* Sext::zRubberBandAsset::Create(World::EntityHandleBase* handle,
                                            zRubberBandAsset* asset) {
    return new (memset(Memory::AllocGlobalHeap(
                           sizeof(zRubberBand), (Memory::GlobalHeapEnum)0,
                           (eMemMgrTag)16, false),
                       0, sizeof(zRubberBand))) zRubberBand(handle, asset);
}
