// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

class xAnimSingle;
class xAnimTransition;


class zSpringboard {
public:
    static bool anCompressCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    static bool anFailCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);
    static bool anLaunchCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2);

    unsigned char _pad0[0xC0];
    int fC0;
};


bool zSpringboard::anCompressCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zSpringboard*)a2)->fC0 == 1; }
bool zSpringboard::anLaunchCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zSpringboard*)a2)->fC0 == 3; }
bool zSpringboard::anFailCheck(xAnimTransition* a0, xAnimSingle* a1, void* a2) { return ((zSpringboard*)a2)->fC0 == 4; }
