// GENERATED by tools/transplant.py from a matched twin.
// Do not hand-edit: re-emit, or take the file over and remove this
// banner -- written_vs_generated.py splits on it.
//
// ztextbox, transplanted from
// Create__Q24Sext11xGroupAssetFPQ25World16EntityHandleBasePQ24Sext11xGroupAsset,
// which is matched. The shapes are identical instruction for
// instruction; the holes were 4, and every one of them is
// read from the retail image rather than guessed:
//
//   +0x020  li      r3,288
//   +0x030  li      r5,288
//   +0x050  addi    r3,r3,10288  = 806C2830  __vt__8ztextbox
//   +0x060  bl        -> load__8ztextboxFRCQ28ztextbox10asset_type
//
// The DWARF places this function in zTextBox.cpp.

enum eMemMgrTag { eMemMgrTag_ = 0x7FFFFFFF };

namespace Memory {
enum GlobalHeapEnum { GlobalHeapEnum_ = 0x7FFFFFFF };

void* AllocGlobalHeap(unsigned long size, GlobalHeapEnum heap, eMemMgrTag tag,
                      bool clear);
}  // namespace Memory

extern "C" {
void* memset(void* dst, int c, unsigned long n);
}

inline void* operator new(unsigned long, void* p) { return p; }

namespace World {
class EntityHandleBase;
}

class ztextbox;


// 0x38, and polymorphic: the vtable pointer the constructor stores
// sits at +0, so nothing precedes it.
class xBase {
public:
    virtual void _v0();

    unsigned char _pad0[0x34 - 0x4];
};

namespace World {

class xOGEntity : public xBase {
public:
    xOGEntity(EntityHandleBase* handle);

    unsigned char _pad0[0x40 - 0x34];
};

}  // namespace World

namespace Sext {

class text_box {
public:
    static ztextbox* Create(World::EntityHandleBase* handle,
                            text_box* asset);
};

}  // namespace Sext

class ztextbox : public World::xOGEntity {
public:
    ztextbox(World::EntityHandleBase* handle) : World::xOGEntity(handle) {}

    virtual void _v0();

    class asset_type;

    void load(const asset_type& asset);

    unsigned char _pad0[0x120 - 0x40];
};

ztextbox* Sext::text_box::Create(World::EntityHandleBase* handle,
                                 text_box* asset) {
    ztextbox* entity = new (memset(
        Memory::AllocGlobalHeap(sizeof(ztextbox), (Memory::GlobalHeapEnum)0,
                                (eMemMgrTag)16, false),
        0, sizeof(ztextbox))) ztextbox(handle);

    entity->load(*(const ztextbox::asset_type*)asset);

    return entity;
}
