// GENERATED by tools/transplant.py from a matched twin.
// Do not hand-edit: re-emit, or take the file over and remove this
// banner -- written_vs_generated.py splits on it.
//
// zUIFlashOnScreenText, transplanted from
// Create__Q24Sext11xGroupAssetFPQ25World16EntityHandleBasePQ24Sext11xGroupAsset,
// which is matched. The shapes are identical instruction for
// instruction; the holes were 4, and every one of them is
// read from the retail image rather than guessed:
//
//   +0x020  li      r3,216
//   +0x030  li      r5,216
//   +0x050  addi    r3,r3,-30208  = 806C8A00  __vt__20zUIFlashOnScreenText
//   +0x060  bl        -> init__20zUIFlashOnScreenTextFRQ24Sext10xBaseAsset
//
// The DWARF places this function in zUIFlashOnScreenText.cpp.

enum eMemMgrTag { eMemMgrTag_ = 0x7FFFFFFF };

namespace Memory {
enum GlobalHeapEnum { GlobalHeapEnum_ = 0x7FFFFFFF };

void* AllocGlobalHeap(unsigned long size, GlobalHeapEnum heap, eMemMgrTag tag,
                      bool clear);
}  // namespace Memory

extern "C" {
void* memset(void* dst, int c, unsigned long n);
}

inline void* operator new(unsigned long, void* p) { return p; }

namespace World {
class EntityHandleBase;
}

class zUIFlashOnScreenText;


namespace Sext { class xBaseAsset; }

// 0x38, and polymorphic: the vtable pointer the constructor stores
// sits at +0, so nothing precedes it.
class xBase {
public:
    virtual void _v0();

    unsigned char _pad0[0x34 - 0x4];
};

namespace World {

class xOGEntity : public xBase {
public:
    xOGEntity(EntityHandleBase* handle);

    unsigned char _pad0[0x40 - 0x34];
};

}  // namespace World

namespace Sext {

class zUIFlashOnScreenTextAsset {
public:
    static zUIFlashOnScreenText* Create(World::EntityHandleBase* handle,
                                        zUIFlashOnScreenTextAsset* asset);
};

}  // namespace Sext

class zUIFlashOnScreenText : public World::xOGEntity {
public:
    zUIFlashOnScreenText(World::EntityHandleBase* handle) : World::xOGEntity(handle) {}

    virtual void _v0();


    void init(Sext::xBaseAsset& asset);

    unsigned char _pad0[0xD8 - 0x40];
};

zUIFlashOnScreenText* Sext::zUIFlashOnScreenTextAsset::Create(World::EntityHandleBase* handle,
                                                              zUIFlashOnScreenTextAsset* asset) {
    zUIFlashOnScreenText* entity = new (memset(
        Memory::AllocGlobalHeap(sizeof(zUIFlashOnScreenText), (Memory::GlobalHeapEnum)0,
                                (eMemMgrTag)16, false),
        0, sizeof(zUIFlashOnScreenText))) zUIFlashOnScreenText(handle);

    entity->init(*(Sext::xBaseAsset*)asset);

    return entity;
}
