// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

namespace World { class IHackCinematicCallbackSink; }

namespace Graphics {

class Renderable3D {
public:
    void SetProjectShadowCast(void* value);

    unsigned char _pad0[0xCC];
    int fCC;
};

}  // namespace Graphics

namespace World {

class CinematicBlobEntity {
public:
    void Play();
    void RegisterCallback(World::IHackCinematicCallbackSink* value);

    unsigned char _pad0[0x1C];
    int f1C;
    unsigned char _pad1[0x80];
    int fA0;
};

}  // namespace World

namespace Animate {

class Interpolator {
public:
    float GetTime() const;
    void SetTime(float value);

    float f0;
};

}  // namespace Animate

namespace World {

class ComboAnimBlobEntity {
public:
    int GetV2() const;

    unsigned char _pad0[0x18];
    int f18;
};

}  // namespace World

namespace Graphics {

class Model {
public:
    unsigned short GetChildTransformCount() const;

    unsigned char _pad0[0x32];
    unsigned short f32;
};

}  // namespace Graphics

void Graphics::Renderable3D::SetProjectShadowCast(void* value) { fCC = (int)value; }
void World::CinematicBlobEntity::Play() { fA0 = 1; }
void World::CinematicBlobEntity::RegisterCallback(World::IHackCinematicCallbackSink* value) { f1C = (int)value; }
void Animate::Interpolator::SetTime(float value) { f0 = value; }
int World::ComboAnimBlobEntity::GetV2() const { return f18; }
float Animate::Interpolator::GetTime() const { return f0; }
unsigned short Graphics::Model::GetChildTransformCount() const { return f32; }
