// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here is one load or one store and a return. Each
// offset was decoded from the image and re-encoded back to the
// same bytes before being written. GENERATED, not read: real
// matched functions whose offsets are recovered fact, but a count
// of them is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each accessor touches are known, not the fields between.

namespace Graphics {

class Node {
public:
    unsigned char Attached() const;

    unsigned char _pad0[0x8];
    unsigned char f8;
};

}  // namespace Graphics

namespace Animate {

class Interpolator {
public:
    float GetTime() const;
    void SetTime(float value);

    float f0;
};

}  // namespace Animate

namespace World {

class ComboAnimBlobEntity {
public:
    int GetV2() const;

    unsigned char _pad0[0x18];
    int f18;
};

}  // namespace World

namespace Graphics {

class Model {
public:
    unsigned short GetChildTransformCount() const;

    unsigned char _pad0[0x32];
    unsigned short f32;
};

}  // namespace Graphics

unsigned char Graphics::Node::Attached() const { return f8; }
void Animate::Interpolator::SetTime(float value) { f0 = value; }
int World::ComboAnimBlobEntity::GetV2() const { return f18; }
float Animate::Interpolator::GetTime() const { return f0; }
unsigned short Graphics::Model::GetChildTransformCount() const { return f32; }
