// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.


class GRendererWiiImpl {
public:
    void FillStyleDisable();
    void LineStyleDisable();

    unsigned char _pad0[0x148];
    int f148;
    unsigned char _pad1[0x8];
    int f154;
    unsigned char _pad2[0x7C];
    int f1D4;
    unsigned char _pad3[0x8];
    int f1E0;
};


namespace Loader {

class DomainDirMemCB {
public:
    virtual void __vtable_anchor();
    DomainDirMemCB();

};

}  // namespace Loader

namespace TRC {

class WiiDVDErrorRunnable {
public:
    virtual void __vtable_anchor();
    WiiDVDErrorRunnable();

};

}  // namespace TRC

void GRendererWiiImpl::LineStyleDisable() { f1D4 = 0; f1E0 = 0; }
void GRendererWiiImpl::FillStyleDisable() { f148 = 0; f154 = 0; }
Loader::DomainDirMemCB::DomainDirMemCB() {}
TRC::WiiDVDErrorRunnable::WiiDVDErrorRunnable() {}
