// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

namespace World { class EntityHandleBase; }

namespace World {

class Entity {
public:
    Entity(World::EntityHandleBase* a0);
    virtual void __vtable_anchor();
};

}  // namespace World

namespace Graphics {

class Renderable3D {
public:
    void SetProjectShadowFlag(unsigned int value);

    unsigned char _pad0[0xF0];
    int fF0;
};

}  // namespace Graphics

namespace World {

class UVMovementInstanceData {
public:
    void SetRows(float* value);

    unsigned char _pad0[0x5C];
    int f5C;
};

}  // namespace World

namespace World {

class RenderCustomizerBaseEntity : public World::Entity {
public:
    virtual void __vtable_anchor();
    RenderCustomizerBaseEntity(World::EntityHandleBase* a0);

};

}  // namespace World

namespace World {

class UVMovementSettingsEntity {
public:
    unsigned int GetInstanceDataSize();

};

}  // namespace World

void Graphics::Renderable3D::SetProjectShadowFlag(unsigned int value) { fF0 = value; }
void World::UVMovementInstanceData::SetRows(float* value) { f5C = (int)value; }
World::RenderCustomizerBaseEntity::RenderCustomizerBaseEntity(World::EntityHandleBase* a0) : World::Entity(a0) {}
unsigned int World::UVMovementSettingsEntity::GetInstanceDataSize() { return 0x00000060u; }
