// GENERATED by tools/gen_accessors.py from the retail image.
// Do not hand-edit: regenerate.
//
// Every function here touches nothing but its own members or a
// constant: one load, one store, the address of a member, a
// constant return, or members set to one constant. Each body was
// decoded from the image and re-encoded back to the same bytes,
// and each parameter list re-mangled back to the same symbol,
// before being written. GENERATED, not read: real matched
// functions whose offsets are recovered fact, but a count of them
// is not a count of decompiled code.
//
// Members are non-virtual, and the padding is padding -- only the
// offsets each function touches are known, not the fields between.

namespace Math {

class Vector {
public:
    float* y();
    float y() const;
    int* z();

    unsigned char _pad0[0x4];
    float f4;
    int f8;
};

}  // namespace Math

namespace Math {

class Vector4 {
public:
    int* w();

    unsigned char _pad0[0xC];
    int fC;
};

}  // namespace Math

namespace Graphics {

class Viewport {
public:
    int* GetFrustumPlanes();
    unsigned char GetLodEnabled() const;
    unsigned char GetRendering() const;

    unsigned char _pad0[0x1C];
    unsigned char f1C;
    unsigned char f1D;
    unsigned char _pad2[0x1AE];
    int f1CC;
};

}  // namespace Graphics

namespace Graphics {

class LightPointSpot {
public:
    const int* GetColor() const;
    float GetProjectScale() const;

    unsigned char _pad0[0x18];
    float f18;
    int f1C;
};

}  // namespace Graphics

namespace Graphics {

class Geometry {
public:
    int GetEffect() const;

    unsigned char _pad0[0x4C];
    int f4C;
};

}  // namespace Graphics

namespace Graphics {

class Scene {
public:
    int GetRenderSceneCollider() const;

    unsigned char _pad0[0x40];
    int f40;
};

}  // namespace Graphics

namespace Graphics {

class TextureRenderTargetCommon {
public:
    int* GetTexture();
    int GetTextureHandle() const;

    unsigned char _pad0[0x14];
    int f14;
    unsigned char _pad1[0x8];
    int f20;
};

}  // namespace Graphics

namespace Graphics {

class Renderable3D {
public:
    void SetProjectShadowReceive(void* value);

    unsigned char _pad0[0xD0];
    int fD0;
};

}  // namespace Graphics

namespace Graphics {

class TextureRenderTargetWii {
public:
    int GetTextureHandle2() const;
    int GetTextureHandle3() const;
    int GetTextureHandle4() const;

    unsigned char _pad0[0x70];
    int f70;
    unsigned char _pad1[0x44];
    int fB8;
    unsigned char _pad2[0x44];
    int f100;
};

}  // namespace Graphics

float* Math::Vector::y() { return &f4; }
int* Math::Vector::z() { return &f8; }
float Math::Vector::y() const { return f4; }
int* Math::Vector4::w() { return &fC; }
int* Graphics::Viewport::GetFrustumPlanes() { return &f1CC; }
unsigned char Graphics::Viewport::GetLodEnabled() const { return f1C; }
float Graphics::LightPointSpot::GetProjectScale() const { return f18; }
const int* Graphics::LightPointSpot::GetColor() const { return &f1C; }
int Graphics::Geometry::GetEffect() const { return f4C; }
int Graphics::Scene::GetRenderSceneCollider() const { return f40; }
unsigned char Graphics::Viewport::GetRendering() const { return f1D; }
int* Graphics::TextureRenderTargetCommon::GetTexture() { return &f14; }
int Graphics::TextureRenderTargetCommon::GetTextureHandle() const { return f20; }
void Graphics::Renderable3D::SetProjectShadowReceive(void* value) { fD0 = (int)value; }
int Graphics::TextureRenderTargetWii::GetTextureHandle2() const { return f70; }
int Graphics::TextureRenderTargetWii::GetTextureHandle3() const { return fB8; }
int Graphics::TextureRenderTargetWii::GetTextureHandle4() const { return f100; }
