// GENERATED by tools/gen_poolprefix.py; regenerate, do not edit.
//
// MediaFile.cpp is a fragment of the unity translation unit WAD01.cpp.
// That unit's string pool (@stringBase0 at 0x806936E0, 1320 bytes)
// is filled in order of first appearance across every file it
// included, and a reference bakes the string's pool OFFSET into
// the instruction. The 57 strings below are the ones that come
// before this file's own, in that order, so that compiled alone
// it gets the same offsets. This is data read from the image;
// retail has no such table, it has the files in front.

static const char* const kUnityPoolPrefix[] = {
    "Options",  // +0
    "LockFramerate",  // +8
    "Error allocating display list (%d, %d)\n",  // +22
    "DynamicEnvMap.cpp",  // +62
    "Exiting",  // +80
    "postColorMultiplier",  // +88
    "colorMultiplier",  // +108
    "alphaMultiplier",  // +124
    "textureBlendFactor",  // +140
    "diffuseMap1",  // +159
    "specularMap1",  // +171
    "diffuseMap",  // +184
    "lightMap",  // +195
    "Bloom_Clamp",  // +204
    "Bloom",  // +216
    "BloomSampler",  // +222
    "DownScale2x2",  // +235
    "DownScale2x2Sampler",  // +248
    "BrightPassFilter",  // +268
    "BrightPassFilterSampler",  // +285
    "GaussBlur5x5_Clamp",  // +309
    "GaussBlur5x5",  // +328
    "GaussBlur5x5Sampler",  // +341
    "DoFDepthSampler",  // +361
    "DoFColorSampler",  // +377
    "DoFBlurSampler",  // +393
    "focusPoints",  // +408
    "SampleTexture",  // +420
    "BloomTexture",  // +434
    "HDRParams",  // +447
    "HDRShader",  // +457
    "ColorSampler",  // +467
    "BlurSampler",  // +480
    "viewportAspect",  // +492
    "blurAmt",  // +507
    "zoomAmt",  // +515
    "blurCenter",  // +523
    "blurScale",  // +534
    "bwBlendFactor",  // +544
    "TextureCopy",  // +558
    "TextureCopySampler",  // +570
    "avgSampleOffsets",  // +589
    "avgSampleWeights",  // +606
    "sampleClamp",  // +623
    "ScreenSampler",  // +635
    "DepthSampler",  // +649
    "BlurryScreenSampler",  // +662
    "LastMoBlurSampler",  // +682
    " ",  // +700
    "\n",  // +702
    "psColorMul",  // +704
    "D:\\%.30s%06u.bmp",  // +715
    "ConsolePad%d",  // +732
    "ConsolePadDeviceNativeWii.cpp",  // +745
    "Cannot allocate work area for KMPLS!\n",  // +775
    "%s%s",  // +813
    "%s%c%s",  // +818
};
