// GENERATED by tools/gen_poolprefix.py; regenerate, do not edit.
//
// CMeshBlobEntity.cpp is a fragment of the unity translation unit WAD00.cpp.
// That unit's string pool (@stringBase0 at 0x80692B78, 144 bytes)
// is filled in order of first appearance across every file it
// included, and a reference bakes the string's pool OFFSET into
// the instruction. The 14 strings below are the ones that come
// before this file's own, in that order, so that compiled alone
// it gets the same offsets. This is data read from the image;
// retail has no such table, it has the files in front.

static const char* const kUnityPoolPrefix[] = {
    "PSL",  // +0
    "",  // +4
    ", ",  // +5
    "",  // +8
    "FirstDomain",  // +9
    "quaternion",  // +21
    "shape",  // +32
    "DomainModule",  // +38
    "BootStrapModule",  // +51
    "MSTQueryModule",  // +67
    "LSPoolModule",  // +82
    "DynaMemModule",  // +95
    "CoordinatorModule",  // +109
    "BasicColorModule",  // +127
};
