// GENERATED by tools/gen_poolprefix.py; regenerate, do not edit.
//
// Quaternion.cpp is a fragment of the unity translation unit WAD02.cpp.
// That unit's string pool (@stringBase0 at 0x80694D50, 3452 bytes)
// is filled in order of first appearance across every file it
// included, and a reference bakes the string's pool OFFSET into
// the instruction. The 161 strings below are the ones that come
// before this file's own, in that order, so that compiled alone
// it gets the same offsets. This is data read from the image;
// retail has no such table, it has the files in front.

static const char* const kUnityPoolPrefix[] = {
    "CloudShader",  // +0
    "diffuseMap",  // +12
    "%s",  // +23
    "LFDevice",  // +26
    "%f : %f : %f : %f",  // +35
    "%s%c%s",  // +53
    "***MEMORY USAGE***\n\n",  // +60
    "*** %-24s\t%12ld B ***\n",  // +81
    "\n",  // +104
    "\n*** %-24s\t%12ld B ***\n\n",  // +106
    "-----------------------------------------------------\n",  // +131
    "FACTORY STATS:\n",  // +186
    "Total Mem..: %d (%dKB)\n",  // +202
    "Used Mem...: %d (%dKB)\n",  // +226
    "Free Mem...: %d (%dKB)\n\n",  // +250
    "Total Pages Num..: %d\n",  // +275
    "Used Pages Num...: %d\n",  // +298
    "Free Pages Num...: %d\n\n",  // +321
    "Page Format%d: blockSize: %5d,\t blocksUsed: %5d,\t TotalUsedMem: %8d\n",  // +345
    "simworld_%s_%02d.hkx",  // +414
    "mainworld_%s_%02d.hkx",  // +435
    "",  // +457
    "tga",  // +458
    "Scaleform out of memory!!\n",  // +462
    "Size: %d  Align: %d\n",  // +489
    "$font_bodyText",  // +510
    "$font_displayNumbers",  // +525
    "$font_displayText",  // +546
    "_root.driver.profileDetected",  // +564
    "_root.driver.storageDeviceDetected",  // +593
    "_root.driver.playerWithControl",  // +628
    "_root.driver.autosavingStart",  // +659
    "_root.driver.autosavingStop",  // +688
    "_root.driver.talkboxOn",  // +716
    "_root.driver.talkboxOff",  // +739
    "_root.driver.talkboxExpand",  // +763
    "_root.driver.talkboxRetract",  // +790
    "_root.driver.talkboxString",  // +818
    "_root.driver.talkboxStringUpdate",  // +845
    "_root.driver.talkboxType",  // +878
    "_root.driver.tutorialAnimationsNum",  // +903
    "_root.driver.currentCounterNum",  // +938
    "_root.driver.currentCounterChanged",  // +969
    "_root.driver.totalCounterNum",  // +1004
    "_root.driver.totalCounterChanged",  // +1033
    "_root.driver.timerMinutes",  // +1066
    "_root.driver.currentTimeChanged",  // +1092
    "_root.driver.timerSeconds",  // +1124
    "_root.driver.movieFinished",  // +1150
    "_root.driver.movieCancelled",  // +1177
    "_root.driver.setSavedDataDetected",  // +1205
    "_root.driver.initialize",  // +1239
    "_level0.subMenu.driver.DisableMP",  // +1263
    "CoreJobProcessor",  // +1296
    "UnknownGame",  // +1313
    "-server=",  // +1325
    "-path=",  // +1334
    "SoundCallback: %d, %d\n",  // +1341
    "/homeBtn.arc",  // +1364
    "/homeBtn_ENG.arc",  // +1377
    "/homeBtn_GER.arc",  // +1394
    "/homeBtn_FRA.arc",  // +1411
    "/homeBtn_SPA.arc",  // +1428
    "/homeBtn_ITA.arc",  // +1445
    "/homeBtn_NED.arc",  // +1462
    "/homeBtn_CHN.arc",  // +1479
    "/homeBtn_KOR.arc",  // +1496
    "/SpeakerSe.arc",  // +1513
    "/home.csv",  // +1528
    "/config.txt",  // +1538
    "/HomeButtonSe.arc",  // +1550
    "Select Btn:%d\n",  // +1568
    "Reassigned:%d\n",  // +1583
    "Return to WiiMenu.\n",  // +1598
    "Reset.\n",  // +1618
    "Total Memory Used by HomeMenu: %d bytes\n",  // +1626
    "boot.ini",  // +1667
    ".",  // +1676
    "domainUID.dir",  // +1678
    "Game.HE",  // +1692
    "BAD_MESSAGE Unknown error.  You should never see this.  BAD_MESSAGE",  // +1700
    "WiiDVDError",  // +1768
    "OSRestart called!\n",  // +1780
    "OSReturnToMenu called!\n",  // +1799
    "OSReturnToDataManager called!\n",  // +1823
    "OSShutdownSystem called!\n",  // +1854
    "=UI_TXT_RECONNECT_CONTROLLER_1",  // +1880
    "=UI_TXT_RECONNECT_CONTROLLER_2",  // +1911
    "=UI_TXT_RECONNECT_CONTROLLER_3",  // +1942
    "=UI_TXT_RECONNECT_CONTROLLER_4",  // +1973
    "=UI_TXT_RECONNECT_NUNCHUK_1",  // +2004
    "=UI_TXT_RECONNECT_NUNCHUK_2",  // +2032
    "=UI_TXT_RECONNECT_NUNCHUK_3",  // +2060
    "=UI_TXT_RECONNECT_NUNCHUK_4",  // +2088
    "=UI_TXT_RECONNECT_CLASSIC_1",  // +2116
    "=UI_TXT_RECONNECT_CLASSIC_2",  // +2144
    "=UI_TXT_RECONNECT_CLASSIC_3",  // +2172
    "=UI_TXT_RECONNECT_CLASSIC_4",  // +2200
    "defaultx.sav",  // +2228
    "%s/%s",  // +2241
    "%s/%s%d.%s",  // +2247
    "default",  // +2258
    "sav",  // +2266
    "%s/banner.bin",  // +2270
    "garbage.sav",  // +2284
    "NAND_RESULT_AUTHENTICATION\n",  // +2296
    "NAND_RESULT_CORRUPT\n",  // +2324
    "NAND_RESULT_ECC_CRIT\n",  // +2345
    "NAND_RESULT_ALLOC_FAILED\n",  // +2367
    "NAND_RESULT_BUSY\n",  // +2393
    "NAND_RESULT_MAXBLOCKS\n",  // +2411
    "NAND_RESULT_MAXFILES\n",  // +2434
    "NAND_RESULT_UNKNOWN\n",  // +2456
    "NAND_RESULT_ACCESS\n",  // +2477
    "NAND_RESULT_EXISTS\n",  // +2497
    "NAND_RESULT_INVALID\n",  // +2517
    "NAND_RESULT_MAXDEPTH\n",  // +2538
    "NAND_RESULT_MAXFD\n",  // +2560
    "NAND_RESULT_NOEXISTS\n",  // +2579
    "NAND_RESULT_NOTEMPTY\n",  // +2601
    "NAND_RESULT_OPENFD\n",  // +2623
    "NAND_RESULT_FATAL_ERROR\n",  // +2643
    "Result: %d\n",  // +2668
    "NAND Failed somewhere\n",  // +2680
    "Save data CRC mismatch. 0x%08X (Header) != 0x%08X (Data)\n",  // +2703
    "=MNUI_SAVELOAD_WII_NAND02",  // +2761
    "=MNUS_SAVELOAD_WII_CONTINUE",  // +2787
    "=MNUS_SAVELOAD_WII_MENU",  // +2815
    "=MNUI_SAVELOAD_WII_NAND03",  // +2839
    "=MNUI_SAVELOAD_WII_NAND05",  // +2865
    "=MNUS_NAVHELP_ACCEPT",  // +2891
    "=MNUI_SAVELOAD_WII_NAND06",  // +2912
    "=UI_TXT_DATA_CORRUPT",  // +2938
    "=UI_TXT_DAMAGE_MC",  // +2959
    "=UI_TXT_CORRUPT_DATA",  // +2977
    "=MNUI_SAVELOAD_WII_NAND08",  // +2998
    "=MNUI_SAVELOAD_WII_NAND11",  // +3024
    "Save data CRC 0x%X\n",  // +3050
    "Graphics::SceneGraphModule",  // +3070
    "ScreenWarpManager",  // +3097
    "IO::LFDeviceModule",  // +3115
    "MathModule",  // +3134
    "Memory::AllocModule",  // +3145
    "PhysicsModule",  // +3165
    "0x15bf4376:CLIENT.Ph.HeavyIron_THQ_SpongeBobFY2010",  // +3179
    "HavokModule",  // +3230
    "ScaleformModule",  // +3242
    "CoreTasking.cpp",  // +3258
    "System::GameWindowModule",  // +3274
    "HomeMenuModule",  // +3299
    "Tasking.cpp",  // +3314
    "Time.cpp",  // +3326
    "Test::TestSuite",  // +3335
    "TRCModule",  // +3351
    "Font.cpp",  // +3361
    "UtilModule",  // +3370
    "CinematicModule",  // +3381
    "EntityModule",  // +3397
    "EntityMgrModule",  // +3410
    "WorldModule",  // +3426
    "GlobalsModule",  // +3438
};
