"""Write tools/gen_accessors.py's output for every unit that has any.

    python tools/gen_units.py [--dry-run]

The shapes gen_accessors covers are spread thin -- 93 functions across 47
units at the time this was written, most of them one or two per unit -- so
doing it by hand is both slow and the kind of slow that quietly stops after
the big ones. This walks the whole population.

It will only ever overwrite a file that says gen_accessors generated it.
A hand-written unit, or one gen_typeids owns, is left alone and REPORTED:
those need merging rather than replacing, and a merge that silently deleted
the other tool's functions is exactly the failure this refuses to have.
"""

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import gen_accessors as A                                # noqa: E402

# Both banners: gen_accessors now emits the constant-return shape too, so
# it owns the files gen_typeids wrote before it could. See gen_typeids.py.
BANNER = "// GENERATED by tools/gen_accessors.py"
BANNERS = (BANNER, "// GENERATED by tools/gen_typeids.py")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    raw, base, foff, ranges = A.load_image()
    game, _matched = A.from_report("gen_units")
    syms = A.symbols()

    wrote = held = 0
    fns = 0
    blocked, withdrawn = [], []
    for unit, rs in ranges:
        if unit not in game:
            continue
        good = []
        for lo, hi in rs:
            g, _s = A.candidates(raw, base, foff, syms, lo, hi)
            good += g

        dst = ROOT / "src" / unit
        if not good:
            # No candidates now. A file this tool wrote on an earlier run is
            # then STALE and has to go: leaving it there builds an answer the
            # generator has since withdrawn, and nothing would say so.
            if dst.exists():
                head = dst.read_text(encoding="utf-8", errors="ignore")[:200]
                if any(b in head for b in BANNERS) and not args.dry_run:
                    dst.unlink()
                    withdrawn.append(unit)
            continue

        if dst.exists():
            body = dst.read_text(encoding="utf-8", errors="ignore")
            # An EMPTY file is a placeholder, not somebody's work: the unit
            # exists in configure.py and compiles to an object defining
            # nothing. Filling it in loses nothing and is reported anyway.
            if body.strip() and not any(b in body[:200] for b in BANNERS):
                blocked.append((unit, len(good),
                                "written by hand or by another generator"))
                held += 1
                continue
            if not body.strip():
                print("  (filling in an empty placeholder: %s)" % unit)
        if args.dry_run:
            print("  would write %-52s %d function(s)" % (unit, len(good)))
            wrote += 1
            fns += len(good)
            continue

        r = subprocess.run([sys.executable, "tools/gen_accessors.py",
                            "--unit", unit, str(dst)],
                           cwd=str(ROOT), capture_output=True, text=True)
        if r.returncode:
            why = (r.stdout + r.stderr).strip().splitlines()[-1]
            # A file this tool wrote on an earlier run, whose candidates the
            # generator now refuses, is STALE: leaving it there builds
            # yesterday's answer and the failure looks like someone else's.
            head = dst.read_text(encoding="utf-8",
                                 errors="ignore")[:200] if dst.exists() else ""
            if any(b in head for b in BANNERS):
                dst.unlink()
                why += " (removed the stale generated file)"
            blocked.append((unit, len(good), why))
            held += 1
            continue
        print("  %s" % r.stdout.strip().splitlines()[0].strip())
        wrote += 1
        fns += len(good)

    print("")
    print("  %d unit(s) written, %d function(s); %d unit(s) held back, "
          "%d withdrawn" % (wrote, fns, held, len(withdrawn)))
    for unit in withdrawn:
        print("    withdrew %-52s no candidate survives now" % unit)
    for unit, n, why in blocked:
        print("    held %-52s %2d function(s): %s" % (unit, n, why))
    if not wrote:
        sys.exit("gen_units: nothing was written -- that is a failure to "
                 "report, not a result")
    return 0


if __name__ == "__main__":
    sys.exit(main())
