"""Bring tools/unitcmp_check.py's EXPECT pins up to what is MEASURED now.

    python tools/unitcmp_pins.py [--dry-run]

Every pin in EXPECT is a (byte-identical, defined) pair, and a pin exists
so that a unit which quietly starts matching FEWER functions is a failure.
Generating a new shape into a unit that already had one raises the honest
answer, and then twenty pins fail for the right reason and have to be
re-measured. Doing that by hand is how a pin gets lowered by accident.

So this refuses to LOWER a pin. A unit that now matches fewer functions
than its pin says is reported and left alone: that is a regression to look
at, not a number to update. A pin whose two halves differ on purpose --
xOGModelRefPtr at 3 of 4, keycode.cxx at 0 of 1 -- is only touched when
the measurement is BETTER than the pin, which is exactly the event those
pins exist to catch.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHECK = ROOT / "tools/unitcmp_check.py"
BANNERS = ("// GENERATED by tools/gen_accessors.py",
           "// GENERATED by tools/gen_typeids.py")
NL = chr(10)

sys.path.insert(0, str(ROOT / "tools"))
import unitcmp_check as C                                 # noqa: E402


def measure(unit):
    r = subprocess.run([sys.executable, "tools/unitcmp.py", unit],
                       cwd=str(ROOT), capture_output=True, text=True)
    m = re.search(r"(\d+) of (\d+) function\(s\) defined by the object are "
                  r"byte-identical", r.stdout)
    if not m:
        return None
    return int(m.group(1)), int(m.group(2))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    units = set(C.EXPECT)
    for src in sorted((ROOT / "src").rglob("*.cpp")):
        head = src.read_text(encoding="utf-8", errors="ignore")[:200]
        if any(b in head for b in BANNERS):
            units.add(str(src.relative_to(ROOT / "src"))
                      .replace(chr(92), "/")[:-4])

    raised, added, same, refused, unmeasured, gone = [], [], 0, [], [], []
    new = {}
    for unit in sorted(units):
        # A pin for a unit whose source no longer exists is not a lowered
        # pin, it is a deleted one -- the generator withdrew the file. Said
        # out loud rather than left to fail as "no answer".
        if not any((ROOT / "src" / (unit + ext)).exists()
                   for ext in ("", ".cpp", ".cxx", ".c")):
            gone.append(unit)
            continue
        got = measure(unit)
        if got is None:
            unmeasured.append(unit)
            continue
        old = C.EXPECT.get(unit)
        if old is None:
            added.append((unit, got))
            new[unit] = got
        elif got == old:
            same += 1
            new[unit] = old
        elif got[0] < old[0] or got[1] < old[1]:
            refused.append((unit, old, got))
            new[unit] = old
        else:
            raised.append((unit, old, got))
            new[unit] = got

    print("  %d pin(s) unchanged, %d raised, %d added, %d removed, "
          "%d refused, %d not measured"
          % (same, len(raised), len(added), len(gone), len(refused),
             len(unmeasured)))
    for unit in gone:
        print("    removed  %-52s its source no longer exists" % unit)
    for unit, old, got in raised:
        print("    raised   %-52s %s -> %s" % (unit, old, got))
    for unit, got in added:
        print("    added    %-52s %s" % (unit, got))
    for unit, old, got in refused:
        print("    REFUSED  %-52s pinned %s, measured %s -- a pin is not "
              "lowered here" % (unit, old, got))
    for unit in unmeasured:
        print("    no answer %-51s unitcmp printed no count" % unit)

    if refused:
        return 1
    if not raised and not added and not gone:
        print("  nothing to write")
        return 0
    if args.dry_run:
        return 0

    text = CHECK.read_text(encoding="utf-8")
    for unit in gone:
        pat = re.compile('^[ ]*"%s": [(][^)]*[)],' % re.escape(unit) + NL,
                         re.M)
        text, n = pat.subn("", text)
        if n != 1:
            sys.exit("unitcmp_pins: %r appears %d times in EXPECT, not once"
                     % (unit, n))
    for unit, _old, got in raised:
        pat = re.compile(r'^(\s*"%s": )\([^)]*\),$' % re.escape(unit), re.M)
        text, n = pat.subn(lambda m: "%s(%d, %d)," % (m.group(1), got[0],
                                                      got[1]), text)
        if n != 1:
            sys.exit("unitcmp_pins: %r appears %d times in EXPECT, not once"
                     % (unit, n))
    if added:
        anchor = "}" + NL + NL + NL + "def main():"
        if text.count(anchor) != 1:
            sys.exit("unitcmp_pins: cannot find the end of EXPECT")
        block = (NL.join('    "%s": (%d, %d),' % (u, g[0], g[1])
                         for u, g in added) + NL + anchor)
        text = text.replace(anchor, block)
    CHECK.write_text(text, encoding="utf-8")
    print("  wrote %d change(s) to %s"
          % (len(raised) + len(added) + len(gone), CHECK.relative_to(ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
