// GENERATED by tools/transplant.py from a matched twin.
// Do not hand-edit: re-emit, or take the file over and remove this
// banner -- written_vs_generated.py splits on it.
//
// xCamTransition, transplanted from
// Create__Q24Sext11xGroupAssetFPQ25World16EntityHandleBasePQ24Sext11xGroupAsset,
// which is matched. The shapes are identical instruction for
// instruction; the holes were 4, and every one of them is
// read from the retail image rather than guessed:
//
//   +0x020  li      r3,88
//   +0x030  li      r5,88
//   +0x050  addi    r3,r3,18936  = 806B49F8  __vt__14xCamTransition
//   +0x060  bl        -> Init__14xCamTransitionFRCQ24Sext15transition_time
//
// The DWARF places this function in xCamTransition.cpp.

enum eMemMgrTag { eMemMgrTag_ = 0x7FFFFFFF };

namespace Memory {
enum GlobalHeapEnum { GlobalHeapEnum_ = 0x7FFFFFFF };

void* AllocGlobalHeap(unsigned long size, GlobalHeapEnum heap, eMemMgrTag tag,
                      bool clear);
}  // namespace Memory

extern "C" {
void* memset(void* dst, int c, unsigned long n);
}

inline void* operator new(unsigned long, void* p) { return p; }

namespace World {
class EntityHandleBase;
}

class xCamTransition;


// 0x38, and polymorphic: the vtable pointer the constructor stores
// sits at +0, so nothing precedes it.
class xBase {
public:
    virtual void _v0();

    unsigned char _pad0[0x34 - 0x4];
};

namespace World {

class xOGEntity : public xBase {
public:
    xOGEntity(EntityHandleBase* handle);

    unsigned char _pad0[0x40 - 0x34];
};

}  // namespace World

namespace Sext {

class transition_time {
public:
    static xCamTransition* Create(World::EntityHandleBase* handle,
                                  transition_time* asset);
};

}  // namespace Sext

class xCamTransition : public World::xOGEntity {
public:
    xCamTransition(World::EntityHandleBase* handle) : World::xOGEntity(handle) {}

    virtual void _v0();


    void Init(const Sext::transition_time& asset);

    unsigned char _pad0[0x58 - 0x40];
};

xCamTransition* Sext::transition_time::Create(World::EntityHandleBase* handle,
                                              transition_time* asset) {
    xCamTransition* entity = new (memset(
        Memory::AllocGlobalHeap(sizeof(xCamTransition), (Memory::GlobalHeapEnum)0,
                                (eMemMgrTag)16, false),
        0, sizeof(xCamTransition))) xCamTransition(handle);

    entity->Init(*(const Sext::transition_time*)asset);

    return entity;
}
