// xGroup.cpp -- read from the image with tools/disasm.py.
//
// The asset's Create is the shape eight other Sext assets in this tree
// already have: take one block of sizeof(T) from the global heap (heap
// 0, tag 16, no clear), memset it, place the entity on it, and run the
// asset's init. It was found by clustering every game function on its
// instruction skeleton -- opcodes and registers, with only the
// address-forming immediates blanked -- and noticing that this one sits
// in a cluster with seven already written. What differs between the
// members is the type, its size, and which init runs.
//
// Only the sizes are recovered fact here: xOGEntity is 0x40 and xGroup
// 0x50, the item count is the int at +0x44, and the vtable pointer is at
// +0 because that is where the constructor stores it. The members
// between are padding.
//
// GetNumItems below was generated by tools/gen_accessors.py before this
// file was written by hand; it is kept, unchanged but for the member's
// name.

enum eMemMgrTag { eMemMgrTag_ = 0x7FFFFFFF };

namespace Memory {
enum GlobalHeapEnum { GlobalHeapEnum_ = 0x7FFFFFFF };

void* AllocGlobalHeap(unsigned long size, GlobalHeapEnum heap, eMemMgrTag tag,
                      bool clear);
}  // namespace Memory

extern "C" {
void* memset(void* dst, int c, unsigned long n);
}

inline void* operator new(unsigned long, void* p) { return p; }

namespace World {
class EntityHandleBase;
}

class xGroup;

// 0x38, and polymorphic: the vtable pointer the constructor stores sits
// at +0, so nothing precedes it.
class xBase {
public:
    virtual void _v0();

    unsigned char _pad0[0x34 - 0x4];
};

namespace World {

class xOGEntity : public xBase {
public:
    xOGEntity(EntityHandleBase* handle);

    unsigned char _pad0[0x40 - 0x34];
};

}  // namespace World

namespace Sext {

class xGroupAsset {
public:
    static xGroup* Create(World::EntityHandleBase* handle,
                          xGroupAsset* asset);
};

}  // namespace Sext

class xGroup : public World::xOGEntity {
public:
    xGroup(World::EntityHandleBase* handle) : World::xOGEntity(handle) {}

    virtual void _v0();

    void Init(Sext::xGroupAsset* asset);
    int GetNumItems();

    unsigned char _pad0[0x44 - 0x40];
    int itemCount;
    unsigned char _pad1[0x50 - 0x48];
};

xGroup* Sext::xGroupAsset::Create(World::EntityHandleBase* handle,
                                  xGroupAsset* asset) {
    xGroup* group = new (memset(
        Memory::AllocGlobalHeap(sizeof(xGroup), (Memory::GlobalHeapEnum)0,
                                (eMemMgrTag)16, false),
        0, sizeof(xGroup))) xGroup(handle);

    group->Init(asset);

    return group;
}

int xGroup::GetNumItems() { return itemCount; }
