// GENERATED by tools/transplant.py from a matched twin.
// Do not hand-edit: re-emit, or take the file over and remove this
// banner -- written_vs_generated.py splits on it.
//
// xMovePoint, transplanted from
// Create__Q24Sext11xGroupAssetFPQ25World16EntityHandleBasePQ24Sext11xGroupAsset,
// which is matched. The shapes are identical instruction for
// instruction; the holes were 3, and every one of them is
// read from the retail image rather than guessed:
//
//   +0x020  li      r3,120
//   +0x030  li      r5,120
//   +0x050  addi    r3,r3,18280  = 806B4768  __vt__10xMovePoint
//
// The DWARF places this function in xMovePoint.cpp.

enum eMemMgrTag { eMemMgrTag_ = 0x7FFFFFFF };

namespace Memory {
enum GlobalHeapEnum { GlobalHeapEnum_ = 0x7FFFFFFF };

void* AllocGlobalHeap(unsigned long size, GlobalHeapEnum heap, eMemMgrTag tag,
                      bool clear);
}  // namespace Memory

extern "C" {
void* memset(void* dst, int c, unsigned long n);
}

inline void* operator new(unsigned long, void* p) { return p; }

namespace World {
class EntityHandleBase;
}

class xMovePoint;


// 0x38, and polymorphic: the vtable pointer the constructor stores
// sits at +0, so nothing precedes it.
class xBase {
public:
    virtual void _v0();

    unsigned char _pad0[0x34 - 0x4];
};

namespace World {

class xOGEntity : public xBase {
public:
    xOGEntity(EntityHandleBase* handle);

    unsigned char _pad0[0x40 - 0x34];
};

}  // namespace World

namespace Sext {

class xMovePointAsset {
public:
    static xMovePoint* Create(World::EntityHandleBase* handle,
                              xMovePointAsset* asset);
};

}  // namespace Sext

class xMovePoint : public World::xOGEntity {
public:
    xMovePoint(World::EntityHandleBase* handle) : World::xOGEntity(handle) {}

    virtual void _v0();


    void Init(Sext::xMovePointAsset* asset);

    unsigned char _pad0[0x78 - 0x40];
};

xMovePoint* Sext::xMovePointAsset::Create(World::EntityHandleBase* handle,
                                          xMovePointAsset* asset) {
    xMovePoint* entity = new (memset(
        Memory::AllocGlobalHeap(sizeof(xMovePoint), (Memory::GlobalHeapEnum)0,
                                (eMemMgrTag)16, false),
        0, sizeof(xMovePoint))) xMovePoint(handle);

    entity->Init((Sext::xMovePointAsset*)asset);

    return entity;
}
