// GENERATED by tools/transplant.py from a matched twin.
// Do not hand-edit: re-emit, or take the file over and remove this
// banner -- written_vs_generated.py splits on it.
//
// xScreenFade, transplanted from
// Create__Q24Sext11xGroupAssetFPQ25World16EntityHandleBasePQ24Sext11xGroupAsset,
// which is matched. The shapes are identical instruction for
// instruction; the holes were 4, and every one of them is
// read from the retail image rather than guessed:
//
//   +0x020  li      r3,88
//   +0x030  li      r5,88
//   +0x050  addi    r3,r3,17344  = 806B43C0  __vt__11xScreenFade
//   +0x060  bl        -> load__11xScreenFadeFRQ211xScreenFade10asset_type
//
// The DWARF places this function in xScreenFade.cpp.

enum eMemMgrTag { eMemMgrTag_ = 0x7FFFFFFF };

namespace Memory {
enum GlobalHeapEnum { GlobalHeapEnum_ = 0x7FFFFFFF };

void* AllocGlobalHeap(unsigned long size, GlobalHeapEnum heap, eMemMgrTag tag,
                      bool clear);
}  // namespace Memory

extern "C" {
void* memset(void* dst, int c, unsigned long n);
}

inline void* operator new(unsigned long, void* p) { return p; }

namespace World {
class EntityHandleBase;
}

class xScreenFade;


// 0x38, and polymorphic: the vtable pointer the constructor stores
// sits at +0, so nothing precedes it.
class xBase {
public:
    virtual void _v0();

    unsigned char _pad0[0x34 - 0x4];
};

namespace World {

class xOGEntity : public xBase {
public:
    xOGEntity(EntityHandleBase* handle);

    unsigned char _pad0[0x40 - 0x34];
};

}  // namespace World

namespace Sext {

class ScreenFade {
public:
    static xScreenFade* Create(World::EntityHandleBase* handle,
                               ScreenFade* asset);
};

}  // namespace Sext

class xScreenFade : public World::xOGEntity {
public:
    xScreenFade(World::EntityHandleBase* handle) : World::xOGEntity(handle) {}

    virtual void _v0();

    class asset_type;

    void load(asset_type& asset);

    unsigned char _pad0[0x58 - 0x40];
};

xScreenFade* Sext::ScreenFade::Create(World::EntityHandleBase* handle,
                                      ScreenFade* asset) {
    xScreenFade* entity = new (memset(
        Memory::AllocGlobalHeap(sizeof(xScreenFade), (Memory::GlobalHeapEnum)0,
                                (eMemMgrTag)16, false),
        0, sizeof(xScreenFade))) xScreenFade(handle);

    entity->load(*(xScreenFade::asset_type*)asset);

    return entity;
}
