// Sext::FixWmlType -- one function, 11,944 bytes, and the whole unit.
//
// GENERATED by tools/gen_wmltypes.py; edit that, not this.
//
// The case table is DATA, read out of the image. Each
// compared value is resolved along the control-flow path
// that reaches it, because mwcc hoists a `lis` into r6/r7
// and shares it across a subtree, so the textually nearest
// one need not be the one that executed.
//
// Two cases carry no equality test: their subtree had
// narrowed to one candidate and mwcc proved it with a pair
// of range tests. Three more run nothing, and are written
// `return;` rather than left empty, because mwcc DELETES a
// case whose body is empty and deleting it moves the median
// of the whole search.
//
// The classes below are STUBS: each carries the method the
// call needs to name, and nothing else about it is known.

namespace Sext {
class ActionNode { public: void Fix(long); };
class AnimList { public: void Fix(long); };
class AnimPackage { public: void Fix(long); };
class AnimationSet { public: void Fix(long); };
class BSP { public: void Fix(long); };
class BehaviorSet { public: void Fix(long); };
class BehaviorTree { public: void Fix(long); };
class Button_Masher_Widget { public: void Fix(long); };
class BuyScreen { public: void Fix(long); };
class CarlLedgeHoist { public: void Fix(long); };
class CharacterAssets { public: void Fix(long); };
class Clip { public: void Fix(long); };
class ConditionNode { public: void Fix(long); };
class Curve { public: void Fix(long); };
class CurveCamera { public: void Fix(long); };
class DTRMovieSettings { public: long mOffset; void Fix(long l) { mOffset += l; } };
class Decal { public: void Fix(long); };
class DecoratorNode { public: void Fix(long); };
class DestructibleAsset { public: void Fix(long); };
class ElectricArcAsset { public: void Fix(long); };
class ElectricPointAsset { public: void Fix(long); };
class ExplosiveProperties { public: void Fix(long); };
class FXObjectSystem { public: void Fix(long); };
class FXParticleSystem { public: void Fix(long); };
class FXSpawn { public: void Fix(long); };
class Flythrough { public: void Fix(long); };
class Function_Generator { public: void Fix(long); };
class GradientCurve { public: void Fix(long); };
class HudUp { public: void Fix(long); };
class InputMappingAsset { public: void Fix(long); };
class LaserAsset { public: void Fix(long); };
class Ledge { public: void Fix(long); };
class LensFlareSpawnPt { public: void Fix(long); };
class LightAsset { public: void Fix(long); };
class LoadingScreen { public: void Fix(long); };
class NPCAsset { public: void Fix(long); };
class NPCGroupAsset { public: void Fix(long); };
class NPCPerceptionAsset { public: void Fix(long); };
class NPC_Action_MovementData { public: void Fix(long); };
class NPC_Combat { public: void Fix(long); };
class ParticleSink { public: void Fix(long); };
class PhysicsDataStruct { public: void Fix(long); };
class PlayerAICommand { public: void Fix(long); };
class PlayerAICommandGroup { public: void Fix(long); };
class PlayerAnimSeq { public: void Fix(long); };
class Player_Location_Ent_Connector { public: void Fix(long); };
class Pointer { public: void Fix(long); };
class ProjectileAsset { public: void Fix(long); };
class Ribbon { public: void Fix(long); };
class RuntimeEntityAsset { public: void Fix(long); };
class Scene { public: void Fix(long); };
class ScreenFade { public: void Fix(long); };
class Script { public: void Fix(long); };
class SelectorNode { public: void Fix(long); };
class ShrapnelAssetDef { public: void Fix(long); };
class SoundBankSource { public: void Fix(long); };
class Springboard { public: void Fix(long); };
class SurfaceGamePlay { public: void Fix(long); };
class TargetList { public: void Fix(long); };
class TikiScreen { public: void Fix(long); };
class TriggerEntityAsset { public: void Fix(long); };
class TriggerPhantomAsset { public: void Fix(long); };
class UI_Box { public: void Fix(long); };
class UI_Controller { public: void Fix(long); };
class UI_Group { public: void Fix(long); };
class UI_Image { public: void Fix(long); };
class UI_Model { public: void Fix(long); };
class UI_Text { public: void Fix(long); };
class UI_User_String { public: void Fix(long); };
class VehicleConfiguration { public: void Fix(long); };
class Whatever2 { public: void Fix(long); };
class binary_poi { public: void Fix(long); };
class text_box { public: void Fix(long); };
class xBaseAsset { public: void CustomFix(long); };
class xCamAsset { public: void Fix(long); };
class xCounterAsset { public: void Fix(long); };
class xEntPlayerAsset { public: void Fix(long); };
class xEnvAsset { public: void Fix(long); };
class xMovePointAsset { public: void Fix(long); };
class xPlatformAsset { public: void Fix(long); };
class xPortalAsset { public: void Fix(long); };
class xSimpleObjAsset { public: void Fix(long); };
class xSubtitlesAsset { public: void Fix(long); };
class xTimerAsset { public: void Fix(long); };
class zBranchSwitchAsset { public: void Fix(long); };
class zBreakawayPlatformAsset { public: void Fix(long); };
class zBugSpawnerAsset { public: void Fix(long); };
class zBungeeBallAsset { public: void Fix(long); };
class zCaveWormAsset { public: void Fix(long); };
class zCheckpointAsset { public: void Fix(long); };
class zCinematicAsset { public: void Fix(long); };
class zCondAsset { public: void Fix(long); };
class zCrankAsset { public: void Fix(long); };
class zCurrentAsset { public: void Fix(long); };
class zDirectionAsset { public: void Fix(long); };
class zDispatcherAsset { public: void Fix(long); };
class zDogPackAsset { public: void Fix(long); };
class zDragRopeAsset { public: void Fix(long); };
class zDugLeverAsset { public: void Fix(long); };
class zEventSpyAsset { public: void Fix(long); };
class zFloatingCollectibleAsset { public: void Fix(long); };
class zFloatingCollectibleSpawnerAsset { public: void Fix(long); };
class zFountainAsset { public: void Fix(long); };
class zGeyserAsset { public: void Fix(long); };
class zHammerAsset { public: void Fix(long); };
class zHintSphereAsset { public: void Fix(long); };
class zHitButtonAsset { public: void Fix(long); };
class zHouseBalloonBounceAsset { public: void Fix(long); };
class zHouseFloatAsset { public: void Fix(long); };
class zInWorldIconWidgetAsset { public: void Fix(long); };
class zInflatablePlatformAsset { public: void Fix(long); };
class zInteractRopeTieAsset { public: void Fix(long); };
class zInteractiveMusicAsset { public: void Fix(long); };
class zKevinSpringboardAsset { public: void Fix(long); };
class zLedgeShimmyAsset { public: void Fix(long); };
class zLeverAsset { public: void Fix(long); };
class zMG2PCamAsset { public: void Fix(long); };
class zManEatingPlantAsset { public: void Fix(long); };
class zPOWGroupAsset { public: void Fix(long); };
class zPOWObjectAsset { public: void Fix(long); };
class zPolygonalVolumeAsset { public: void Fix(long); };
class zPryAsset { public: void Fix(long); };
class zPuckReflectorAsset { public: void Fix(long); };
class zPushPullAsset { public: void Fix(long); };
class zRandomModelListAsset { public: void Fix(long); };
class zRopeCutAsset { public: void Fix(long); };
class zRubberBandAsset { public: void Fix(long); };
class zRussellRopeAsset { public: void Fix(long); };
class zSaveLoadAsset { public: void Fix(long); };
class zSinkingSurfaceAsset { public: void Fix(long); };
class zSlopeAsset { public: void Fix(long); };
class zSniffAsset { public: void Fix(long); };
class zSoundMaskAsset { public: void Fix(long); };
class zSoundWiimoteSpeakerListAsset { public: void Fix(long); };
class zSoundsNamedAsset { public: void Fix(long); };
class zSpinnerAsset { public: void Fix(long); };
class zSwingVineAsset { public: void Fix(long); };
class zTacticalCommanderAsset { public: void Fix(long); };
class zTikiAsset { public: void Fix(long); };
class zTrampolineAsset { public: void Fix(long); };
class zTrapAsset { public: void Fix(long); };
class zUIFlashOnScreenTextAsset { public: void Fix(long); };
class zUIHintBoxAsset { public: void Fix(long); };
class zUpFloatingBridgeAsset { public: void Fix(long); };
class zUpQuestCardAsset { public: void Fix(long); };
class zWaterAsset { public: void Fix(long); };
class zWaterWheelAsset { public: void Fix(long); };
class zWhirlpoolAsset { public: void Fix(long); };
}  // namespace Sext

namespace Sext {
namespace LinkAssetBaseNew {
class __srcEvent__ { public: void Fix(long); };
}  // namespace LinkAssetBaseNew
}  // namespace Sext

namespace World {
class ImmediateInstanceAsset { public: void Fix(long); };
class ModelInstanceAsset { public: void Fix(long); };
class TemplateAsset { public: void Fix(long); };
}  // namespace World

namespace Sext { class EventAny; }

template <class T>
class Pointer32 {
public:
    T Get() const;
};

namespace Util {
template <class T> void RTTID_Fix(void* p, long l) { ((T*)p)->Fix(l); }
}  // namespace Util

namespace Sext {

void FixWmlType(long l, int type, void* p) {
    switch (type) {
    case 798822953:
        *(long*)p += l;
        *(long*)((char*)p + 0x4) += l;
        break;

    case -1550835501:
        ((Sext::Curve*)p)->Fix(l);
        break;

    case -1681551399:
        *(long*)p += l;
        break;

    case 175888640:
        *(long*)((char*)p + 0x10) += l;
        break;

    case -1104554107:
        *(long*)p += l;
        break;

    case -1116751210:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case -478173534:
        ((World::ImmediateInstanceAsset*)p)->Fix(l);
        break;

    case 151935976:
        ((Sext::Clip*)p)->Fix(l);
        break;

    case 1651669435:
        *(long*)p += l;
        break;

    case 422527453:
        *(long*)((char*)p + 0x4) += l;
        FixWmlType(l, *(int*)p, *(void**)((char*)p + 0x4));
        *(long*)((char*)p + 0xC) += l;
        FixWmlType(l, *(int*)((char*)p + 0x8),
                   *(void**)((char*)p + 0xC));
        break;

    case -1149085410:
        {
            char* e = (*(char**)((char*)p + 0x4) += l);
            char* end = e + *(int*)p * 40;

            while (e != end) {
                Util::RTTID_Fix<Sext::DTRMovieSettings>(e + 4, l);
                FixWmlType(l, *(int*)e,
                           ((Pointer32<Sext::EventAny*>*)(e + 4))->Get());
                Util::RTTID_Fix<Sext::DTRMovieSettings>(e + 12, l);
                FixWmlType(l, *(int*)(e + 8),
                           ((Pointer32<Sext::EventAny*>*)(e + 12))->Get());
                e += 40;
            }
        }
        break;

    case -828968992:
        *(long*)((char*)p + 0x4) += l;
        *(long*)((char*)p + 0xC) += l;
        break;

    case 189966057:
        *(long*)((char*)p + 0x4) += l;
        *(long*)((char*)p + 0xC) += l;
        break;

    case 762263891:
        ((World::ModelInstanceAsset*)((char*)p + 0x30))->Fix(l);
        break;

    case -1361846843:
        *(long*)((char*)p + 0x4) += l;
        break;

    case 2005586424:
        *(long*)((char*)p + 0x4) += l;
        break;

    case -1617646906:
        ((Sext::Whatever2*)p)->Fix(l);
        break;

    case 1200733916:
        ((Sext::Whatever2*)((char*)p + 0xC))->Fix(l);
        break;

    case -113386345:
        ((Sext::Whatever2*)((char*)p + 0x1C))->Fix(l);
        if (*(long*)((char*)p + 0x34)) {
            *(long*)((char*)p + 0x34) += l;
        }
        break;

    case -113386343:
        *(long*)((char*)p + 0x14) += l;
        *(long*)((char*)p + 0x1C) += l;
        *(long*)((char*)p + 0x24) += l;
        *(long*)((char*)p + 0x30) += l;
        *(long*)((char*)p + 0x38) += l;
        break;

    case 278895828:
        *(long*)((char*)p + 0x28) += l;
        if (*(int*)((char*)p + 0x24) == 2) {
            char* e = *(char**)((char*)p + 0x28);
            if (*(long*)(e + 4)) {
                *(long*)(e + 4) += l;
                ((Sext::Whatever2*)(*(char**)(e + 4) + 12))->Fix(l);
            }
        }
        break;

    case -1261580861:
        *(long*)((char*)p + 0x34) += l;
        break;

    case 2136955483:
        *(long*)((char*)p + 0x20) += l;
        break;

    case 553761402:
        *(long*)((char*)p + 0x4) += l;
        *(long*)((char*)p + 0xC) += l;
        *(long*)((char*)p + 0x14) += l;
        if (*(long*)((char*)p + 0x18)) {
            *(long*)((char*)p + 0x18) += l;
        }
        if (*(long*)((char*)p + 0x1C)) {
            *(long*)((char*)p + 0x1C) += l;
        }
        if (*(long*)((char*)p + 0x20)) {
            *(long*)((char*)p + 0x20) += l;
        }
        *(long*)((char*)p + 0x24) += l;
        break;

    case 2043830543:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case -1281314017:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 937466530:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 1583630768:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        {
            char* e = (*(char**)((char*)p + 0x18) += l);
            char* end = e + *(int*)((char*)p + 0x14) * 40;

            while (e != end) {
                ((Sext::LinkAssetBaseNew::__srcEvent__*)e)->Fix(l);
                ((Sext::LinkAssetBaseNew::__srcEvent__*)(e + 8))->Fix(l);
                e += 40;
            }
        }
        break;

    case -2083284290:
        ((Sext::SoundBankSource*)p)->Fix(l);
        break;

    case -915518070:
        ((Sext::SoundBankSource*)p)->Fix(l);
        ((Sext::SoundBankSource*)((char*)p + 0xC))->Fix(l);
        ((Sext::SoundBankSource*)((char*)p + 0x18))->Fix(l);
        break;

    case 1329244266:
        *(long*)p += l;
        ((Sext::SoundBankSource*)((char*)p + 0x4))->Fix(l);
        break;

    case -1736377030:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 1462919013:
        ((Sext::zSoundsNamedAsset*)p)->Fix(l);
        break;

    case 307163269:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        ((Sext::SoundBankSource*)((char*)p + 0x28))->Fix(l);
        break;

    case 551162597:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        ((Sext::SoundBankSource*)((char*)p + 0x10))->Fix(l);
        break;

    case 1801694842:
        ((Sext::zSoundWiimoteSpeakerListAsset*)p)->Fix(l);
        break;

    case 1563962107:
        ((World::ModelInstanceAsset*)((char*)p + 0x20))->Fix(l);
        break;

    case -1576197354:
        ((Sext::SoundBankSource*)((char*)p + 0x1C))->Fix(l);
        ((Sext::SoundBankSource*)((char*)p + 0x28))->Fix(l);
        ((Sext::SoundBankSource*)((char*)p + 0x34))->Fix(l);
        break;

    case -496942199:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        ((World::ModelInstanceAsset*)((char*)p + 0x50))->Fix(l);
        ((Sext::PhysicsDataStruct*)((char*)p + 0x98))->Fix(l);
        break;

    case -1431069676:
        ((Sext::DestructibleAsset*)p)->Fix(l);
        break;

    case -1292565195:
        ((Sext::Decal*)p)->Fix(l);
        break;

    case 1776085875:
        ((Sext::AnimList*)p)->Fix(l);
        break;

    case -1480930058:
        ((Sext::SoundBankSource*)((char*)p + 0x8))->Fix(l);
        break;

    case -1887859445:
        *(long*)((char*)p + 0x14) += l;
        break;

    case 1636349426:
        ((Sext::AnimationSet*)p)->Fix(l);
        break;

    case 1143579:
        ((Sext::BSP*)p)->Fix(l);
        break;

    case 1392418029:
        ((Sext::xCamAsset*)p)->Fix(l);
        break;

    case 2018135435:
        ((Sext::xCamAsset*)p)->Fix(l);
        break;

    case -939020975:
        ((Sext::zMG2PCamAsset*)p)->Fix(l);
        break;

    case 1790980296:
        ((Sext::CurveCamera*)p)->Fix(l);
        break;

    case 160305452:
        ((Sext::CharacterAssets*)p)->Fix(l);
        break;

    case -1114381414:
        ((Sext::zCondAsset*)p)->Fix(l);
        break;

    case -953588996:
        ((Sext::xCounterAsset*)p)->Fix(l);
        break;

    case -1970398356:
        if (*(unsigned int*)((char*)p + 0x28) == 0) {
            *(long*)((char*)p + 0xC) += l;
        }
        if (*(unsigned int*)((char*)p + 0x28) == 1) {
            *(long*)((char*)p + 0x14) += l;
        }
        if (*(unsigned int*)((char*)p + 0x28) == 2) {
            *(long*)((char*)p + 0x1C) += l;
        }
        if (*(unsigned int*)((char*)p + 0x28) == 3) {
            *(long*)((char*)p + 0x24) += l;
        }
        break;

    case -616682125:
        ((Sext::zSaveLoadAsset*)p)->Fix(l);
        break;

    case 1088551191:
        ((Sext::zDispatcherAsset*)p)->Fix(l);
        break;

    case 1194413:
        ((Sext::xEnvAsset*)p)->Fix(l);
        break;

    case -379631693:
        ((Sext::zSaveLoadAsset*)p)->Fix(l);
        break;

    case 1748178859:
        ((Sext::xMovePointAsset*)p)->Fix(l);
        break;

    case -697670284:
        *(long*)((char*)p + 0x8) += l;
        break;

    case 2093266559:
        *(long*)((char*)p + 0x8) += l;
        break;

    case 56292717:
        *(long*)((char*)p + 0x8) += l;
        break;

    case 268231735:
        *(long*)((char*)p + 0x4) += l;
        break;

    case -857948335:
        ((Sext::zTacticalCommanderAsset*)p)->Fix(l);
        break;

    case -143537534:
        ((Sext::NPC_Combat*)p)->Fix(l);
        break;

    case -667493863:
        ((Sext::xEntPlayerAsset*)p)->Fix(l);
        break;

    case -1654696689:
        ((Sext::xPlatformAsset*)p)->Fix(l);
        break;

    case -2004290421:
        ((Sext::ProjectileAsset*)p)->Fix(l);
        break;

    case -1872028443:
        ((Sext::RuntimeEntityAsset*)p)->Fix(l);
        break;

    case 789270519:
        ((Sext::Script*)p)->Fix(l);
        break;

    case -1353883103:
        ((Sext::xSimpleObjAsset*)p)->Fix(l);
        break;

    case -866369251:
        ((Sext::xTimerAsset*)p)->Fix(l);
        break;

    case -1799419295:
        ((Sext::TriggerPhantomAsset*)p)->Fix(l);
        break;

    case -1378505423:
        ((Sext::xCounterAsset*)p)->Fix(l);
        break;

    case -1467754764:
        ((Sext::xCounterAsset*)p)->Fix(l);
        break;

    case 997483627:
        ((Sext::TriggerEntityAsset*)p)->Fix(l);
        break;

    case -87682670:
        ((World::ModelInstanceAsset*)((char*)p + 0x10))->Fix(l);
        break;

    case -1045669195:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 1614268447:
        ((Sext::SurfaceGamePlay*)p)->Fix(l);
        break;

    case 65271747:
        ((Sext::zDirectionAsset*)p)->Fix(l);
        break;

    case 254137112:
        ((Sext::xPortalAsset*)p)->Fix(l);
        break;

    case 1171363154:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        {
            long* a = (long*)(*(char**)((char*)p + 0x14) += l);
            long* aend = a + *(int*)((char*)p + 0x10);

            while (a != aend) {
                *a += l;
                a += 1;
            }
        }
        {
            char* e = (*(char**)((char*)p + 0x1C) += l);
            char* end = e + *(int*)((char*)p + 0x18) * 40;

            while (e != end) {
                *(long*)(e + 4) += l;
                FixWmlType(l, *(int*)e, *(void**)(e + 4));
                *(long*)(e + 12) += l;
                FixWmlType(l, *(int*)(e + 8), *(void**)(e + 12));
                e += 40;
            }
        }
        break;

    case 387806969:
        ((Sext::LinkAssetBaseNew::__srcEvent__*)p)->Fix(l);
        break;

    case 295328922:
        ((Sext::zEventSpyAsset*)p)->Fix(l);
        break;

    case -359438917:
        ((Sext::zPolygonalVolumeAsset*)p)->Fix(l);
        break;

    case 756554474:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 303932471:
        ((Sext::ElectricPointAsset*)p)->Fix(l);
        break;

    case -2118315667:
        ((Sext::ElectricArcAsset*)p)->Fix(l);
        break;

    case -1884150558:
        ((Sext::zFloatingCollectibleSpawnerAsset*)p)->Fix(l);
        break;

    case 1511914333:
        ((Sext::zPolygonalVolumeAsset*)p)->Fix(l);
        break;

    case -1196419464:
        ((Sext::zCondAsset*)p)->Fix(l);
        break;

    case -1020066002:
        ((Sext::zFloatingCollectibleAsset*)p)->Fix(l);
        break;

    case 1622271528:
        ((Sext::zBreakawayPlatformAsset*)p)->Fix(l);
        break;

    case -1753168175:
        ((Sext::ParticleSink*)p)->Fix(l);
        break;

    case 113975486:
        ((Sext::zCinematicAsset*)p)->Fix(l);
        break;

    case -1197889025:
        ((Sext::GradientCurve*)p)->Fix(l);
        break;

    case 1155000491:
        ((Sext::zPOWObjectAsset*)p)->Fix(l);
        break;

    case 1983842095:
        ((Sext::zPOWGroupAsset*)p)->Fix(l);
        break;

    case -2023376938:
        ((Sext::zInWorldIconWidgetAsset*)p)->Fix(l);
        break;

    case 39215315:
        ((Sext::LensFlareSpawnPt*)p)->Fix(l);
        break;

    case 759447915:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 576485256:
        ((Sext::xSimpleObjAsset*)p)->Fix(l);
        break;

    case -583453515:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 1757291539:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 1608736448:
        ((Sext::zRandomModelListAsset*)p)->Fix(l);
        break;

    case -1383906355:
        ((Sext::AnimPackage*)p)->Fix(l);
        break;

    case -91773352:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        ((World::ModelInstanceAsset*)((char*)p + 0x30))->Fix(l);
        break;

    case 629154819:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        ((World::ModelInstanceAsset*)((char*)p + 0x40))->Fix(l);
        ((World::ModelInstanceAsset*)((char*)p + 0xD0))->Fix(l);
        ((Sext::SoundBankSource*)((char*)p + 0x120))->Fix(l);
        break;

    case 1622701482:
        ((Sext::zUpFloatingBridgeAsset*)p)->Fix(l);
        break;

    case -950915804:
        ((Sext::zSwingVineAsset*)p)->Fix(l);
        break;

    case -1115645676:
        ((Sext::zRussellRopeAsset*)p)->Fix(l);
        break;

    case 1580424122:
        ((Sext::zDragRopeAsset*)p)->Fix(l);
        break;

    case 990738612:
        ((Sext::zInteractRopeTieAsset*)p)->Fix(l);
        break;

    case 1063760762:
        ((Sext::zLeverAsset*)p)->Fix(l);
        break;

    case -2040813851:
        ((Sext::zDogPackAsset*)p)->Fix(l);
        break;

    case 1063452113:
        ((Sext::Ledge*)p)->Fix(l);
        break;

    case 628819333:
        ((Sext::xTimerAsset*)p)->Fix(l);
        break;

    case -970567065:
        ((Sext::zInWorldIconWidgetAsset*)p)->Fix(l);
        break;

    case 1453335308:
        ((Sext::zDragRopeAsset*)p)->Fix(l);
        break;

    case 1407121242:
        ((Sext::CarlLedgeHoist*)p)->Fix(l);
        break;

    case -710399701:
        ((Sext::zPushPullAsset*)p)->Fix(l);
        break;

    case 190255441:
        ((Sext::zTrapAsset*)p)->Fix(l);
        break;

    case -275397429:
        ((Sext::xSubtitlesAsset*)p)->Fix(l);
        break;

    case 190256489:
        ((Sext::CarlLedgeHoist*)p)->Fix(l);
        break;

    case -2037829413:
        ((Sext::zManEatingPlantAsset*)p)->Fix(l);
        break;

    case -1726334820:
        ((Sext::zManEatingPlantAsset*)p)->Fix(l);
        break;

    case 1717275432:
        ((Sext::zCaveWormAsset*)p)->Fix(l);
        break;

    case -1723912525:
        ((Sext::zPushPullAsset*)p)->Fix(l);
        break;

    case 755971856:
        ((Sext::zHouseFloatAsset*)p)->Fix(l);
        break;

    case -1309733482:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 1471697475:
        ((Sext::zDragRopeAsset*)p)->Fix(l);
        break;

    case -1514711704:
        ((Sext::zSniffAsset*)p)->Fix(l);
        break;

    case 1892559119:
        ((Sext::zHouseBalloonBounceAsset*)p)->Fix(l);
        break;

    case -2073775304:
        ((Sext::zKevinSpringboardAsset*)p)->Fix(l);
        break;

    case 1383711:
        ((Sext::zPryAsset*)p)->Fix(l);
        break;

    case -1217568168:
        ((Sext::zDugLeverAsset*)p)->Fix(l);
        break;

    case -1557872553:
        ((Sext::zCrankAsset*)p)->Fix(l);
        break;

    case 77778756:
        ((Sext::zRopeCutAsset*)p)->Fix(l);
        break;

    case 452662965:
        ((Sext::zHitButtonAsset*)p)->Fix(l);
        break;

    case 1121520593:
        ((Sext::zTrampolineAsset*)p)->Fix(l);
        break;

    case -203808897:
        ((Sext::zPuckReflectorAsset*)p)->Fix(l);
        break;

    case 993086973:
        ((Sext::zSpinnerAsset*)p)->Fix(l);
        break;

    case 1016473566:
        ((Sext::zHammerAsset*)p)->Fix(l);
        break;

    case -21402543:
        ((Sext::zRubberBandAsset*)p)->Fix(l);
        break;

    case 1348327076:
        ((Sext::zFountainAsset*)p)->Fix(l);
        break;

    case 190102295:
        ((Sext::zTikiAsset*)p)->Fix(l);
        break;

    case -44097849:
        ((Sext::zBungeeBallAsset*)p)->Fix(l);
        break;

    case 1664585699:
        ((Sext::zInflatablePlatformAsset*)p)->Fix(l);
        break;

    case -837045092:
        ((Sext::zWaterWheelAsset*)p)->Fix(l);
        break;

    case -734089:
        ((Sext::zWaterAsset*)p)->Fix(l);
        break;

    case 2015318589:
        ((Sext::zCurrentAsset*)p)->Fix(l);
        break;

    case 1906999682:
        ((Sext::zWhirlpoolAsset*)p)->Fix(l);
        break;

    case 1695692970:
        ((Sext::zSinkingSurfaceAsset*)p)->Fix(l);
        break;

    case -1618681630:
        ((Sext::zLedgeShimmyAsset*)p)->Fix(l);
        break;

    case 2009818152:
        ((Sext::zHintSphereAsset*)p)->Fix(l);
        break;

    case -1154089149:
        ((Sext::zSlopeAsset*)p)->Fix(l);
        break;

    case -1119726864:
        ((Sext::zBugSpawnerAsset*)p)->Fix(l);
        break;

    case -1471946119:
        ((Sext::PlayerAnimSeq*)p)->Fix(l);
        break;

    case 210653836:
        ((Sext::InputMappingAsset*)p)->Fix(l);
        break;

    case -823135279:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case -622841007:
        ((Sext::zMG2PCamAsset*)p)->Fix(l);
        break;

    case -320212948:
        ((Sext::zPolygonalVolumeAsset*)p)->Fix(l);
        break;

    case -346459782:
        ((Sext::zBranchSwitchAsset*)p)->Fix(l);
        break;

    case -1448015923:
        ((Sext::SelectorNode*)p)->Fix(l);
        break;

    case 727322885:
        ((Sext::DecoratorNode*)p)->Fix(l);
        break;

    case -1011475288:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -797560863:
        *(long*)((char*)p + 0x10) += l;
        FixWmlType(l, *(int*)((char*)p + 0xC),
                   *(void**)((char*)p + 0x10));
        break;

    case -967145995:
        *(long*)((char*)p + 0x4) += l;
        FixWmlType(l, *(int*)p, *(void**)((char*)p + 0x4));
        break;

    case -301616589:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case 865626641:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case 1435568823:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -1794010979:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -423267305:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -638592055:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -964250911:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -650555275:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case 1315533874:
        *(long*)p += l;
        *(long*)((char*)p + 0x4) += l;
        break;

    case -55373099:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -1600247203:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case 1238507704:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -1874760420:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -1313168839:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case 1977812965:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -1935959370:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -1936183390:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case 615611227:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -2093863949:
        ((Sext::NPC_Action_MovementData*)p)->Fix(l);
        break;

    case -1342229918:
        ((Sext::NPC_Action_MovementData*)((char*)p + 0x4))->Fix(l);
        break;

    case 1038349756:
        ((Sext::NPC_Action_MovementData*)((char*)p + 0x8))->Fix(l);
        break;

    case 787692763:
        *(long*)((char*)p + 0xC) += l;
        *(long*)((char*)p + 0x14) += l;
        break;

    case 249492736:
        ((Sext::ActionNode*)p)->Fix(l);
        break;

    case 1619209077:
        ((Sext::ConditionNode*)p)->Fix(l);
        break;

    case -2073122736:
        ((Sext::BehaviorTree*)p)->Fix(l);
        break;

    case -605992392:
        ((Sext::BehaviorSet*)p)->Fix(l);
        break;

    case -1405030550:
        ((Sext::PlayerAICommand*)p)->Fix(l);
        break;

    case -1319706031:
        ((Sext::PlayerAICommandGroup*)p)->Fix(l);
        break;

    case 1319339999:
        ((Sext::zSoundMaskAsset*)p)->Fix(l);
        break;

    case 1211690:
        ((Sext::zWhirlpoolAsset*)p)->Fix(l);
        break;

    case -1274935458:
        ((Sext::zPolygonalVolumeAsset*)p)->Fix(l);
        break;

    case -413111097:
        ((Sext::xPlatformAsset*)p)->Fix(l);
        break;

    case -1273583229:
        ((Sext::zInteractiveMusicAsset*)p)->Fix(l);
        break;

    case 1908694374:
        *(long*)((char*)p + 0x44) += l;
        break;

    case -1815901490:
        ((Sext::zPolygonalVolumeAsset*)p)->Fix(l);
        break;

    case -1998197975:
        ((Sext::zGeyserAsset*)p)->Fix(l);
        break;

    case -159664877:
        ((Sext::zUpQuestCardAsset*)p)->Fix(l);
        break;

    case -1579685039:
        ((Sext::zDirectionAsset*)p)->Fix(l);
        break;

    case -1144235383:
        ((Sext::LaserAsset*)p)->Fix(l);
        break;

    case 1617330984:
        ((Sext::zDogPackAsset*)p)->Fix(l);
        break;

    case -31988820:
        ((World::TemplateAsset*)p)->Fix(l);
        break;

    case 2032394919:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case 418796747:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case -730586820:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case 1879608325:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case -90109602:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case -1751929287:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case 569064725:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case 1550448054:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case -1909420759:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case 887252645:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case 442010650:
        ((World::ModelInstanceAsset*)p)->Fix(l);
        break;

    case 263674518:
        ((Sext::VehicleConfiguration*)p)->Fix(l);
        break;

    case -749020665:
        ((Sext::TargetList*)p)->Fix(l);
        break;

    case 287494376:
        *(long*)p += l;
        break;

    case -734183123:
        *(long*)p += l;
        break;

    case 1157347722:
        *(long*)p += l;
        break;

    case -710859367:
        *(long*)p += l;
        break;

    case -596309199:
        *(long*)p += l;
        break;

    case 1778761999:
        *(long*)p += l;
        break;

    case -1642326103:
        *(long*)p += l;
        break;

    case -1755207715:
        *(long*)p += l;
        break;

    case -643972360:
        *(long*)p += l;
        break;

    case 563527989:
        ((Sext::Pointer*)p)->Fix(l);
        break;

    case -319975300:
        ((Sext::Button_Masher_Widget*)p)->Fix(l);
        break;

    case -1844335714:
        ((Sext::Flythrough*)p)->Fix(l);
        break;

    case 1743972558:
        ((Sext::zInWorldIconWidgetAsset*)p)->Fix(l);
        break;

    case -1806689046:
        ((Sext::zCurrentAsset*)p)->Fix(l);
        break;

    case 642581713:
        ((Sext::text_box*)p)->Fix(l);
        break;

    case 1788294005:
        ((Sext::Player_Location_Ent_Connector*)p)->Fix(l);
        break;

    case 304866275:
        ((Sext::zSaveLoadAsset*)p)->Fix(l);
        break;

    case -1783340654:
        ((Sext::xCounterAsset*)p)->Fix(l);
        break;

    case 1761871372:
        ((Sext::Function_Generator*)p)->Fix(l);
        break;

    case 1957535870:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 1555698:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case -1884700691:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 1190240396:
        ((Sext::UI_Text*)p)->Fix(l);
        break;

    case 1228989402:
        ((Sext::UI_User_String*)p)->Fix(l);
        break;

    case -1919241520:
        ((Sext::UI_Image*)p)->Fix(l);
        break;

    case -736694426:
        ((Sext::UI_Model*)p)->Fix(l);
        break;

    case -1860024348:
        ((Sext::UI_Box*)p)->Fix(l);
        break;

    case -986784485:
        ((Sext::UI_Controller*)p)->Fix(l);
        break;

    case 2039357403:
        ((Sext::UI_User_String*)p)->Fix(l);
        break;

    case -1981650723:
        ((Sext::zDispatcherAsset*)p)->Fix(l);
        break;

    case 1798208488:
        ((Sext::UI_Group*)p)->Fix(l);
        break;

    case -78576270:
        ((Sext::HudUp*)p)->Fix(l);
        break;

    case -78576546:
        ((Sext::zSaveLoadAsset*)p)->Fix(l);
        break;

    case -606252813:
        ((Sext::zSaveLoadAsset*)p)->Fix(l);
        break;

    case 1495384491:
        ((Sext::TikiScreen*)p)->Fix(l);
        break;

    case 475997126:
        ((Sext::BuyScreen*)p)->Fix(l);
        break;

    case -1378318244:
        ((World::ImmediateInstanceAsset*)p)->Fix(l);
        break;

    case 1698248788:
        ((Sext::LoadingScreen*)p)->Fix(l);
        break;

    case 1859156693:
        ((Sext::CarlLedgeHoist*)p)->Fix(l);
        break;

    case 831323220:
        ((Sext::Function_Generator*)p)->Fix(l);
        break;

    case -1849081434:
        ((Sext::zWhirlpoolAsset*)p)->Fix(l);
        break;

    case 1579111592:
        ((Sext::ScreenFade*)p)->Fix(l);
        break;

    case 961156738:
        ((Sext::ShrapnelAssetDef*)p)->Fix(l);
        break;

    case 1072496106:
        ((Sext::LightAsset*)p)->Fix(l);
        break;

    case 929721443:
        ((Sext::Button_Masher_Widget*)p)->Fix(l);
        break;

    case -856508802:
        ((Sext::CarlLedgeHoist*)p)->Fix(l);
        break;

    case -525637985:
        ((Sext::NPCPerceptionAsset*)p)->Fix(l);
        break;

    case -205833502:
        ((Sext::NPCGroupAsset*)p)->Fix(l);
        break;

    case -736274403:
        ((Sext::NPCGroupAsset*)p)->Fix(l);
        break;

    case 2867682:
        ((Sext::NPCGroupAsset*)p)->Fix(l);
        break;

    case 641723106:
        ((Sext::NPCGroupAsset*)p)->Fix(l);
        break;

    case -1136852767:
        *(long*)((char*)p + 0x8) += l;
        break;

    case 641215519:
        *(long*)((char*)p + 0x110) += l;
        break;

    case 748767651:
        ((Sext::NPCAsset*)p)->Fix(l);
        break;

    case 1538195659:
        ((Sext::NPCAsset*)p)->Fix(l);
        break;

    case -314849528:
        ((Sext::NPCAsset*)p)->Fix(l);
        break;

    case -350235010:
        ((Sext::NPCAsset*)p)->Fix(l);
        break;

    case 864598828:
        ((Sext::NPCAsset*)p)->Fix(l);
        break;

    case 223981161:
        ((Sext::NPCAsset*)p)->Fix(l);
        break;

    case 1674320693:
        ((Sext::NPCAsset*)p)->Fix(l);
        break;

    case 2010580078:
        ((Sext::NPCAsset*)p)->Fix(l);
        break;

    case 1376039481:
        ((Sext::NPCAsset*)p)->Fix(l);
        break;

    case -1174493840:
        ((Sext::Scene*)p)->Fix(l);
        break;

    case 1623714843:
        ((Sext::zDispatcherAsset*)p)->Fix(l);
        break;

    case -1122959124:
        ((Sext::binary_poi*)p)->Fix(l);
        break;

    case 770157464:
        ((Sext::zCheckpointAsset*)p)->Fix(l);
        break;

    case -19426899:
        ((Sext::Springboard*)p)->Fix(l);
        break;

    case -1699570958:
        ((Sext::Ribbon*)p)->Fix(l);
        break;

    case -1794113892:
        ((Sext::xCounterAsset*)p)->Fix(l);
        break;

    case -688205224:
        ((Sext::ExplosiveProperties*)p)->Fix(l);
        break;

    case 674073324:
        ((Sext::zWhirlpoolAsset*)p)->Fix(l);
        break;

    case 2022832498:
        ((Sext::zUIFlashOnScreenTextAsset*)p)->Fix(l);
        break;

    case 1733955146:
        ((Sext::zUIHintBoxAsset*)p)->Fix(l);
        break;

    case -1129814313:
        ((World::ModelInstanceAsset*)((char*)p + 0x10))->Fix(l);
        break;

    case 59059829:
        if (*(int*)p == 4) {
            ((World::ModelInstanceAsset*)((char*)p + 0x20))->Fix(l);
        }
        break;

    case 2120953911:
        ((Sext::FXParticleSystem*)p)->Fix(l);
        break;

    case 2025077100:
        ((Sext::FXObjectSystem*)p)->Fix(l);
        break;

    case -1710482515:
        ((Sext::FXSpawn*)p)->Fix(l);
        break;

    case -63054801:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case -1571119935:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        ((World::ModelInstanceAsset*)((char*)p + 0x40))->Fix(l);
        break;

    case -1919221771:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case 609408226:
        ((Sext::xBaseAsset*)p)->CustomFix(l);
        break;

    case -1517243578:
    case -616172351:
    case -113386344:
        return;

    }
}

}  // namespace Sext
